// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// AddNotificationByTrackingIdRequest 
type AddNotificationByTrackingIdRequest struct {
    // Notification Notification request object
    Notification NotificationRequestV1 `json:"notification,omitempty"`
}


