// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// CheckpointSource The source of the checkpoint, which can either be from the carrier or when the user marks the tracking as completed.
type CheckpointSource string

const (
	CheckpointSourceCarrier CheckpointSource = "carrier"
	CheckpointSourceUser    CheckpointSource = "user"
)
