// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// CheckpointEventsReason Describes the specific reason that led to the event.
type CheckpointEventsReason struct {
	// Code The code of the reason.
	Code *string `json:"code,omitempty"`
}

func (checkpointEventsReason *CheckpointEventsReason) SetCode(val string) {
	checkpointEventsReason.Code = &val
}
