// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// CheckpointEvents
type CheckpointEvents struct {
	// Code Represents the event code.
	Code *string `json:"code,omitempty"`
	// Reason Describes the specific reason that led to the event.
	Reason *CheckpointEventsReason `json:"reason,omitempty"`
}

func (checkpointEvents *CheckpointEvents) SetCode(val string) {
	checkpointEvents.Code = &val
}

func (checkpointEvents *CheckpointEvents) SetReason(val CheckpointEventsReason) {
	checkpointEvents.Reason = &val
}
