// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// CheckpointCoordinate The latitude and longitude coordinates indicate the precise location of the shipments that are currently in transit.
type CheckpointCoordinate struct {
	// Latitude Represents the latitude.
	Latitude *float64 `json:"latitude,omitempty"`
	// Longitude Represents the longitude.
	Longitude *float64 `json:"longitude,omitempty"`
}

func (checkpointCoordinate *CheckpointCoordinate) SetLatitude(val float64) {
	checkpointCoordinate.Latitude = &val
}

func (checkpointCoordinate *CheckpointCoordinate) SetLongitude(val float64) {
	checkpointCoordinate.Longitude = &val
}
