// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// CourierConnection This model represents user-created courier connection details. AfterShip will use this information to retrieve tracking updates from carriers based on the provided tracking numbers.
type CourierConnection struct {
	// Id The courier connection ID is a special set of numbers generated by AfterShip to define each user-created connection.
	Id *string `json:"id,omitempty"`
	// CourierSlug Unique courier code. Get courier codes .
	CourierSlug *string `json:"courier_slug,omitempty"`
	// Credentials It refers to the authentication details required for each specific carrier details required for each specific carrier (such as API keys, username, password, etc.) that the user must provide to establish a carrier connection. The content varies by carrier.
	Credentials map[string]string `json:"credentials,omitempty"`
	// CreatedAt The date and time the courier connection was created. It uses the format YYYY-MM-DDTHH:mm:ssZ for the timezone GMT +0.
	CreatedAt *string `json:"created_at,omitempty"`
	// UpdatedAt The date and time the courier connection was updated. It uses the format YYYY-MM-DDTHH:mm:ssZ for the timezone GMT +0.
	UpdatedAt *string `json:"updated_at,omitempty"`
}

func (courierConnection *CourierConnection) SetId(val string) {
	courierConnection.Id = &val
}

func (courierConnection *CourierConnection) SetCourierSlug(val string) {
	courierConnection.CourierSlug = &val
}

func (courierConnection *CourierConnection) SetCredentials(val map[string]string) {
	courierConnection.Credentials = val
}

func (courierConnection *CourierConnection) SetCreatedAt(val string) {
	courierConnection.CreatedAt = &val
}

func (courierConnection *CourierConnection) SetUpdatedAt(val string) {
	courierConnection.UpdatedAt = &val
}
