// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// CourierResponse Model of all couriers endpoint response
type CourierResponse struct {
	// Meta Meta data
	Meta Meta `json:"meta"`
	// Data
	Data CourierResponseData `json:"data"`
}

func (courierResponse *CourierResponse) SetMeta(val Meta) {
	courierResponse.Meta = val
}

func (courierResponse *CourierResponse) SetData(val CourierResponseData) {
	courierResponse.Data = val
}
