// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// CourierConnectionResponseForGetCourierConnectionsDataPagination
type CourierConnectionResponseForGetCourierConnectionsDataPagination struct {
	// Total The total number of courier connections.
	Total *int `json:"total,omitempty"`
	// NextCursor A string representing the cursor value for the next page of results.
	NextCursor *string `json:"next_cursor,omitempty"`
	// HasNextPage To indicate if next page is available.
	HasNextPage *bool `json:"has_next_page,omitempty"`
}

func (courierConnectionResponseForGetCourierConnectionsDataPagination *CourierConnectionResponseForGetCourierConnectionsDataPagination) SetTotal(val int) {
	courierConnectionResponseForGetCourierConnectionsDataPagination.Total = &val
}

func (courierConnectionResponseForGetCourierConnectionsDataPagination *CourierConnectionResponseForGetCourierConnectionsDataPagination) SetNextCursor(val string) {
	courierConnectionResponseForGetCourierConnectionsDataPagination.NextCursor = &val
}

func (courierConnectionResponseForGetCourierConnectionsDataPagination *CourierConnectionResponseForGetCourierConnectionsDataPagination) SetHasNextPage(val bool) {
	courierConnectionResponseForGetCourierConnectionsDataPagination.HasNextPage = &val
}
