// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// CourierCredentials Refers to the authentication details required for each specific carrier (such as API keys, username, password, etc.) that the user must provide to create a carrier connection. The content varies by carrier.
type CourierCredentials struct {
	// Fields Through this field, users can get the specific authentication information needed when creating a courier connection to one specific carrier, such as API keys, usernames, and passwords. Each field includes properties like name, data type, and whether it's required.
	Fields []CredentialField `json:"fields,omitempty"`
}

func (courierCredentials *CourierCredentials) SetFields(val []CredentialField) {
	courierCredentials.Fields = val
}
