// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// CourierConnectionResponseForGetCourierConnectionsData
type CourierConnectionResponseForGetCourierConnectionsData struct {
	// Pagination
	Pagination *CourierConnectionResponseForGetCourierConnectionsDataPagination `json:"pagination,omitempty"`
	// CourierConnections
	CourierConnections []CourierConnection `json:"courier_connections,omitempty"`
}

func (courierConnectionResponseForGetCourierConnectionsData *CourierConnectionResponseForGetCourierConnectionsData) SetPagination(val CourierConnectionResponseForGetCourierConnectionsDataPagination) {
	courierConnectionResponseForGetCourierConnectionsData.Pagination = &val
}

func (courierConnectionResponseForGetCourierConnectionsData *CourierConnectionResponseForGetCourierConnectionsData) SetCourierConnections(val []CourierConnection) {
	courierConnectionResponseForGetCourierConnectionsData.CourierConnections = val
}
