// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// CourierResponse Model of all couriers endpoint response
type CourierResponse struct {
	// Meta Meta data
	Meta Meta `json:"meta"`
	// Data
	Data *DataCourierResponse `json:"data"`
}

// DataCourierResponse
type DataCourierResponse struct {
	// Total Total count of courier objects
	Total int `json:"total,omitempty"`
	// Couriers Array of  object.
	Couriers []Courier `json:"couriers,omitempty"`
}
