// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// CourierConnectionResponseForGetCourierConnections Courier connection response for getting courier connections
type CourierConnectionResponseForGetCourierConnections struct {
	// Meta Meta data
	Meta Meta `json:"meta"`
	// Data
	Data *CourierConnectionResponseForGetCourierConnectionsData `json:"data,omitempty"`
}

func (courierConnectionResponseForGetCourierConnections *CourierConnectionResponseForGetCourierConnections) SetMeta(val Meta) {
	courierConnectionResponseForGetCourierConnections.Meta = val
}

func (courierConnectionResponseForGetCourierConnections *CourierConnectionResponseForGetCourierConnections) SetData(val CourierConnectionResponseForGetCourierConnectionsData) {
	courierConnectionResponseForGetCourierConnections.Data = &val
}
