// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// CourierResponseData
type CourierResponseData struct {
	// Total Total count of courier objects
	Total *int `json:"total,omitempty"`
	// Couriers Array of  object.
	Couriers []Courier `json:"couriers,omitempty"`
}

func (courierResponseData *CourierResponseData) SetTotal(val int) {
	courierResponseData.Total = &val
}

func (courierResponseData *CourierResponseData) SetCouriers(val []Courier) {
	courierResponseData.Couriers = val
}
