// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// CreateTrackingRequestDeliveryType Shipment delivery type- pickup_at_store- pickup_at_courier- door_to_door
type CreateTrackingRequestDeliveryType string

const (
	CreateTrackingRequestDeliveryTypePickupAtStore   CreateTrackingRequestDeliveryType = "pickup_at_store"
	CreateTrackingRequestDeliveryTypeDoorToDoor      CreateTrackingRequestDeliveryType = "door_to_door"
	CreateTrackingRequestDeliveryTypePickupAtCourier CreateTrackingRequestDeliveryType = "pickup_at_courier"
)
