// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// CreateTrackingRequestCustomers
type CreateTrackingRequestCustomers struct {
	// Role The  role of the customer, indicating whether the customer is  an individual or a company.
	Role *string `json:"role,omitempty"`
	// Name Customer name associated with the tracking.
	Name *string `json:"name,omitempty"`
	// PhoneNumber The phone number(s) to receive SMS notifications. Phone numbers should begin with a `+` sign and include the area code.
	PhoneNumber *string `json:"phone_number,omitempty"`
	// Email Email address(es) to receive email notifications.
	Email *string `json:"email,omitempty"`
	// Language The preferred language of the customer. If you have set up AfterShip notifications in different languages, we use this to send the tracking updates to the customer in their preferred language.
	Language *string `json:"language,omitempty"`
}

func (createTrackingRequestCustomers *CreateTrackingRequestCustomers) SetRole(val string) {
	createTrackingRequestCustomers.Role = &val
}

func (createTrackingRequestCustomers *CreateTrackingRequestCustomers) SetName(val string) {
	createTrackingRequestCustomers.Name = &val
}

func (createTrackingRequestCustomers *CreateTrackingRequestCustomers) SetPhoneNumber(val string) {
	createTrackingRequestCustomers.PhoneNumber = &val
}

func (createTrackingRequestCustomers *CreateTrackingRequestCustomers) SetEmail(val string) {
	createTrackingRequestCustomers.Email = &val
}

func (createTrackingRequestCustomers *CreateTrackingRequestCustomers) SetLanguage(val string) {
	createTrackingRequestCustomers.Language = &val
}
