// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// CreateTrackingRequestLastMile This field contains information about the last leg of the shipment, starting from the carrier who hands it over to the last-mile carrier, all the way to delivery. Once AfterShip detects that the shipment involves multiple legs and identifies the last-mile carrier, we will populate the last-mile carrier information in this object. Alternatively, the user can provide this information in this field to specify the last-mile carrier, which is helpful if AfterShip is unable to detect it automatically.
type CreateTrackingRequestLastMile struct {
	// TrackingNumber The tracking number of the last-mile carrier.
	TrackingNumber string `json:"tracking_number"`
	// Slug The unique code of the carrier responsible for the last-mile of the shipment.  Find all the courier slugs .
	Slug *string `json:"slug,omitempty"`
}

func (createTrackingRequestLastMile *CreateTrackingRequestLastMile) SetTrackingNumber(val string) {
	createTrackingRequestLastMile.TrackingNumber = val
}

func (createTrackingRequestLastMile *CreateTrackingRequestLastMile) SetSlug(val string) {
	createTrackingRequestLastMile.Slug = &val
}
