// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// CreateTrackingRequestOrderPromisedDeliveryDate The promised delivery date of the order in shipment recipient’s timezone.
type CreateTrackingRequestOrderPromisedDeliveryDate struct {
	// PromisedDeliveryDate The promised delivery date of the order.It uses the formats:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	PromisedDeliveryDate *string `json:"promised_delivery_date,omitempty"`
	// PromisedDeliveryDateMin Earliest promised delivery date of the order. It uses the formats:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	PromisedDeliveryDateMin *string `json:"promised_delivery_date_min,omitempty"`
	// PromisedDeliveryDateMax Latest promised delivery date of the order. It uses the formats:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	PromisedDeliveryDateMax *string `json:"promised_delivery_date_max,omitempty"`
}

func (createTrackingRequestOrderPromisedDeliveryDate *CreateTrackingRequestOrderPromisedDeliveryDate) SetPromisedDeliveryDate(val string) {
	createTrackingRequestOrderPromisedDeliveryDate.PromisedDeliveryDate = &val
}

func (createTrackingRequestOrderPromisedDeliveryDate *CreateTrackingRequestOrderPromisedDeliveryDate) SetPromisedDeliveryDateMin(val string) {
	createTrackingRequestOrderPromisedDeliveryDate.PromisedDeliveryDateMin = &val
}

func (createTrackingRequestOrderPromisedDeliveryDate *CreateTrackingRequestOrderPromisedDeliveryDate) SetPromisedDeliveryDateMax(val string) {
	createTrackingRequestOrderPromisedDeliveryDate.PromisedDeliveryDateMax = &val
}
