// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// DeleteTrackingByIdResponse 
type DeleteTrackingByIdResponse struct {
    // Tracking Partial tracking model
    Tracking PartialDeleteTracking `json:"tracking,omitempty"`
}


