// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// DeleteNotificationByTrackingIdResponse 
type DeleteNotificationByTrackingIdResponse struct {
    // Notification Object describes the notification information.
    Notification Notification `json:"notification,omitempty"`
}


