// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// DeleteTrackingBySlugTrackingNumberResponse 
type DeleteTrackingBySlugTrackingNumberResponse struct {
    // Tracking Partial tracking model
    Tracking PartialDeleteTracking `json:"tracking,omitempty"`
}


