// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// DeleteNotificationByTrackingIdRequest 
type DeleteNotificationByTrackingIdRequest struct {
    // Notification Notification request object
    Notification NotificationRequestV1 `json:"notification,omitempty"`
}


