// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// DetectCourierRequest 
type DetectCourierRequest struct {
    // Tracking Detect courier request
    Tracking *TrackingDetectCourierRequest `json:"tracking,omitempty"`
}

// TrackingDetectCourierRequest 
type TrackingDetectCourierRequest struct {
    // TrackingNumber Tracking number of a shipment.
    TrackingNumber string `json:"tracking_number,omitempty"`
    // Slug If not specified, Aftership will automatically detect the courier based on the tracking number format and your . Use array or comma separated to input a list of couriers for auto detect. Cannot be used with slug_group at the same time.
    Slug []string `json:"slug,omitempty"`
    // TrackingPostalCode The postal code of receiver's address. Required by some couriers. Refer to  for more details
    TrackingPostalCode string `json:"tracking_postal_code,omitempty"`
    // TrackingShipDate Shipping date in `YYYYMMDD` format. Required by some couriers. Refer to  for more details
    TrackingShipDate string `json:"tracking_ship_date,omitempty"`
    // TrackingAccountNumber Account number of the shipper for a specific courier. Required by some couriers. Refer to  for more details
    TrackingAccountNumber string `json:"tracking_account_number,omitempty"`
    // TrackingKey Key of the shipment for a specific courier. Required by some couriers. Refer to  for more details
    TrackingKey string `json:"tracking_key,omitempty"`
    // TrackingOriginCountry Origin Country/Region of the shipment for a specific courier. Required by some couriers.
    TrackingOriginCountry string `json:"tracking_origin_country,omitempty"`
    // TrackingDestinationCountry Destination Country/Region of the shipment for a specific courier. Required by some couriers. Refer to  for more details
    TrackingDestinationCountry string `json:"tracking_destination_country,omitempty"`
    // TrackingState State of the destination shipping address of the shipment. Required by some couriers.
    TrackingState string `json:"tracking_state,omitempty"`
    // SlugGroup Slug group is a group of slugs which belong to same courier. For example, when you inpit "fedex-group" as slug_group, AfterShip will detect the tracking with "fedex-uk", "fedex-fims", and other slugs which belong to "fedex". It cannot be used with slug at the same time. (
    SlugGroup SlugGroupV1 `json:"slug_group,omitempty"`
    // OriginCountryIso3 Enter .
    OriginCountryIso3 string `json:"origin_country_iso3,omitempty"`
    // DestinationCountryIso3 Enter .
    DestinationCountryIso3 string `json:"destination_country_iso3,omitempty"`
}


