// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// DetectCourierResponseData
type DetectCourierResponseData struct {
	// Total Total count of courier objects
	Total *int `json:"total,omitempty"`
	// Couriers Array of  object.
	Couriers []Courier `json:"couriers,omitempty"`
}

func (detectCourierResponseData *DetectCourierResponseData) SetTotal(val int) {
	detectCourierResponseData.Total = &val
}

func (detectCourierResponseData *DetectCourierResponseData) SetCouriers(val []Courier) {
	detectCourierResponseData.Couriers = val
}
