// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// DetectCourierResponse 
type DetectCourierResponse struct {
    // Total Total count of courier objects
    Total int `json:"total,omitempty"`
    // Couriers Array of  object.
    Couriers []Courier `json:"couriers,omitempty"`
}


