// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// EstimatedDeliveryDateRequestWeight AfterShip uses this object to calculate the total weight of the order.
type EstimatedDeliveryDateRequestWeight struct {
	// Unit The weight unit of the package.
	Unit string `json:"unit"`
	// Value The weight of the shipment.
	Value float64 `json:"value"`
}

func (estimatedDeliveryDateRequestWeight *EstimatedDeliveryDateRequestWeight) SetUnit(val string) {
	estimatedDeliveryDateRequestWeight.Unit = val
}

func (estimatedDeliveryDateRequestWeight *EstimatedDeliveryDateRequestWeight) SetValue(val float64) {
	estimatedDeliveryDateRequestWeight.Value = val
}
