// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// EstimatedDeliveryDateResponse
type EstimatedDeliveryDateResponse struct {
	// Id A string that acts as a unique identifier for the estimated delivery date value generated by AfterShip Predict API
	Id string `json:"id"`
	// Slug AfterShip's unique code of courier. Please refer to https://track.aftership.com/couriers/download.
	Slug string `json:"slug"`
	// ServiceTypeName AfterShip’s unique code represents carrier’s shipping and delivery options. Refer to .
	ServiceTypeName *string `json:"service_type_name,omitempty"`
	// OriginAddress The location from where the package is picked up by the carrier to be delivered to the final destination.
	OriginAddress EstimatedDeliveryDateResponseOriginAddress `json:"origin_address"`
	// DestinationAddress The final destination of the customer where the delivery will be made.
	DestinationAddress EstimatedDeliveryDateResponseDestinationAddress `json:"destination_address"`
	// Weight AfterShip uses this object to calculate the total weight of the order.
	Weight *EstimatedDeliveryDateResponseWeight `json:"weight,omitempty"`
	// PackageCount The number of packages.
	PackageCount *int `json:"package_count,omitempty"`
	// PickupTime The local pickup time in the origin address time zone of the package.Either `pickup_time` or `estimated_pickup` is required.
	PickupTime *string `json:"pickup_time,omitempty"`
	// EstimatedPickup The local pickup time of the package.Either `pickup_time` or `estimated_pickup` is required.
	EstimatedPickup *EstimatedDeliveryDateResponseEstimatedPickup `json:"estimated_pickup,omitempty"`
	// EstimatedDeliveryDate The estimated arrival date of the shipment, provided by AfterShip.
	EstimatedDeliveryDate *string `json:"estimated_delivery_date,omitempty"`
	// ConfidenceCode Indicates the confidence level and associated reason for an AI EDD prediction request. For a comprehensive list of confidence codes, refer to .
	ConfidenceCode *float64 `json:"confidence_code,omitempty"`
	// EstimatedDeliveryDateMin The earliest estimated delivery date of the shipment, provided by AfterShip.
	EstimatedDeliveryDateMin *string `json:"estimated_delivery_date_min,omitempty"`
	// EstimatedDeliveryDateMax The latest estimated delivery date of the shipment, provided by AfterShip.
	EstimatedDeliveryDateMax *string `json:"estimated_delivery_date_max,omitempty"`
}

func (estimatedDeliveryDateResponse *EstimatedDeliveryDateResponse) SetId(val string) {
	estimatedDeliveryDateResponse.Id = val
}

func (estimatedDeliveryDateResponse *EstimatedDeliveryDateResponse) SetSlug(val string) {
	estimatedDeliveryDateResponse.Slug = val
}

func (estimatedDeliveryDateResponse *EstimatedDeliveryDateResponse) SetServiceTypeName(val string) {
	estimatedDeliveryDateResponse.ServiceTypeName = &val
}

func (estimatedDeliveryDateResponse *EstimatedDeliveryDateResponse) SetOriginAddress(val EstimatedDeliveryDateResponseOriginAddress) {
	estimatedDeliveryDateResponse.OriginAddress = val
}

func (estimatedDeliveryDateResponse *EstimatedDeliveryDateResponse) SetDestinationAddress(val EstimatedDeliveryDateResponseDestinationAddress) {
	estimatedDeliveryDateResponse.DestinationAddress = val
}

func (estimatedDeliveryDateResponse *EstimatedDeliveryDateResponse) SetWeight(val EstimatedDeliveryDateResponseWeight) {
	estimatedDeliveryDateResponse.Weight = &val
}

func (estimatedDeliveryDateResponse *EstimatedDeliveryDateResponse) SetPackageCount(val int) {
	estimatedDeliveryDateResponse.PackageCount = &val
}

func (estimatedDeliveryDateResponse *EstimatedDeliveryDateResponse) SetPickupTime(val string) {
	estimatedDeliveryDateResponse.PickupTime = &val
}

func (estimatedDeliveryDateResponse *EstimatedDeliveryDateResponse) SetEstimatedPickup(val EstimatedDeliveryDateResponseEstimatedPickup) {
	estimatedDeliveryDateResponse.EstimatedPickup = &val
}

func (estimatedDeliveryDateResponse *EstimatedDeliveryDateResponse) SetEstimatedDeliveryDate(val string) {
	estimatedDeliveryDateResponse.EstimatedDeliveryDate = &val
}

func (estimatedDeliveryDateResponse *EstimatedDeliveryDateResponse) SetConfidenceCode(val float64) {
	estimatedDeliveryDateResponse.ConfidenceCode = &val
}

func (estimatedDeliveryDateResponse *EstimatedDeliveryDateResponse) SetEstimatedDeliveryDateMin(val string) {
	estimatedDeliveryDateResponse.EstimatedDeliveryDateMin = &val
}

func (estimatedDeliveryDateResponse *EstimatedDeliveryDateResponse) SetEstimatedDeliveryDateMax(val string) {
	estimatedDeliveryDateResponse.EstimatedDeliveryDateMax = &val
}
