// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// EstimatedDeliveryDateResponseEstimatedPickup The local pickup time of the package.Either `pickup_time` or `estimated_pickup` is required.
type EstimatedDeliveryDateResponseEstimatedPickup struct {
	// OrderTime The local order time in the origin address time zone of the package.
	OrderTime string `json:"order_time"`
	// OrderCutoffTime Order cut off time in the origin address time zone. The default value set by AfterShip is 18:00:00.
	OrderCutoffTime *string `json:"order_cutoff_time,omitempty"`
	// BusinessDays Operating days in a week. Number refers to the weekday.E.g., [1,2,3,4,5] means operating days are from Monday to Friday.AfterShip will set [1,2,3,4,5] as the default value.
	BusinessDays []int `json:"business_days,omitempty"`
	// OrderProcessingTime
	OrderProcessingTime *EstimatedDeliveryDateResponseEstimatedPickupOrderProcessingTime `json:"order_processing_time,omitempty"`
	// PickupTime The local pickup time of the package.
	PickupTime *string `json:"pickup_time,omitempty"`
}

func (estimatedDeliveryDateResponseEstimatedPickup *EstimatedDeliveryDateResponseEstimatedPickup) SetOrderTime(val string) {
	estimatedDeliveryDateResponseEstimatedPickup.OrderTime = val
}

func (estimatedDeliveryDateResponseEstimatedPickup *EstimatedDeliveryDateResponseEstimatedPickup) SetOrderCutoffTime(val string) {
	estimatedDeliveryDateResponseEstimatedPickup.OrderCutoffTime = &val
}

func (estimatedDeliveryDateResponseEstimatedPickup *EstimatedDeliveryDateResponseEstimatedPickup) SetBusinessDays(val []int) {
	estimatedDeliveryDateResponseEstimatedPickup.BusinessDays = val
}

func (estimatedDeliveryDateResponseEstimatedPickup *EstimatedDeliveryDateResponseEstimatedPickup) SetOrderProcessingTime(val EstimatedDeliveryDateResponseEstimatedPickupOrderProcessingTime) {
	estimatedDeliveryDateResponseEstimatedPickup.OrderProcessingTime = &val
}

func (estimatedDeliveryDateResponseEstimatedPickup *EstimatedDeliveryDateResponseEstimatedPickup) SetPickupTime(val string) {
	estimatedDeliveryDateResponseEstimatedPickup.PickupTime = &val
}
