// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// EstimatedDeliveryDateResponseWeight AfterShip uses this object to calculate the total weight of the order.
type EstimatedDeliveryDateResponseWeight struct {
	// Unit The weight unit of the package.
	Unit string `json:"unit"`
	// Value The weight of the shipment.
	Value float64 `json:"value"`
}

func (estimatedDeliveryDateResponseWeight *EstimatedDeliveryDateResponseWeight) SetUnit(val string) {
	estimatedDeliveryDateResponseWeight.Unit = val
}

func (estimatedDeliveryDateResponseWeight *EstimatedDeliveryDateResponseWeight) SetValue(val float64) {
	estimatedDeliveryDateResponseWeight.Value = val
}
