// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// EstimatedDeliveryDateRequest
type EstimatedDeliveryDateRequest struct {
	// Slug AfterShip's unique code of courier. Please refer to https://track.aftership.com/couriers/download.
	Slug string `json:"slug"`
	// ServiceTypeName AfterShip’s unique code represents carrier’s shipping and delivery options. Refer to .
	ServiceTypeName *string `json:"service_type_name,omitempty"`
	// OriginAddress The location from where the package is picked up by the carrier to be delivered to the final destination.
	OriginAddress EstimatedDeliveryDateRequestOriginAddress `json:"origin_address"`
	// DestinationAddress The final destination of the customer where the delivery will be made.
	DestinationAddress EstimatedDeliveryDateRequestDestinationAddress `json:"destination_address"`
	// Weight AfterShip uses this object to calculate the total weight of the order.
	Weight *EstimatedDeliveryDateRequestWeight `json:"weight,omitempty"`
	// PackageCount The number of packages.
	PackageCount *int `json:"package_count,omitempty"`
	// PickupTime The local pickup time in the origin address time zone of the package.Either `pickup_time` or `estimated_pickup` is required.
	PickupTime *string `json:"pickup_time,omitempty"`
	// EstimatedPickup The local pickup time of the package.Either `pickup_time` or `estimated_pickup` is required.
	EstimatedPickup *EstimatedDeliveryDateRequestEstimatedPickup `json:"estimated_pickup,omitempty"`
}

func (estimatedDeliveryDateRequest *EstimatedDeliveryDateRequest) SetSlug(val string) {
	estimatedDeliveryDateRequest.Slug = val
}

func (estimatedDeliveryDateRequest *EstimatedDeliveryDateRequest) SetServiceTypeName(val string) {
	estimatedDeliveryDateRequest.ServiceTypeName = &val
}

func (estimatedDeliveryDateRequest *EstimatedDeliveryDateRequest) SetOriginAddress(val EstimatedDeliveryDateRequestOriginAddress) {
	estimatedDeliveryDateRequest.OriginAddress = val
}

func (estimatedDeliveryDateRequest *EstimatedDeliveryDateRequest) SetDestinationAddress(val EstimatedDeliveryDateRequestDestinationAddress) {
	estimatedDeliveryDateRequest.DestinationAddress = val
}

func (estimatedDeliveryDateRequest *EstimatedDeliveryDateRequest) SetWeight(val EstimatedDeliveryDateRequestWeight) {
	estimatedDeliveryDateRequest.Weight = &val
}

func (estimatedDeliveryDateRequest *EstimatedDeliveryDateRequest) SetPackageCount(val int) {
	estimatedDeliveryDateRequest.PackageCount = &val
}

func (estimatedDeliveryDateRequest *EstimatedDeliveryDateRequest) SetPickupTime(val string) {
	estimatedDeliveryDateRequest.PickupTime = &val
}

func (estimatedDeliveryDateRequest *EstimatedDeliveryDateRequest) SetEstimatedPickup(val EstimatedDeliveryDateRequestEstimatedPickup) {
	estimatedDeliveryDateRequest.EstimatedPickup = &val
}
