// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// EstimatedDeliveryDateRequestEstimatedPickup The local pickup time of the package.</br><span style=color:#ff6b2b;padding:2px>**Either `pickup_time` or `estimated_pickup` is required.**</span>
type EstimatedDeliveryDateRequestEstimatedPickup struct {
	// OrderTime The local order time in the origin address time zone of the package.
	OrderTime string `json:"order_time"`
	// OrderCutoffTime Order cut off time in the origin address time zone. The default value set by AfterShip is 18:00:00.
	OrderCutoffTime *string `json:"order_cutoff_time,omitempty"`
	// BusinessDays Operating days in a week. Number refers to the weekday.E.g., [1,2,3,4,5] means operating days are from Monday to Friday.AfterShip will set [1,2,3,4,5] as the default value.
	BusinessDays []int `json:"business_days,omitempty"`
	// OrderProcessingTime
	OrderProcessingTime *EstimatedDeliveryDateRequestEstimatedPickupOrderProcessingTime `json:"order_processing_time,omitempty"`
}

func (estimatedDeliveryDateRequestEstimatedPickup *EstimatedDeliveryDateRequestEstimatedPickup) SetOrderTime(val string) {
	estimatedDeliveryDateRequestEstimatedPickup.OrderTime = val
}

func (estimatedDeliveryDateRequestEstimatedPickup *EstimatedDeliveryDateRequestEstimatedPickup) SetOrderCutoffTime(val string) {
	estimatedDeliveryDateRequestEstimatedPickup.OrderCutoffTime = &val
}

func (estimatedDeliveryDateRequestEstimatedPickup *EstimatedDeliveryDateRequestEstimatedPickup) SetBusinessDays(val []int) {
	estimatedDeliveryDateRequestEstimatedPickup.BusinessDays = val
}

func (estimatedDeliveryDateRequestEstimatedPickup *EstimatedDeliveryDateRequestEstimatedPickup) SetOrderProcessingTime(val EstimatedDeliveryDateRequestEstimatedPickupOrderProcessingTime) {
	estimatedDeliveryDateRequestEstimatedPickup.OrderProcessingTime = &val
}
