// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// EstimatedDeliveryDateResponseDestinationAddress The final destination of the customer where the delivery will be made.
type EstimatedDeliveryDateResponseDestinationAddress struct {
	// CountryRegion The country/region of the destination location where the package will be delivered. Use 3 letters of ISO 3166-1 country code.
	CountryRegion string `json:"country_region"`
	// State State, province, or the equivalent location of the destination address where the package will be delivered.Either `destination_address.state` or `destination_address.postal_code` is required.
	State *string `json:"state,omitempty"`
	// City City of the destination address where the package will be delivered.
	City *string `json:"city,omitempty"`
	// PostalCode Postal code of the destination address.Either `destination_address.state` or `destination_address.postal_code` is required.
	PostalCode *string `json:"postal_code,omitempty"`
	// RawLocation Raw location of the destination address. A raw address will help AI to identify the accurate location of the destination address.
	RawLocation *string `json:"raw_location,omitempty"`
}

func (estimatedDeliveryDateResponseDestinationAddress *EstimatedDeliveryDateResponseDestinationAddress) SetCountryRegion(val string) {
	estimatedDeliveryDateResponseDestinationAddress.CountryRegion = val
}

func (estimatedDeliveryDateResponseDestinationAddress *EstimatedDeliveryDateResponseDestinationAddress) SetState(val string) {
	estimatedDeliveryDateResponseDestinationAddress.State = &val
}

func (estimatedDeliveryDateResponseDestinationAddress *EstimatedDeliveryDateResponseDestinationAddress) SetCity(val string) {
	estimatedDeliveryDateResponseDestinationAddress.City = &val
}

func (estimatedDeliveryDateResponseDestinationAddress *EstimatedDeliveryDateResponseDestinationAddress) SetPostalCode(val string) {
	estimatedDeliveryDateResponseDestinationAddress.PostalCode = &val
}

func (estimatedDeliveryDateResponseDestinationAddress *EstimatedDeliveryDateResponseDestinationAddress) SetRawLocation(val string) {
	estimatedDeliveryDateResponseDestinationAddress.RawLocation = &val
}
