// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// EstimatedDeliveryDateRequestEstimatedPickupOrderProcessingTime
type EstimatedDeliveryDateRequestEstimatedPickupOrderProcessingTime struct {
	// Unit Processing time of an order, from being placed to being picked up. Only support day as value now.AfterShip will set day as the default value.
	Unit *string `json:"unit,omitempty"`
	// Value Processing time of an order, from being placed to being picked up.AfterShip will set 0 as the default value.
	Value *float64 `json:"value,omitempty"`
}

func (estimatedDeliveryDateRequestEstimatedPickupOrderProcessingTime *EstimatedDeliveryDateRequestEstimatedPickupOrderProcessingTime) SetUnit(val string) {
	estimatedDeliveryDateRequestEstimatedPickupOrderProcessingTime.Unit = &val
}

func (estimatedDeliveryDateRequestEstimatedPickupOrderProcessingTime *EstimatedDeliveryDateRequestEstimatedPickupOrderProcessingTime) SetValue(val float64) {
	estimatedDeliveryDateRequestEstimatedPickupOrderProcessingTime.Value = &val
}
