// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// EstimatedDeliveryDateRequestOriginAddress The location from where the package is picked up by the carrier to be delivered to the final destination.
type EstimatedDeliveryDateRequestOriginAddress struct {
	// CountryRegion The country/region of the origin location from where the package is picked up by the carrier to be delivered to the final destination. Use 3 letters of ISO 3166-1 country/region code.
	CountryRegion string `json:"country_region"`
	// State State, province, or the equivalent location of the origin address. Use 3 letters of ISO 3166-1 country/region code for countries/regions without state. Either `origin_address.state` or `origin_address.postal_code` is required.
	State *string `json:"state,omitempty"`
	// City City of the origin address. Use 3 letters of ISO 3166-1 country/region code for countries/regions without City.
	City *string `json:"city,omitempty"`
	// PostalCode Postal code of the origin address. Use 3 letters of ISO 3166-1 country/region code for countries/regions without postal code. Either `origin_address.state` or `origin_address.postal_code` is required.
	PostalCode *string `json:"postal_code,omitempty"`
	// RawLocation Raw location of the origin address. A raw address will help AI to identify the accurate location of the origin address.
	RawLocation *string `json:"raw_location,omitempty"`
}

func (estimatedDeliveryDateRequestOriginAddress *EstimatedDeliveryDateRequestOriginAddress) SetCountryRegion(val string) {
	estimatedDeliveryDateRequestOriginAddress.CountryRegion = val
}

func (estimatedDeliveryDateRequestOriginAddress *EstimatedDeliveryDateRequestOriginAddress) SetState(val string) {
	estimatedDeliveryDateRequestOriginAddress.State = &val
}

func (estimatedDeliveryDateRequestOriginAddress *EstimatedDeliveryDateRequestOriginAddress) SetCity(val string) {
	estimatedDeliveryDateRequestOriginAddress.City = &val
}

func (estimatedDeliveryDateRequestOriginAddress *EstimatedDeliveryDateRequestOriginAddress) SetPostalCode(val string) {
	estimatedDeliveryDateRequestOriginAddress.PostalCode = &val
}

func (estimatedDeliveryDateRequestOriginAddress *EstimatedDeliveryDateRequestOriginAddress) SetRawLocation(val string) {
	estimatedDeliveryDateRequestOriginAddress.RawLocation = &val
}
