// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// GetNotificationByTrackingIdResponse 
type GetNotificationByTrackingIdResponse struct {
    // Notification Object describes the notification information.
    Notification Notification `json:"notification,omitempty"`
}


