// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// GetCouriersResponseData
type GetCouriersResponseData struct {
	// Total Total count of courier objects
	Total *int `json:"total,omitempty"`
	// Couriers Array of  object.
	Couriers []Courier `json:"couriers,omitempty"`
}

func (getCouriersResponseData *GetCouriersResponseData) SetTotal(val int) {
	getCouriersResponseData.Total = &val
}

func (getCouriersResponseData *GetCouriersResponseData) SetCouriers(val []Courier) {
	getCouriersResponseData.Couriers = val
}
