// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// GetCourierConnectionsResponseDataPagination
type GetCourierConnectionsResponseDataPagination struct {
	// Total The total number of courier connections.
	Total *int `json:"total,omitempty"`
	// NextCursor A string representing the cursor value for the next page of results.
	NextCursor *string `json:"next_cursor,omitempty"`
	// HasNextPage To indicate if next page is available.
	HasNextPage *bool `json:"has_next_page,omitempty"`
}

func (getCourierConnectionsResponseDataPagination *GetCourierConnectionsResponseDataPagination) SetTotal(val int) {
	getCourierConnectionsResponseDataPagination.Total = &val
}

func (getCourierConnectionsResponseDataPagination *GetCourierConnectionsResponseDataPagination) SetNextCursor(val string) {
	getCourierConnectionsResponseDataPagination.NextCursor = &val
}

func (getCourierConnectionsResponseDataPagination *GetCourierConnectionsResponseDataPagination) SetHasNextPage(val bool) {
	getCourierConnectionsResponseDataPagination.HasNextPage = &val
}
