// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// GetCouriersQuery
type GetCouriersQuery struct {
	// Active get user activated couriers
	Active bool `url:"active,omitempty"`
	// Slug Unique courier code Use comma for multiple values. (Example: dhl,ups,usps)
	Slug string `url:"slug,omitempty"`
}
