// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// GetTrackingByIdResponse 
type GetTrackingByIdResponse struct {
    // Tracking Object describes the tracking information.<div style="display:none; height: 0"></div>
    Tracking Tracking `json:"tracking,omitempty"`
}


