// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// GetCourierConnectionsResponseData
type GetCourierConnectionsResponseData struct {
	// Pagination
	Pagination *GetCourierConnectionsResponseDataPagination `json:"pagination,omitempty"`
	// CourierConnections
	CourierConnections []CourierConnection `json:"courier_connections,omitempty"`
}

func (getCourierConnectionsResponseData *GetCourierConnectionsResponseData) SetPagination(val GetCourierConnectionsResponseDataPagination) {
	getCourierConnectionsResponseData.Pagination = &val
}

func (getCourierConnectionsResponseData *GetCourierConnectionsResponseData) SetCourierConnections(val []CourierConnection) {
	getCourierConnectionsResponseData.CourierConnections = val
}
