// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// GetNotificationBySlugTrackingNumberResponse 
type GetNotificationBySlugTrackingNumberResponse struct {
    // Notification Object describes the notification information.
    Notification Notification `json:"notification,omitempty"`
}


