// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// GetTrackingsQuery
type GetTrackingsQuery struct {
	// Cursor A string representing the cursor value for the current page of results.
	Cursor string `url:"cursor,omitempty"`
	// Limit Number of trackings each page contain. (Default: 100, Max: 200)
	Limit int `url:"limit,omitempty"`
	// Keyword Search the content of the tracking record fields: `tracking_number`, `title`, `order_id`, `customers[x].name`, `custom_fields`, `customers[x].email`, `customers[x].phone_number`
	Keyword string `url:"keyword,omitempty"`
	// TrackingNumbers Tracking number of shipments. Use comma to separate multiple values (Example: RA123456789US,LE123456789US). Supports up to 50 tracking numbers.
	TrackingNumbers string `url:"tracking_numbers,omitempty"`
	// Slug Unique courier code Use comma for multiple values. (Example: dhl,ups,usps)
	Slug string `url:"slug,omitempty"`
	// TransitTime Total delivery time in days.- When the shipment is delivered: Transit time = Delivered date - Picked up date- When the shipment is not delivered: Transit time = Current date - Picked up dateValue as `null` for the shipment without pickup date.
	TransitTime int `url:"transit_time,omitempty"`
	// Origin Origin country/region of trackings. Use ISO Alpha-3 (three letters). Use comma for multiple values. (Example: USA,HKG)
	Origin string `url:"origin,omitempty"`
	// Destination Destination country/region of trackings. Use ISO Alpha-3 (three letters). Use comma for multiple values. (Example: USA,HKG)
	Destination string `url:"destination,omitempty"`
	// Tag Current status of tracking. Values include `Pending`, `InfoReceived`, `InTransit`, `OutForDelivery`, `AttemptFail`, `Delivered`, `AvailableForPickup`, `Exception`, `Expired` (See tag definition)
	Tag string `url:"tag,omitempty"`
	// CreatedAtMin Start date and time of trackings created. AfterShip only stores data of 120 days. Please make sure the value of the parameter is properly escaped in
	CreatedAtMin string `url:"created_at_min,omitempty"`
	// CreatedAtMax End date and time of trackings created. Please make sure the value of the parameter is properly escaped in
	CreatedAtMax string `url:"created_at_max,omitempty"`
	// UpdatedAtMin Start date and time of trackings updated. Please make sure the value of the parameter is properly escaped in
	UpdatedAtMin string `url:"updated_at_min,omitempty"`
	// UpdatedAtMax End date and time of trackings updated. Please make sure the value of the parameter is properly escaped in
	UpdatedAtMax string `url:"updated_at_max,omitempty"`
	// Fields List of fields to include in the response. Use comma for multiple values. Available options: `title`, `order_id`, `tag`, `checkpoints`. Example: `title,order_id`
	Fields string `url:"fields,omitempty"`
	// ReturnToSender Select return to sender, the value should be `true` or `false`, with optional comma separated.
	ReturnToSender string `url:"return_to_sender,omitempty"`
	// CourierDestinationCountryRegion Destination country/region of trackings returned by courier. Use ISO Alpha-3 (three letters). Use comma for multiple values. (Example: USA,HKG)
	CourierDestinationCountryRegion string `url:"courier_destination_country_region,omitempty"`
	// ShipmentTags Tags you added to your shipments to help categorize and filter them easily. Use a comma to separate multiple values (Example: a,b)
	ShipmentTags string `url:"shipment_tags,omitempty"`
	// OrderId A globally-unique identifier for the order. Use comma for multiple values.(Example: 6845a095a27a4caeb27487806f058add,4845a095a27a4caeb27487806f058abc)
	OrderId string `url:"order_id,omitempty"`
}
