// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// GetCheckpointByTrackingIdResponse 
type GetCheckpointByTrackingIdResponse struct {
    // Id Tracking id
    Id string `json:"id,omitempty"`
    // TrackingNumber Tracking number.
    TrackingNumber string `json:"tracking_number,omitempty"`
    // Slug Unique code of courier.
    Slug string `json:"slug,omitempty"`
    // Tag Current status of tracking. (
    Tag TagV1 `json:"tag,omitempty"`
    // Subtag Current subtag of tracking. (
    Subtag string `json:"subtag,omitempty"`
    // SubtagMessage Normalized tracking message. (
    SubtagMessage string `json:"subtag_message,omitempty"`
    // Checkpoint Object describes checkpoint information.
    Checkpoint Checkpoint `json:"checkpoint,omitempty"`
}


