// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

import "net/http"

type GetCourierConnectionsResponse struct {
	ResponseHeader http.Header
	Data           GetCourierConnectionsResponseData
}
