// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// GetCourierConnectionsQuery
type GetCourierConnectionsQuery struct {
	// CourierSlug Unique courier code.(Example: dhl-api)
	CourierSlug string `url:"courier_slug,omitempty"`
}
