// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// GetCheckpointByTrackingIdQuery 
type GetCheckpointByTrackingIdQuery struct {
    // Fields List of fields to include in the response. Use comma for multiple values. Fields to include: `slug`, `created_at`, `checkpoint_time`, `city`, `coordinates`, `country_iso3`, `country_name`, `message`, `state`, `tag`, `zip`
    Fields string `url:"fields,omitempty"`
    // Lang Support Chinese to English translation for `china-ems` and `china-post` only
    Lang string `url:"lang,omitempty"`
}


