// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// MetaType error type, only exist if the response status is not 2xx
type MetaType string

const (
	MetaTypeBadRequest      MetaType = "BadRequest"
	MetaTypeUnauthorized    MetaType = "Unauthorized"
	MetaTypeForbidden       MetaType = "Forbidden"
	MetaTypeNotFound        MetaType = "NotFound"
	MetaTypeTooManyRequests MetaType = "TooManyRequests"
	MetaTypeInternalError   MetaType = "InternalError"
)
