// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// Notification Object describes the notification information.
type Notification struct {
    // Emails Email address(es) to receive email notifications.
    Emails []string `json:"emails,omitempty"`
    // Smses The phone number(s) to receive sms notifications. 
    Smses []string `json:"smses,omitempty"`
}


