// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// PartialUpdateTracking Partial tracking
type PartialUpdateTracking struct {
    // Id A unique identifier generated by AfterShip for the tracking.
    Id string `json:"id,omitempty"`
    // TrackingNumber Tracking number.
    TrackingNumber string `json:"tracking_number,omitempty"`
    // Slug Unique code of courier. Get the slugs from .
    Slug string `json:"slug,omitempty"`
    // TrackingAccountNumber Additional field required by some carriers to retrieve the tracking info. The shipper’s carrier account number. Refer to our article on  for more details.
    TrackingAccountNumber string `json:"tracking_account_number,omitempty"`
    // TrackingOriginCountry Additional field required by some carriers to retrieve the tracking info. The origin country/region of the shipment. Refer to our article on  for more details.
    TrackingOriginCountry string `json:"tracking_origin_country,omitempty"`
    // TrackingDestinationCountry Additional field required by some carriers to retrieve the tracking info. The destination country/region of the shipment. Refer to our article on  for more details.
    TrackingDestinationCountry string `json:"tracking_destination_country,omitempty"`
    // TrackingKey Additional field required by some carriers to retrieve the tracking info. A type of tracking credential required by some carriers. Refer to our article on  for more details.
    TrackingKey string `json:"tracking_key,omitempty"`
    // TrackingShipDate Additional field required by some carriers to retrieve the tracking info. The date the shipment was sent, using the format YYYYMMDD. Refer to our article on  for more details.
    TrackingShipDate string `json:"tracking_ship_date,omitempty"`
    // TrackingPostalCode Additional field required by some carriers to retrieve the tracking info. The postal code of the recipient’s address. Refer to our article on  for more details.
    TrackingPostalCode string `json:"tracking_postal_code,omitempty"`
    // TrackingState Additional field required by some carriers to retrieve the tracking info. The state/province of the recipient’s address. Refer to our article on  for more details.
    TrackingState string `json:"tracking_state,omitempty"`
    // Active Whether or not AfterShip will continue tracking the shipments. Value is `false` when tag (status) is `Delivered`, `Expired`, or further updates for 30 days since last update.
    Active bool `json:"active,omitempty"`
}


