// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

import "net/http"

type PredictBatchResponse struct {
	ResponseHeader http.Header
	Data           PredictBatchResponseData
}
