// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// PredictBatchResponse 
type PredictBatchResponse struct {
    // EstimatedDeliveryDates 
    EstimatedDeliveryDates []EstimatedDeliveryDateResponse `json:"estimated_delivery_dates"`
}


