// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// PredictBatchResponseData
type PredictBatchResponseData struct {
	// EstimatedDeliveryDates
	EstimatedDeliveryDates []EstimatedDeliveryDateResponse `json:"estimated_delivery_dates"`
}

func (predictBatchResponseData *PredictBatchResponseData) SetEstimatedDeliveryDates(val []EstimatedDeliveryDateResponse) {
	predictBatchResponseData.EstimatedDeliveryDates = val
}
