// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// PredictBatchRequest 
type PredictBatchRequest struct {
    // EstimatedDeliveryDates 
    EstimatedDeliveryDates []EstimatedDeliveryDateRequest `json:"estimated_delivery_dates"`
}


