// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

import "net/http"

type PredictResponse struct {
	ResponseHeader http.Header
	Data           EstimatedDeliveryDateResponse
}
