// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// PredictBatchResponse
type PredictBatchResponse struct {
	// EstimatedDeliveryDates
	EstimatedDeliveryDates []Estimateddeliverydate2 `json:"estimated_delivery_dates"`
}
