// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

import "net/http"

type PutCourierConnectionsByIdResponse struct {
	ResponseHeader http.Header
	Data           CourierConnection
}
