// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// RetrackTrackingByIdResponse 
type RetrackTrackingByIdResponse struct {
    // Tracking Partial tracking
    Tracking PartialUpdateTracking `json:"tracking,omitempty"`
}


