// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// RetrackTrackingBySlugTrackingNumberResponse 
type RetrackTrackingBySlugTrackingNumberResponse struct {
    // Tracking Partial tracking
    Tracking PartialUpdateTracking `json:"tracking,omitempty"`
}


