// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// SlugGroup Slug group is a group of slugs which belong to same courier. For example, when you inpit "fedex-group" as slug_group, AfterShip will detect the tracking with "fedex-uk", "fedex-fims", and other slugs which belong to "fedex". It cannot be used with slug at the same time. (
type SlugGroup string

const (
	SlugGroupAmazonGroup  SlugGroup = "amazon-group"
	SlugGroupFedexGroup   SlugGroup = "fedex-group"
	SlugGroupTollGroup    SlugGroup = "toll-group"
	SlugGroupTaqbinGroup  SlugGroup = "taqbin-group"
	SlugGroupTntGroup     SlugGroup = "tnt-group"
	SlugGroupCjGroup      SlugGroup = "cj-group"
	SlugGroupHermesGroup  SlugGroup = "hermes-group"
	SlugGroupDpdGroup     SlugGroup = "dpd-group"
	SlugGroupGlsGroup     SlugGroup = "gls-group"
	SlugGroupDhlGroup     SlugGroup = "dhl-group"
	SlugGroupFastwayGroup SlugGroup = "fastway-group"
	SlugGroupAsendiaGroup SlugGroup = "asendia-group"
)
