// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingLatestEstimatedDeliverySource The source of the EDD. Either the carrier, AfterShip AI, or based on your custom EDD settings.
type TrackingLatestEstimatedDeliverySource string

const (
	TrackingLatestEstimatedDeliverySourceCarrierEdd   TrackingLatestEstimatedDeliverySource = "Carrier EDD"
	TrackingLatestEstimatedDeliverySourceAfterShipEdd TrackingLatestEstimatedDeliverySource = "AfterShip EDD"
	TrackingLatestEstimatedDeliverySourceCustomEdd    TrackingLatestEstimatedDeliverySource = "Custom EDD"
	TrackingLatestEstimatedDeliverySourceOrderEdd     TrackingLatestEstimatedDeliverySource = "Order EDD"
)
