// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingProofOfDelivery
type TrackingProofOfDelivery struct {
	// Type The file type of the proof of delivery record. Currently, only images are supported.
	Type *string `json:"type,omitempty"`
	// Url The URL of the proof of delivery record.
	Url *string `json:"url,omitempty"`
}

func (trackingProofOfDelivery *TrackingProofOfDelivery) SetType(val string) {
	trackingProofOfDelivery.Type = &val
}

func (trackingProofOfDelivery *TrackingProofOfDelivery) SetUrl(val string) {
	trackingProofOfDelivery.Url = &val
}
