// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// Tracking Object describes the tracking information.<div style="display:none; height: 0"></div>
type Tracking struct {
	// Id A  system-generated tracking ID by default, which can be customized by the user when creating a tracking.
	Id string `json:"id,omitempty"`
	// LegacyId The length of the tracking ID has been increased from 24 characters to 32 characters. We will use the legacy_id field to store the original 24-character tracking ID to maintain compatibility with existing data. Therefore, all tracking endpoints will continue to work with the legacy_id field as before.
	LegacyId string `json:"legacy_id,omitempty"`
	// CreatedAt The date and time the shipment was imported or added to AfterShip. It uses the format `YYYY-MM-DDTHH:mm:ssZ` for the timezone GMT +0.
	CreatedAt string `json:"created_at,omitempty"`
	// UpdatedAt The date and time the shipment was updated. It uses the format `YYYY-MM-DDTHH:mm:ssZ` for the timezone GMT +0.
	UpdatedAt string `json:"updated_at,omitempty"`
	// TrackingNumber Tracking number.
	TrackingNumber string `json:"tracking_number,omitempty"`
	// Slug Unique courier code. When importing a shipment with no courier slug and the tracking number can’t be recognized, the courier will be marked as `unrecognized`. Get courier codes .
	Slug string `json:"slug,omitempty"`
	// Active Whether or not AfterShip will continue tracking the shipment. Value is false when no further updates for a few days since last update.
	Active bool `json:"active,omitempty"`
	// CustomFields Custom fields that accept an object with string field. In order to protect the privacy of your customers, do not include any  in custom fields.
	CustomFields map[string]string `json:"custom_fields,omitempty"`
	// TransitTime Total transit time in days.- For delivered shipments: Transit time (in days) = Delivered date - Pick-up date- For undelivered shipments: Transit time (in days) = Current date - Pick-up dateValue as `null` for the shipment without pick-up date.
	TransitTime int `json:"transit_time,omitempty"`
	// OriginCountryRegion The  for the origin country/region. E.g. USA for the United States.
	OriginCountryRegion string `json:"origin_country_region,omitempty"`
	// OriginState The state of the sender’s address.
	OriginState string `json:"origin_state,omitempty"`
	// OriginCity The city of the sender’s address.
	OriginCity string `json:"origin_city,omitempty"`
	// OriginPostalCode The postal code of the sender’s address.
	OriginPostalCode string `json:"origin_postal_code,omitempty"`
	// OriginRawLocation The sender address that the shipment is shipping from.
	OriginRawLocation string `json:"origin_raw_location,omitempty"`
	// DestinationCountryRegion The  for the destination country/region. E.g. USA for the United States.
	DestinationCountryRegion string `json:"destination_country_region,omitempty"`
	// DestinationState The state of the recipient’s address.
	DestinationState string `json:"destination_state,omitempty"`
	// DestinationCity The city of the recipient’s address.
	DestinationCity string `json:"destination_city,omitempty"`
	// DestinationPostalCode The postal code of the recipient’s address.
	DestinationPostalCode string `json:"destination_postal_code,omitempty"`
	// DestinationRawLocation The shipping address that the shipment is shipping to.
	DestinationRawLocation string `json:"destination_raw_location,omitempty"`
	// CourierDestinationCountryRegion Destination country/region of the tracking detected from the courier. ISO Alpha-3 (three letters). Value will be `null` if the courier doesn't provide the destination country.
	CourierDestinationCountryRegion string `json:"courier_destination_country_region,omitempty"`
	// CourierEstimatedDeliveryDate The field contains the estimated delivery date provided by the carrier.
	CourierEstimatedDeliveryDate *CourierEstimatedDeliveryDateTracking `json:"courier_estimated_delivery_date,omitempty"`
	// Note Text field for the note.
	Note string `json:"note,omitempty"`
	// OrderId A globally-unique identifier for the order.
	OrderId string `json:"order_id,omitempty"`
	// OrderIdPath The URL for the order in your system or store.
	OrderIdPath string `json:"order_id_path,omitempty"`
	// OrderDate The date and time the order was created in your system or store. It uses the format: `YYYY-MM-DDTHH:mm:ssZ` based on whichever timezone you provide.
	OrderDate string `json:"order_date,omitempty"`
	// ShipmentPackageCount Number of packages under the tracking.
	ShipmentPackageCount float64 `json:"shipment_package_count,omitempty"`
	// ShipmentPickupDate The date and time the shipment was picked up by the carrier. It uses the timezone where the pickup occured. The format may differ depending on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	ShipmentPickupDate string `json:"shipment_pickup_date,omitempty"`
	// ShipmentDeliveryDate The date and time the shipment was delivered. It uses the shipment recipient’s timezone. The format may differ depending on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	ShipmentDeliveryDate string `json:"shipment_delivery_date,omitempty"`
	// ShipmentType The carrier service type for the shipment.
	ShipmentType string `json:"shipment_type,omitempty"`
	// ShipmentWeight The shipment_weight field represents the total weight of the shipment. In scenarios where the carrier does not provide this information, you can provide the weight to AfterShip. We will prioritize the data provided by the carrier, if available. The shipment weight will be included in the Response and accessed through the GET API, Webhook, and CSV export. It will also be displayed on the AfterShip Tracking admin. Additionally, it plays a significant role in error-free shipment handling and carbon emission calculations, ensuring accurate and informed decision-making
	ShipmentWeight *ShipmentWeightTracking `json:"shipment_weight,omitempty"`
	// SignedBy Signed by information for delivered shipment.
	SignedBy string `json:"signed_by,omitempty"`
	// Source Source of how this tracking is added.
	Source string `json:"source,omitempty"`
	// Tag Current status of tracking. (
	Tag Tag `json:"tag,omitempty"`
	// Subtag Current subtag of tracking. (
	Subtag string `json:"subtag,omitempty"`
	// SubtagMessage Normalized tracking message. (
	SubtagMessage string `json:"subtag_message,omitempty"`
	// Title By default this field shows the `tracking_number`, but you can customize it as you wish with any info (e.g. the order number).
	Title string `json:"title,omitempty"`
	// TrackedCount Number of attempts AfterShip tracks at courier's system.
	TrackedCount float64 `json:"tracked_count,omitempty"`
	// LastMileTrackingSupported Indicates if the shipment is trackable till the final destination.Three possible values:- true- false- null
	LastMileTrackingSupported bool `json:"last_mile_tracking_supported,omitempty"`
	// Language The recipient’s language. If you set up AfterShip notifications in different languages, we use this to send the recipient tracking updates in their preferred language.
	Language string `json:"language,omitempty"`
	// UniqueToken Deprecated
	UniqueToken string `json:"unique_token,omitempty"`
	// Checkpoints Array of checkpoint object describes the checkpoint information.
	Checkpoints []Checkpoint `json:"checkpoints,omitempty"`
	// SubscribedSmses Phone number(s) subscribed to receive sms notifications.
	SubscribedSmses []string `json:"subscribed_smses,omitempty"`
	// SubscribedEmails Email address(es) subscribed to receive email notifications.
	SubscribedEmails []string `json:"subscribed_emails,omitempty"`
	// ReturnToSender Whether or not the shipment is returned to sender. Value is `true` when any of its checkpoints has subtag `Exception_010` (returning to sender) or `Exception_011` (returned to sender). Otherwise value is `false`.
	ReturnToSender bool `json:"return_to_sender,omitempty"`
	// OrderPromisedDeliveryDate The promised delivery date of the order. It uses the formats:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	OrderPromisedDeliveryDate string `json:"order_promised_delivery_date,omitempty"`
	// DeliveryType Shipment delivery type- pickup_at_store- pickup_at_courier- door_to_door
	DeliveryType string `json:"delivery_type,omitempty"`
	// PickupLocation Shipment pickup location for receiver
	PickupLocation string `json:"pickup_location,omitempty"`
	// PickupNote Shipment pickup note for receiver
	PickupNote string `json:"pickup_note,omitempty"`
	// CourierTrackingLink Official tracking URL of the courier (if any). The language parameter of this link relies on the destination country/region and the language associated with the shipment, if the data regarding the destination country/region and language of the shipment is not available, AfterShip will set the language parameter of the link to "US" by default.
	CourierTrackingLink string `json:"courier_tracking_link,omitempty"`
	// FirstAttemptedAt The date and time of the carrier’s first attempt to deliver the package to the recipient.  It uses the shipment recipient’s timezone. The format may differ depending on how the carrier provides it:- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	FirstAttemptedAt string `json:"first_attempted_at,omitempty"`
	// CourierRedirectLink Delivery instructions (delivery date or address) can be modified by visiting the link if supported by a carrier. The language parameter of this link relies on the destination country/region and the language associated with the shipment, if the data regarding the destination country/region and language of the shipment is not available, AfterShip will set the language parameter of the link to "US" by default.
	CourierRedirectLink string `json:"courier_redirect_link,omitempty"`
	// TrackingAccountNumber Additional field required by some carriers to retrieve the tracking info. The shipper’s carrier account number. Refer to our article on  for more details.
	TrackingAccountNumber string `json:"tracking_account_number,omitempty"`
	// TrackingKey Additional field required by some carriers to retrieve the tracking info. A type of tracking credential required by some carriers. Refer to our article on  for more details.
	TrackingKey string `json:"tracking_key,omitempty"`
	// TrackingShipDate The date and time when the shipment is shipped by the merchant and ready for pickup by the carrier. The field supports the following formats:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZThe field serves two key purposes:- Calculate processing time metrics in the Order-to-delivery Analytics dashboard. To ensure accurate analytics, it's recommended to include timezone information when configuring this value- Required by certain carriers to retrieve tracking information as an additional tracking field.
	TrackingShipDate string `json:"tracking_ship_date,omitempty"`
	// OnTimeStatus Whether the tracking is delivered on time or not.
	OnTimeStatus string `json:"on_time_status,omitempty"`
	// OnTimeDifference The difference days of the on time.
	OnTimeDifference float64 `json:"on_time_difference,omitempty"`
	// OrderTags The tags of the order.
	OrderTags []string `json:"order_tags,omitempty"`
	// AftershipEstimatedDeliveryDate The estimated delivery date of the shipment provided by AfterShip’s AI and shown to the recipients. It uses the format `YYYY-MM-DD` based on the shipment recipient’s timezone.
	AftershipEstimatedDeliveryDate *AftershipEstimatedDeliveryDateTracking `json:"aftership_estimated_delivery_date,omitempty"`
	// CustomEstimatedDeliveryDate Estimated delivery time of the shipment based on your . It uses the format `YYYY-MM-DD` based on the shipment recipient’s timezone.
	CustomEstimatedDeliveryDate *CustomEstimatedDeliveryDateTracking `json:"custom_estimated_delivery_date,omitempty"`
	// OrderNumber A unique, human-readable identifier for the order.
	OrderNumber string `json:"order_number,omitempty"`
	// FirstEstimatedDelivery The shipment’s original estimated delivery date. It could be provided by the carrier, AfterShip AI, or based on your custom settings. The format of carrier EDDs may differ depending on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ AfterShip AI and custom EDDs always use the format `YYYY-MM-DD`. All EDDs use the shipment recipient’s timezone.
	FirstEstimatedDelivery *FirstEstimatedDeliveryTracking `json:"first_estimated_delivery,omitempty"`
	// LatestEstimatedDelivery The most recently calculated estimated delivery date. It could be provided by the carrier, AfterShip AI, or based on your custom settings. The format of carrier EDDs may differ depending on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ AfterShip AI and custom EDDs always use the format `YYYY-MM-DD`. All EDDs use the shipment recipient’s timezone.
	LatestEstimatedDelivery *LatestEstimatedDeliveryTracking `json:"latest_estimated_delivery,omitempty"`
	// ShipmentTags Used to add tags to your shipments to help categorize and filter them easily.
	ShipmentTags []string `json:"shipment_tags,omitempty"`
	// CourierConnectionId If you have multiple accounts connected for a single carrier on AfterShip, we have introduced the courier_connection_id field to allow you to specify the carrier account associated with each shipment. By providing this information, you enable us to accurately track and monitor your shipments based on the correct carrier account.(</br>In the event that you do not specify the courier_connection_id, we will handle your shipment using the connection that was created earliest among your connected accounts.
	CourierConnectionId string `json:"courier_connection_id,omitempty"`
	// CarbonEmissions The model contains the total amount of carbon emissions generated by the shipment. - AfterShip will provide this data only when it is available, and its availability is contingent upon the location and weight information that AfterShip can obtain.- The values will be accessible solely for shipments that have been successfully delivered. However, in the event of a shipping update after the delivery status has been achieved, the value may change.- It’s a paid service and only for Tracking Enterprise users, please contact your customer success manager if you want to know more.
	CarbonEmissions *CarbonEmissionsTracking `json:"carbon_emissions,omitempty"`
	// LocationId The location_id refers to the place where you fulfilled the items.  - If you provide a location_id, the system will automatically use it as the tracking's origin address. However, passing both location_id and any origin address information simultaneously is not allowed.- Please make sure you add your locations .
	LocationId string `json:"location_id,omitempty"`
	// ShippingMethod The shipping_method string refers to the chosen method for delivering the package. Merchants typically offer various shipping methods to consumers during the checkout process, such as, Local Delivery, Free Express Worldwide Shipping, etc.
	ShippingMethod string `json:"shipping_method,omitempty"`
	// FailedDeliveryAttempts By dynamically tracking failed delivery attempts during shipment, this field allows you to pinpoint carriers accountable for the most failures. Analyzing the root cause of these failures enables you to improve carriers' delivery standard operating procedures (SOP), leading to an overall enhancement in delivery service quality.
	FailedDeliveryAttempts int `json:"failed_delivery_attempts,omitempty"`
	// SignatureRequirement The signature_requirement field serves the purpose of validating the service option type, specifically proof of delivery. By collecting the recipient's signature upon delivery, it ensures the package reaches the intended recipient and prevents disputes related to non-delivery or lost packages.</br>
	SignatureRequirement string `json:"signature_requirement,omitempty"`
	// DeliveryLocationType The delivery location type represents the secure area where the carrier leaves the package, such as a safe place, locker, mailbox, front porch, etc. This information helps ensure the shipment reaches the intended recipient efficiently, minimizing the risk of theft or damage.
	DeliveryLocationType string `json:"delivery_location_type,omitempty"`
	// AftershipTrackingUrl The tracking URL directs your customers to the shipment tracking page which can display either the default or a customized page based on segmentation rules.- The universal URL is used by default, but you can opt for a custom domain if you have one. Learn how to set up a custom domain .The field is not automatically enabled in API & Webhook. Please contact support if you’d like to enable it.
	AftershipTrackingUrl string `json:"aftership_tracking_url,omitempty"`
	// AftershipTrackingOrderUrl The order URL directs your customers to the order tracking page, which includes all shipments. It can display either the default or a customized page based on segmentation rules.- The universal URL is used by default, but you can opt for a custom domain if you have one. Learn how to set up a custom domain .The field is not automatically enabled in API & Webhook. Please contact support if you’d like to enable it.
	AftershipTrackingOrderUrl string `json:"aftership_tracking_order_url,omitempty"`
	// FirstMile The field contains information about the first leg of the shipping starting from the carrier picking up the shipment from the shipper to the point where they hand it over to the last-mile carrier. Once AfterShip detects the shipment is multi-leg, we will populate the first-mile information under this object.
	FirstMile *FirstMileTracking `json:"first_mile,omitempty"`
	// LastMile This field contains information about the last leg of the shipment, starting from the carrier who hands it over to the last-mile carrier, all the way to delivery. Once AfterShip detects that the shipment involves multiple legs and identifies the last-mile carrier, we will populate the last-mile carrier information in this object. Alternatively, the user can provide this information in this field to specify the last-mile carrier, which is helpful if AfterShip is unable to detect it automatically.
	LastMile *LastMileTracking `json:"last_mile,omitempty"`
	// Customers The field contains the customer information associated with the tracking. A maximum of three customer objects are allowed.
	Customers []CustomersTracking `json:"customers,omitempty"`
}

// CourierEstimatedDeliveryDateTracking
type CourierEstimatedDeliveryDateTracking struct {
	// EstimatedDeliveryDate The estimated arrival date of the shipment. It reflects the shipment recipient’s timezone and the format may vary based on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	EstimatedDeliveryDate string `json:"estimated_delivery_date,omitempty"`
	// EstimatedDeliveryDateMin The earliest estimated delivery date of the shipment. It reflects the shipment recipient’s timezone and the format may vary based on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	EstimatedDeliveryDateMin string `json:"estimated_delivery_date_min,omitempty"`
	// EstimatedDeliveryDateMax The Latest estimated delivery date of the shipment. It reflects the shipment recipient’s timezone and the format may vary based on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	EstimatedDeliveryDateMax string `json:"estimated_delivery_date_max,omitempty"`
}

// ShipmentWeightTracking
type ShipmentWeightTracking struct {
	// Unit The unit in which the value field is expressed.
	Unit string `json:"unit,omitempty"`
	// Value The total amount of shipment weight.
	Value float64 `json:"value,omitempty"`
}

// AftershipEstimatedDeliveryDateTracking
type AftershipEstimatedDeliveryDateTracking struct {
	// EstimatedDeliveryDate The estimated arrival date of the shipment.
	EstimatedDeliveryDate string `json:"estimated_delivery_date,omitempty"`
	// ConfidenceCode Indicates the confidence level and associated reason for an AI EDD prediction request. For a comprehensive list of confidence codes, refer to .
	ConfidenceCode float64 `json:"confidence_code,omitempty"`
	// EstimatedDeliveryDateMin Earliest estimated delivery date of the shipment.
	EstimatedDeliveryDateMin string `json:"estimated_delivery_date_min,omitempty"`
	// EstimatedDeliveryDateMax Latest estimated delivery date of the shipment.
	EstimatedDeliveryDateMax string `json:"estimated_delivery_date_max,omitempty"`
}

// CustomEstimatedDeliveryDateTracking
type CustomEstimatedDeliveryDateTracking struct {
	// Type The format of the EDD. Either a single date or a date range.
	Type string `json:"type,omitempty"`
	// Datetime The specific EDD date.
	Datetime string `json:"datetime,omitempty"`
	// DatetimeMin For a date range EDD format, the date for the lower end of the range.
	DatetimeMin string `json:"datetime_min,omitempty"`
	// DatetimeMax For a date range EDD format, the date for the upper end of the range.
	DatetimeMax string `json:"datetime_max,omitempty"`
}

// FirstEstimatedDeliveryTracking
type FirstEstimatedDeliveryTracking struct {
	// Type The format of the EDD. Either a single date or a date range.
	Type string `json:"type,omitempty"`
	// Source The source of the EDD. Either the carrier, AfterShip AI, or based on your custom EDD settings.
	Source string `json:"source,omitempty"`
	// Datetime The latest EDD time.
	Datetime string `json:"datetime,omitempty"`
	// DatetimeMin For a date range EDD format, the date and time for the lower end of the range.
	DatetimeMin string `json:"datetime_min,omitempty"`
	// DatetimeMax For a date range EDD format, the date and time for the upper end of the range.
	DatetimeMax string `json:"datetime_max,omitempty"`
}

// LatestEstimatedDeliveryTracking
type LatestEstimatedDeliveryTracking struct {
	// Type The format of the EDD. Either a single date or a date range.
	Type string `json:"type,omitempty"`
	// Source The source of the EDD. Either the carrier, AfterShip AI, or based on your custom EDD settings.
	Source string `json:"source,omitempty"`
	// Datetime The latest EDD time.
	Datetime string `json:"datetime,omitempty"`
	// DatetimeMin For a date range EDD format, the date and time for the lower end of the range.
	DatetimeMin string `json:"datetime_min,omitempty"`
	// DatetimeMax For a date range EDD format, the date and time for the upper end of the range.
	DatetimeMax string `json:"datetime_max,omitempty"`
	// ReviseReason Explains the reason for a change to the latest_estimated_delivery. This string will only have a value if:1. The source for the latest EDD is AfterShip EDD. 2. The reason for the change is known.For a comprehensive list of reasons, please refer to .
	ReviseReason string `json:"revise_reason,omitempty"`
}

// CarbonEmissionsTracking
type CarbonEmissionsTracking struct {
	// Unit The unit in which the value field is expressed. Allowed values: kg
	Unit string `json:"unit,omitempty"`
	// Value The total amount of carbon emissions
	Value float64 `json:"value,omitempty"`
}

// FirstMileTracking
type FirstMileTracking struct {
	// TrackingNumber The tracking number of the first-mile carrier.
	TrackingNumber string `json:"tracking_number,omitempty"`
	// Slug The unique code of the carrier responsible for the first-mile of the shipment. Find all the courier slugs .
	Slug string `json:"slug,omitempty"`
	// TransitTime The transit time for the first-mile of a shipment in days. This field is calculated based on whether the handed_over_to_last_mile_carrier or received_by_last_mile_carrier event is detected by AfterShip. The handover event date is used to calculate the first-mile transit time.- First mile transit time (in days) = Handover date - Pickup date
	TransitTime int `json:"transit_time,omitempty"`
	// CourierRedirectLink The field provides the link for modifying delivery instructions (such as delivery date and shipping address), if supported by the first-mile carrier. The language parameter of this link is determined by the destination country/region and the language associated with the shipment. If the destination country/region and language data is unavailable, AfterShip will default the language parameter to "US".
	CourierRedirectLink string `json:"courier_redirect_link,omitempty"`
	// CourierTrackingLink The field contains the official tracking URL of the first-mile carrier, if available. The language parameter of this link is determined by the destination country/region and the language associated with the shipment. If the destination country/region and language data is unavailable, AfterShip will default the language parameter to "US".
	CourierTrackingLink string `json:"courier_tracking_link,omitempty"`
}

// LastMileTracking
type LastMileTracking struct {
	// TrackingNumber The tracking number of the last-mile carrier.
	TrackingNumber string `json:"tracking_number,omitempty"`
	// Slug The unique code of the carrier responsible for the last-mile of the shipment.  Find all the courier slugs .
	Slug string `json:"slug,omitempty"`
	// TransitTime The transit time for the last-mile of a shipment in days. This field is calculated based on whether the handed_over_to_last_mile_carrier or the received_by_last_mile_carrier event is detected by AfterShip. The handover event date is used to calculate the last-mile transit time.- Last mile transit time (in days)= Delivered date - Handover date
	TransitTime int `json:"transit_time,omitempty"`
	// CourierTrackingLink The field contains the official tracking URL of the last-mile carrier, if available. The language parameter of this link is determined by the destination country/region and the language associated with the shipment. If the destination country/region and language data is unavailable, AfterShip will default the language parameter to "US".
	CourierTrackingLink string `json:"courier_tracking_link,omitempty"`
	// CourierRedirectLink The field provides the link for modifying delivery instructions (such as delivery date and shipping address), if supported by the last-mile carrier. The language parameter of this link is determined by the destination country/region and the language associated with the shipment. If the destination country/region and language data is unavailable, AfterShip will default the language parameter to "US".
	CourierRedirectLink string `json:"courier_redirect_link,omitempty"`
	// Source The field indicates the source of last-mile carrier.
	Source string `json:"source,omitempty"`
}

// CustomersTracking
type CustomersTracking struct {
	// Role The  role of the customer, indicating whether the customer is  an individual or a company.
	Role string `json:"role,omitempty"`
	// Name Customer name associated with the tracking.
	Name string `json:"name,omitempty"`
	// PhoneNumber The phone number(s) to receive SMS notifications. Phone numbers should begin with a `+` sign and include the area code.
	PhoneNumber string `json:"phone_number,omitempty"`
	// Email Email address(es) to receive email notifications.
	Email string `json:"email,omitempty"`
	// Language The preferred language of the customer. If you have set up AfterShip notifications in different languages, we use this to send the tracking updates to the customer in their preferred language.
	Language string `json:"language,omitempty"`
}
