// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingResponseForGetTrackingsData
type TrackingResponseForGetTrackingsData struct {
	// Pagination The Pagination holds the information for the pagination when the response contains multiple objects.
	Pagination *TrackingResponseForGetTrackingsDataPagination `json:"pagination,omitempty"`
	// Trackings Array of
	Trackings []Tracking `json:"trackings,omitempty"`
}

func (trackingResponseForGetTrackingsData *TrackingResponseForGetTrackingsData) SetPagination(val TrackingResponseForGetTrackingsDataPagination) {
	trackingResponseForGetTrackingsData.Pagination = &val
}

func (trackingResponseForGetTrackingsData *TrackingResponseForGetTrackingsData) SetTrackings(val []Tracking) {
	trackingResponseForGetTrackingsData.Trackings = val
}
