// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingForwardShipment The original outbound shipment linked to this return. Use this to trace a return back to its source delivery.This field is only present when `shipment_direction = "return"` and AfterShip has detected a linked forward shipment.
type TrackingForwardShipment struct {
	// Id AfterShip system-assigned unique identifier of the linked outbound shipment.
	Id *string `json:"id,omitempty"`
}

func (trackingForwardShipment *TrackingForwardShipment) SetId(val string) {
	trackingForwardShipment.Id = &val
}
