// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingOrderPromisedDeliveryDate The promised delivery date of the order in shipment recipient’s timezone.
type TrackingOrderPromisedDeliveryDate struct {
	// PromisedDeliveryDate The promised delivery date of the order. It uses the formats:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	PromisedDeliveryDate *string `json:"promised_delivery_date,omitempty"`
	// PromisedDeliveryDateMin Earliest promised delivery date of the order. It uses the formats:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	PromisedDeliveryDateMin *string `json:"promised_delivery_date_min,omitempty"`
	// PromisedDeliveryDateMax Latest promised delivery date of the order. It uses the formats:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	PromisedDeliveryDateMax *string `json:"promised_delivery_date_max,omitempty"`
}

func (trackingOrderPromisedDeliveryDate *TrackingOrderPromisedDeliveryDate) SetPromisedDeliveryDate(val string) {
	trackingOrderPromisedDeliveryDate.PromisedDeliveryDate = &val
}

func (trackingOrderPromisedDeliveryDate *TrackingOrderPromisedDeliveryDate) SetPromisedDeliveryDateMin(val string) {
	trackingOrderPromisedDeliveryDate.PromisedDeliveryDateMin = &val
}

func (trackingOrderPromisedDeliveryDate *TrackingOrderPromisedDeliveryDate) SetPromisedDeliveryDateMax(val string) {
	trackingOrderPromisedDeliveryDate.PromisedDeliveryDateMax = &val
}
