// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingShipmentWeight The shipment_weight field represents the total weight of the shipment. In scenarios where the carrier does not provide this information, you can provide the weight to AfterShip. We will prioritize the data provided by the carrier, if available. The shipment weight will be included in the Response and accessed through the GET API, Webhook, and CSV export. It will also be displayed on the AfterShip Tracking admin. Additionally, it plays a significant role in error-free shipment handling and carbon emission calculations, ensuring accurate and informed decision-making
type TrackingShipmentWeight struct {
	// Unit The unit in which the value field is expressed.
	Unit *string `json:"unit,omitempty"`
	// Value The total amount of shipment weight.
	Value *float64 `json:"value,omitempty"`
}

func (trackingShipmentWeight *TrackingShipmentWeight) SetUnit(val string) {
	trackingShipmentWeight.Unit = &val
}

func (trackingShipmentWeight *TrackingShipmentWeight) SetValue(val float64) {
	trackingShipmentWeight.Value = &val
}
