// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingFirstEstimatedDelivery The shipment’s original estimated delivery date. It could be provided by the carrier, AfterShip AI, or based on your custom settings. The format of carrier EDDs may differ depending on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ AfterShip AI and custom EDDs always use the format `YYYY-MM-DD`. All EDDs use the shipment recipient’s timezone.
type TrackingFirstEstimatedDelivery struct {
	// Type The format of the EDD. Either a single date or a date range.
	Type *TrackingFirstEstimatedDeliveryType `json:"type,omitempty"`
	// Source The source of the EDD. Either the carrier, AfterShip AI, or based on your custom EDD settings.
	Source *TrackingFirstEstimatedDeliverySource `json:"source,omitempty"`
	// Datetime The latest EDD time.
	Datetime *string `json:"datetime,omitempty"`
	// DatetimeMin For a date range EDD format, the date and time for the lower end of the range.
	DatetimeMin *string `json:"datetime_min,omitempty"`
	// DatetimeMax For a date range EDD format, the date and time for the upper end of the range.
	DatetimeMax *string `json:"datetime_max,omitempty"`
}

func (trackingFirstEstimatedDelivery *TrackingFirstEstimatedDelivery) SetType(val TrackingFirstEstimatedDeliveryType) {
	trackingFirstEstimatedDelivery.Type = &val
}

func (trackingFirstEstimatedDelivery *TrackingFirstEstimatedDelivery) SetSource(val TrackingFirstEstimatedDeliverySource) {
	trackingFirstEstimatedDelivery.Source = &val
}

func (trackingFirstEstimatedDelivery *TrackingFirstEstimatedDelivery) SetDatetime(val string) {
	trackingFirstEstimatedDelivery.Datetime = &val
}

func (trackingFirstEstimatedDelivery *TrackingFirstEstimatedDelivery) SetDatetimeMin(val string) {
	trackingFirstEstimatedDelivery.DatetimeMin = &val
}

func (trackingFirstEstimatedDelivery *TrackingFirstEstimatedDelivery) SetDatetimeMax(val string) {
	trackingFirstEstimatedDelivery.DatetimeMax = &val
}
