// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingLastMile This field contains information about the last leg of the shipment, starting from the carrier who hands it over to the last-mile carrier, all the way to delivery. Once AfterShip detects that the shipment involves multiple legs and identifies the last-mile carrier, we will populate the last-mile carrier information in this object. Alternatively, the user can provide this information in this field to specify the last-mile carrier, which is helpful if AfterShip is unable to detect it automatically.
type TrackingLastMile struct {
	// TrackingNumber The tracking number of the last-mile carrier.
	TrackingNumber *string `json:"tracking_number,omitempty"`
	// Slug The unique code of the carrier responsible for the last-mile of the shipment.  Find all the courier slugs .
	Slug *string `json:"slug,omitempty"`
	// TransitTime The transit time for the last-mile of a shipment in days. This field is calculated based on whether the handed_over_to_last_mile_carrier or the received_by_last_mile_carrier event is detected by AfterShip. The handover event date is used to calculate the last-mile transit time.- Last mile transit time (in days)= Delivered date - Handover date
	TransitTime *int `json:"transit_time,omitempty"`
	// CourierTrackingLink The field contains the official tracking URL of the last-mile carrier, if available. The language parameter of this link is determined by the destination country/region and the language associated with the shipment. If the destination country/region and language data is unavailable, AfterShip will default the language parameter to "US".
	CourierTrackingLink *string `json:"courier_tracking_link,omitempty"`
	// CourierRedirectLink The field provides the link for modifying delivery instructions (such as delivery date and shipping address), if supported by the last-mile carrier. The language parameter of this link is determined by the destination country/region and the language associated with the shipment. If the destination country/region and language data is unavailable, AfterShip will default the language parameter to "US".
	CourierRedirectLink *string `json:"courier_redirect_link,omitempty"`
	// Source The field indicates the source of last-mile carrier.
	Source *TrackingLastMileSource `json:"source,omitempty"`
}

func (trackingLastMile *TrackingLastMile) SetTrackingNumber(val string) {
	trackingLastMile.TrackingNumber = &val
}

func (trackingLastMile *TrackingLastMile) SetSlug(val string) {
	trackingLastMile.Slug = &val
}

func (trackingLastMile *TrackingLastMile) SetTransitTime(val int) {
	trackingLastMile.TransitTime = &val
}

func (trackingLastMile *TrackingLastMile) SetCourierTrackingLink(val string) {
	trackingLastMile.CourierTrackingLink = &val
}

func (trackingLastMile *TrackingLastMile) SetCourierRedirectLink(val string) {
	trackingLastMile.CourierRedirectLink = &val
}

func (trackingLastMile *TrackingLastMile) SetSource(val TrackingLastMileSource) {
	trackingLastMile.Source = &val
}
