// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingResponse Tracking response for returning single tracking
type TrackingResponse struct {
	// Meta Meta data
	Meta Meta `json:"meta"`
	// Data Object describes the tracking information.<div style="display:none; height: 0"></div>
	Data Tracking `json:"data"`
}
