// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingFirstMile The field contains information about the first leg of the shipping starting from the carrier picking up the shipment from the shipper to the point where they hand it over to the last-mile carrier. Once AfterShip detects the shipment is multi-leg, we will populate the first-mile information under this object.
type TrackingFirstMile struct {
	// TrackingNumber The tracking number of the first-mile carrier.
	TrackingNumber *string `json:"tracking_number,omitempty"`
	// Slug The unique code of the carrier responsible for the first-mile of the shipment. Find all the courier slugs .
	Slug *string `json:"slug,omitempty"`
	// TransitTime The transit time for the first-mile of a shipment in days. This field is calculated based on whether the handed_over_to_last_mile_carrier or received_by_last_mile_carrier event is detected by AfterShip. The handover event date is used to calculate the first-mile transit time.- First mile transit time (in days) = Handover date - Pickup date
	TransitTime *int `json:"transit_time,omitempty"`
	// CourierRedirectLink The field provides the link for modifying delivery instructions (such as delivery date and shipping address), if supported by the first-mile carrier. The language parameter of this link is determined by the destination country/region and the language associated with the shipment. If the destination country/region and language data is unavailable, AfterShip will default the language parameter to "US".
	CourierRedirectLink *string `json:"courier_redirect_link,omitempty"`
	// CourierTrackingLink The field contains the official tracking URL of the first-mile carrier, if available. The language parameter of this link is determined by the destination country/region and the language associated with the shipment. If the destination country/region and language data is unavailable, AfterShip will default the language parameter to "US".
	CourierTrackingLink *string `json:"courier_tracking_link,omitempty"`
}

func (trackingFirstMile *TrackingFirstMile) SetTrackingNumber(val string) {
	trackingFirstMile.TrackingNumber = &val
}

func (trackingFirstMile *TrackingFirstMile) SetSlug(val string) {
	trackingFirstMile.Slug = &val
}

func (trackingFirstMile *TrackingFirstMile) SetTransitTime(val int) {
	trackingFirstMile.TransitTime = &val
}

func (trackingFirstMile *TrackingFirstMile) SetCourierRedirectLink(val string) {
	trackingFirstMile.CourierRedirectLink = &val
}

func (trackingFirstMile *TrackingFirstMile) SetCourierTrackingLink(val string) {
	trackingFirstMile.CourierTrackingLink = &val
}
