// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingShipmentDimensions Physical dimensions of the package (length, width and height).
type TrackingShipmentDimensions struct {
	// Unit The unit in which the dimension values are expressed. Allowed values: cm, in
	Unit *string `json:"unit,omitempty"`
	// Length The length of the shipment package.
	Length *float64 `json:"length,omitempty"`
	// Width The width of the shipment package.
	Width *float64 `json:"width,omitempty"`
	// Height The height of the shipment package.
	Height *float64 `json:"height,omitempty"`
}

func (trackingShipmentDimensions *TrackingShipmentDimensions) SetUnit(val string) {
	trackingShipmentDimensions.Unit = &val
}

func (trackingShipmentDimensions *TrackingShipmentDimensions) SetLength(val float64) {
	trackingShipmentDimensions.Length = &val
}

func (trackingShipmentDimensions *TrackingShipmentDimensions) SetWidth(val float64) {
	trackingShipmentDimensions.Width = &val
}

func (trackingShipmentDimensions *TrackingShipmentDimensions) SetHeight(val float64) {
	trackingShipmentDimensions.Height = &val
}
