// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingMultiPieceInfoPieces
type TrackingMultiPieceInfoPieces struct {
	// TrackingId AfterShip system-assigned unique identifier for the piece.
	TrackingId *string `json:"tracking_id,omitempty"`
	// TrackingNumber Carrier-assigned tracking number for the piece.
	TrackingNumber *string `json:"tracking_number,omitempty"`
	// Type Type of the piece within the MPS: `master` or `child`.
	Type *TrackingMultiPieceInfoPiecesType `json:"type,omitempty"`
	// Trackable Indicates whether the tracking number can be used to retrieve tracking updates on the carrier's side. If not, it means the carrier can only return a child tracking number, but cannot independently provide tracking updates for the sub-shipment. In this case, it is not recommended for you to import this tracking number into AfterShip for tracking.
	Trackable *bool `json:"trackable,omitempty"`
}

func (trackingMultiPieceInfoPieces *TrackingMultiPieceInfoPieces) SetTrackingId(val string) {
	trackingMultiPieceInfoPieces.TrackingId = &val
}

func (trackingMultiPieceInfoPieces *TrackingMultiPieceInfoPieces) SetTrackingNumber(val string) {
	trackingMultiPieceInfoPieces.TrackingNumber = &val
}

func (trackingMultiPieceInfoPieces *TrackingMultiPieceInfoPieces) SetType(val TrackingMultiPieceInfoPiecesType) {
	trackingMultiPieceInfoPieces.Type = &val
}

func (trackingMultiPieceInfoPieces *TrackingMultiPieceInfoPieces) SetTrackable(val bool) {
	trackingMultiPieceInfoPieces.Trackable = &val
}
