// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingCourierEstimatedDeliveryDate The field contains the estimated delivery date provided by the carrier.
type TrackingCourierEstimatedDeliveryDate struct {
	// EstimatedDeliveryDate The estimated arrival date of the shipment. It reflects the shipment recipient’s timezone and the format may vary based on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	EstimatedDeliveryDate *string `json:"estimated_delivery_date,omitempty"`
	// EstimatedDeliveryDateMin The earliest estimated delivery date of the shipment. It reflects the shipment recipient’s timezone and the format may vary based on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	EstimatedDeliveryDateMin *string `json:"estimated_delivery_date_min,omitempty"`
	// EstimatedDeliveryDateMax The Latest estimated delivery date of the shipment. It reflects the shipment recipient’s timezone and the format may vary based on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	EstimatedDeliveryDateMax *string `json:"estimated_delivery_date_max,omitempty"`
}

func (trackingCourierEstimatedDeliveryDate *TrackingCourierEstimatedDeliveryDate) SetEstimatedDeliveryDate(val string) {
	trackingCourierEstimatedDeliveryDate.EstimatedDeliveryDate = &val
}

func (trackingCourierEstimatedDeliveryDate *TrackingCourierEstimatedDeliveryDate) SetEstimatedDeliveryDateMin(val string) {
	trackingCourierEstimatedDeliveryDate.EstimatedDeliveryDateMin = &val
}

func (trackingCourierEstimatedDeliveryDate *TrackingCourierEstimatedDeliveryDate) SetEstimatedDeliveryDateMax(val string) {
	trackingCourierEstimatedDeliveryDate.EstimatedDeliveryDateMax = &val
}
