// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingReturnShipment The associated return shipment linked to the current outbound shipment.This field is only present when `shipment_direction = "forward"` and AfterShip has detected a linked return shipment.
type TrackingReturnShipment struct {
	// Id AfterShip system-assigned unique identifier of the linked return shipment.This field is only returned when both of the following conditions are met:1. AfterShip has detected a linked return shipment.2. The Auto-import for return shipments feature is enabled in your AfterShip account.When auto-import is disabled, `id` will not be returned, but `tracking_number` and `slug` may still be present.To enable this feature, go to .
	Id *string `json:"id,omitempty"`
	// TrackingNumber Carrier-assigned tracking number of the linked return shipment. Can be used together with `return_shipment.slug` to create a new tracking subscription and retrieve the return shipment's checkpoints.
	TrackingNumber *string `json:"tracking_number,omitempty"`
	// Slug Carrier slug (identifier) of the linked return shipment. Can be used together with `return_shipment.tracking_number` to subscribe to tracking updates for the return shipment.
	Slug *string `json:"slug,omitempty"`
}

func (trackingReturnShipment *TrackingReturnShipment) SetId(val string) {
	trackingReturnShipment.Id = &val
}

func (trackingReturnShipment *TrackingReturnShipment) SetTrackingNumber(val string) {
	trackingReturnShipment.TrackingNumber = &val
}

func (trackingReturnShipment *TrackingReturnShipment) SetSlug(val string) {
	trackingReturnShipment.Slug = &val
}
