// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingShipmentDirection Indicates the business direction of the shipment in the e-commerce fulfillment lifecycle.Possible values:- `forward`: A forward (outbound-to-customer) shipment created for order fulfillment.- `return`: A return (customer-to-merchant) shipment created for after-sales return or exchange.This field is populated in either of the following cases:1. You explicitly provided it when creating the tracking.2. AfterShip automatically detected a linked forward or return shipment.It also determines which related shipment object (`forward_shipment` or `return_shipment`) may appear in the response.
type TrackingShipmentDirection string

const (
	TrackingShipmentDirectionForward TrackingShipmentDirection = "forward"
	TrackingShipmentDirectionReturn  TrackingShipmentDirection = "return"
	TrackingShipmentDirectionNull    TrackingShipmentDirection = "null"
)
