// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingResponseV1 Tracking response for returning single tracking
type TrackingResponseV1 struct {
	// Meta Meta data
	Meta MetaV1 `json:"meta"`
	// Data Object describes the tracking information.<div style="display:none; height: 0"></div>
	Data Tracking `json:"data"`
}
