// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingSignatureRequirement The signature_requirement field serves the purpose of validating the service option type, specifically proof of delivery. By collecting the recipient's signature upon delivery, it ensures the package reaches the intended recipient and prevents disputes related to non-delivery or lost packages.</br>
type TrackingSignatureRequirement string

const (
	TrackingSignatureRequirementSignatureRequired         TrackingSignatureRequirement = "signature_required"
	TrackingSignatureRequirementAdultSignatureRequired    TrackingSignatureRequirement = "adult_signature_required"
	TrackingSignatureRequirementIndirectSignatureRequired TrackingSignatureRequirement = "indirect_signature_required"
	TrackingSignatureRequirementNoSignatureRequired       TrackingSignatureRequirement = "no_signature_required"
	TrackingSignatureRequirementNull                      TrackingSignatureRequirement = "null"
)
