// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingFirstEstimatedDeliveryType The format of the EDD. Either a single date or a date range.
type TrackingFirstEstimatedDeliveryType string

const (
	TrackingFirstEstimatedDeliveryTypeRange    TrackingFirstEstimatedDeliveryType = "range"
	TrackingFirstEstimatedDeliveryTypeSpecific TrackingFirstEstimatedDeliveryType = "specific"
)
