// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingMultiPieceInfoPiecesType Type of the piece within the MPS: `master` or `child`.
type TrackingMultiPieceInfoPiecesType string

const (
	TrackingMultiPieceInfoPiecesTypeMaster TrackingMultiPieceInfoPiecesType = "master"
	TrackingMultiPieceInfoPiecesTypeChild  TrackingMultiPieceInfoPiecesType = "child"
)
