// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingResponseV1 Tracking response for returning single tracking
type TrackingResponseV1 struct {
    // Meta Meta data
    Meta MetaV1 `json:"meta"`
    // Data 
    Data *DataTrackingResponseV1 `json:"data"`
}

// DataTrackingResponseV1 
type DataTrackingResponseV1 struct {
    // Tracking Object describes the tracking information.<div style="display:none; height: 0"></div>
    Tracking Tracking `json:"tracking,omitempty"`
}


