// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingResponseGetMultipleV1 Tracking response for getting tracking
type TrackingResponseGetMultipleV1 struct {
    // Meta Meta data
    Meta MetaV1 `json:"meta"`
    // Data 
    Data *DataTrackingResponseGetMultipleV1 `json:"data,omitempty"`
}

// DataTrackingResponseGetMultipleV1 
type DataTrackingResponseGetMultipleV1 struct {
    // Pagination The Pagination holds the information for the pagination when the response contains multiple objects.
    Pagination *PaginationDataTrackingResponseGetMultipleV1 `json:"pagination,omitempty"`
    // Trackings Array of 
    Trackings []Tracking `json:"trackings,omitempty"`
}

// PaginationDataTrackingResponseGetMultipleV1 
type PaginationDataTrackingResponseGetMultipleV1 struct {
    // Total The total number of trackings.
    Total int `json:"total,omitempty"`
    // NextCursor A string representing the cursor value for the next page of results.
    NextCursor string `json:"next_cursor,omitempty"`
    // HasNextPage To indicate if next page is available.
    HasNextPage bool `json:"has_next_page,omitempty"`
}


