// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingAftershipEstimatedDeliveryDate The estimated delivery date of the shipment provided by AfterShip’s AI and shown to the recipients. It uses the format `YYYY-MM-DD` based on the shipment recipient’s timezone.
type TrackingAftershipEstimatedDeliveryDate struct {
	// EstimatedDeliveryDate The estimated arrival date of the shipment.
	EstimatedDeliveryDate *string `json:"estimated_delivery_date,omitempty"`
	// ConfidenceCode Indicates the confidence level and associated reason for an AI EDD prediction request. For a comprehensive list of confidence codes, refer to .
	ConfidenceCode *float64 `json:"confidence_code,omitempty"`
	// EstimatedDeliveryDateMin Earliest estimated delivery date of the shipment.
	EstimatedDeliveryDateMin *string `json:"estimated_delivery_date_min,omitempty"`
	// EstimatedDeliveryDateMax Latest estimated delivery date of the shipment.
	EstimatedDeliveryDateMax *string `json:"estimated_delivery_date_max,omitempty"`
}

func (trackingAftershipEstimatedDeliveryDate *TrackingAftershipEstimatedDeliveryDate) SetEstimatedDeliveryDate(val string) {
	trackingAftershipEstimatedDeliveryDate.EstimatedDeliveryDate = &val
}

func (trackingAftershipEstimatedDeliveryDate *TrackingAftershipEstimatedDeliveryDate) SetConfidenceCode(val float64) {
	trackingAftershipEstimatedDeliveryDate.ConfidenceCode = &val
}

func (trackingAftershipEstimatedDeliveryDate *TrackingAftershipEstimatedDeliveryDate) SetEstimatedDeliveryDateMin(val string) {
	trackingAftershipEstimatedDeliveryDate.EstimatedDeliveryDateMin = &val
}

func (trackingAftershipEstimatedDeliveryDate *TrackingAftershipEstimatedDeliveryDate) SetEstimatedDeliveryDateMax(val string) {
	trackingAftershipEstimatedDeliveryDate.EstimatedDeliveryDateMax = &val
}
