// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingResponseForGetTrackings Tracking response for getting tracking
type TrackingResponseForGetTrackings struct {
	// Meta Meta data
	Meta Meta `json:"meta"`
	// Data
	Data *TrackingResponseForGetTrackingsData `json:"data,omitempty"`
}

func (trackingResponseForGetTrackings *TrackingResponseForGetTrackings) SetMeta(val Meta) {
	trackingResponseForGetTrackings.Meta = val
}

func (trackingResponseForGetTrackings *TrackingResponseForGetTrackings) SetData(val TrackingResponseForGetTrackingsData) {
	trackingResponseForGetTrackings.Data = &val
}
