// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingResponseForGetTrackingsDataPagination The Pagination holds the information for the pagination when the response contains multiple objects.
type TrackingResponseForGetTrackingsDataPagination struct {
	// Total The total number of trackings.
	Total *int `json:"total,omitempty"`
	// NextCursor A string representing the cursor value for the next page of results.
	NextCursor *string `json:"next_cursor,omitempty"`
	// HasNextPage To indicate if next page is available.
	HasNextPage *bool `json:"has_next_page,omitempty"`
}

func (trackingResponseForGetTrackingsDataPagination *TrackingResponseForGetTrackingsDataPagination) SetTotal(val int) {
	trackingResponseForGetTrackingsDataPagination.Total = &val
}

func (trackingResponseForGetTrackingsDataPagination *TrackingResponseForGetTrackingsDataPagination) SetNextCursor(val string) {
	trackingResponseForGetTrackingsDataPagination.NextCursor = &val
}

func (trackingResponseForGetTrackingsDataPagination *TrackingResponseForGetTrackingsDataPagination) SetHasNextPage(val bool) {
	trackingResponseForGetTrackingsDataPagination.HasNextPage = &val
}
