// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingCustomEstimatedDeliveryDateType The format of the EDD. Either a single date or a date range.
type TrackingCustomEstimatedDeliveryDateType string

const (
	TrackingCustomEstimatedDeliveryDateTypeRange    TrackingCustomEstimatedDeliveryDateType = "range"
	TrackingCustomEstimatedDeliveryDateTypeSpecific TrackingCustomEstimatedDeliveryDateType = "specific"
)
