// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingLastMileSource The field indicates the source of last-mile carrier.
type TrackingLastMileSource string

const (
	TrackingLastMileSourceSystem TrackingLastMileSource = "system"
	TrackingLastMileSourceUser   TrackingLastMileSource = "user"
)
