// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// Tracking Object describes the tracking information.<div style="visibility:hidden; height: 0"></div>
type Tracking struct {
	// Id A  system-generated tracking ID by default, which can be customized by the user when creating a tracking.
	Id *string `json:"id,omitempty"`
	// LegacyId The length of the tracking ID has been increased from 24 characters to 32 characters. We will use the legacy_id field to store the original 24-character tracking ID to maintain compatibility with existing data. Therefore, all tracking endpoints will continue to work with the legacy_id field as before.
	LegacyId *string `json:"legacy_id,omitempty"`
	// CreatedAt The date and time the shipment was imported or added to AfterShip. It uses the format `YYYY-MM-DDTHH:mm:ssZ` for the timezone GMT +0.
	CreatedAt *string `json:"created_at,omitempty"`
	// UpdatedAt The date and time the shipment was updated. It uses the format `YYYY-MM-DDTHH:mm:ssZ` for the timezone GMT +0.
	UpdatedAt *string `json:"updated_at,omitempty"`
	// TrackingNumber Tracking number.
	TrackingNumber *string `json:"tracking_number,omitempty"`
	// Slug Unique courier code. When importing a shipment with no courier slug and the tracking number can’t be recognized, the courier will be marked as `unrecognized`. Get courier codes .
	Slug *string `json:"slug,omitempty"`
	// Active Whether or not AfterShip will continue tracking the shipment. Value is false when no further updates for a few days since last update.
	Active *bool `json:"active,omitempty"`
	// CustomFields Custom fields that accept an object with string field. In order to protect the privacy of your customers, do not include any  in custom fields.
	CustomFields map[string]string `json:"custom_fields,omitempty"`
	// TransitTime Total transit time in days.- For delivered shipments: Transit time (in days) = Delivered date - Pick-up date- For undelivered shipments: Transit time (in days) = Current date - Pick-up dateValue as `null` for the shipment without pick-up date.
	TransitTime *int `json:"transit_time,omitempty"`
	// OriginCountryRegion The  for the origin country/region. E.g. USA for the United States.
	OriginCountryRegion *string `json:"origin_country_region,omitempty"`
	// OriginState The state of the sender’s address.
	OriginState *string `json:"origin_state,omitempty"`
	// OriginCity The city of the sender’s address.
	OriginCity *string `json:"origin_city,omitempty"`
	// OriginPostalCode The postal code of the sender’s address.
	OriginPostalCode *string `json:"origin_postal_code,omitempty"`
	// OriginRawLocation The sender address that the shipment is shipping from.
	OriginRawLocation *string `json:"origin_raw_location,omitempty"`
	// DestinationCountryRegion The  for the destination country/region. E.g. USA for the United States.
	DestinationCountryRegion *string `json:"destination_country_region,omitempty"`
	// DestinationState The state of the recipient’s address.
	DestinationState *string `json:"destination_state,omitempty"`
	// DestinationCity The city of the recipient’s address.
	DestinationCity *string `json:"destination_city,omitempty"`
	// DestinationPostalCode The postal code of the recipient’s address.
	DestinationPostalCode *string `json:"destination_postal_code,omitempty"`
	// DestinationRawLocation The shipping address that the shipment is shipping to.
	DestinationRawLocation *string `json:"destination_raw_location,omitempty"`
	// CourierDestinationCountryRegion Destination country/region of the tracking detected from the courier. ISO Alpha-3 (three letters). Value will be `null` if the courier doesn't provide the destination country.
	CourierDestinationCountryRegion *string `json:"courier_destination_country_region,omitempty"`
	// CourierEstimatedDeliveryDate The field contains the estimated delivery date provided by the carrier.
	CourierEstimatedDeliveryDate *TrackingCourierEstimatedDeliveryDate `json:"courier_estimated_delivery_date,omitempty"`
	// Note Text field for the note.
	Note *string `json:"note,omitempty"`
	// OrderId A globally-unique identifier for the order.
	OrderId *string `json:"order_id,omitempty"`
	// OrderIdPath The URL for the order in your system or store.
	OrderIdPath *string `json:"order_id_path,omitempty"`
	// OrderDate The date and time the order was created in your system or store. It uses the format: `YYYY-MM-DDTHH:mm:ssZ` based on whichever timezone you provide.
	OrderDate *string `json:"order_date,omitempty"`
	// ShipmentPackageCount Number of packages under the tracking.
	ShipmentPackageCount *float64 `json:"shipment_package_count,omitempty"`
	// ShipmentPickupDate The date and time the shipment was picked up by the carrier. It uses the timezone where the pickup occured. The format may differ depending on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	ShipmentPickupDate *string `json:"shipment_pickup_date,omitempty"`
	// ShipmentDeliveryDate The date and time the shipment was delivered. It uses the shipment recipient’s timezone. The format may differ depending on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	ShipmentDeliveryDate *string `json:"shipment_delivery_date,omitempty"`
	// ShipmentType The carrier service type for the shipment.
	ShipmentType *string `json:"shipment_type,omitempty"`
	// ShipmentWeight The shipment_weight field represents the total weight of the shipment. In scenarios where the carrier does not provide this information, you can provide the weight to AfterShip. We will prioritize the data provided by the carrier, if available. The shipment weight will be included in the Response and accessed through the GET API, Webhook, and CSV export. It will also be displayed on the AfterShip Tracking admin. Additionally, it plays a significant role in error-free shipment handling and carbon emission calculations, ensuring accurate and informed decision-making
	ShipmentWeight *TrackingShipmentWeight `json:"shipment_weight,omitempty"`
	// ShipmentDimensions Physical dimensions of the package (length, width and height).
	ShipmentDimensions *TrackingShipmentDimensions `json:"shipment_dimensions,omitempty"`
	// SignedBy Signed by information for delivered shipment.
	SignedBy *string `json:"signed_by,omitempty"`
	// Source Source of how this tracking is added.
	Source *string `json:"source,omitempty"`
	// Tag Current status of tracking. (
	Tag *Tag `json:"tag,omitempty"`
	// Subtag Current subtag of tracking. (
	Subtag *string `json:"subtag,omitempty"`
	// SubtagMessage Normalized tracking message. (
	SubtagMessage *string `json:"subtag_message,omitempty"`
	// Title By default this field shows the `tracking_number`, but you can customize it as you wish with any info (e.g. the order number).
	Title *string `json:"title,omitempty"`
	// TrackedCount Number of attempts AfterShip tracks at courier's system.
	TrackedCount *float64 `json:"tracked_count,omitempty"`
	// Language The recipient’s language. If you set up AfterShip notifications in different languages, we use this to send the recipient tracking updates in their preferred language.
	Language *string `json:"language,omitempty"`
	// UniqueToken Deprecated
	UniqueToken *string `json:"unique_token,omitempty"`
	// Checkpoints Array of checkpoint object describes the checkpoint information.
	Checkpoints []Checkpoint `json:"checkpoints,omitempty"`
	// SubscribedSmses Phone number(s) subscribed to receive sms notifications.
	SubscribedSmses []string `json:"subscribed_smses,omitempty"`
	// SubscribedEmails Email address(es) subscribed to receive email notifications.
	SubscribedEmails []string `json:"subscribed_emails,omitempty"`
	// ReturnToSender Whether or not the shipment is returned to sender. Value is `true` when any of its checkpoints has subtag `Exception_010` (returning to sender) or `Exception_011` (returned to sender). Otherwise value is `false`.
	ReturnToSender *bool `json:"return_to_sender,omitempty"`
	// OrderPromisedDeliveryDate The promised delivery date of the order in shipment recipient’s timezone.
	OrderPromisedDeliveryDate *TrackingOrderPromisedDeliveryDate `json:"order_promised_delivery_date,omitempty"`
	// DeliveryType Shipment delivery type- pickup_at_store- pickup_at_courier- door_to_door
	DeliveryType *string `json:"delivery_type,omitempty"`
	// PickupLocation Shipment pickup location for receiver
	PickupLocation *string `json:"pickup_location,omitempty"`
	// PickupNote Shipment pickup note for receiver
	PickupNote *string `json:"pickup_note,omitempty"`
	// CourierTrackingLink Official tracking URL of the courier (if any). The language parameter of this link relies on the destination country/region and the language associated with the shipment, if the data regarding the destination country/region and language of the shipment is not available, AfterShip will set the language parameter of the link to "US" by default.
	CourierTrackingLink *string `json:"courier_tracking_link,omitempty"`
	// FirstAttemptedAt The date and time of the carrier’s first attempt to deliver the package to the recipient.  It uses the shipment recipient’s timezone. The format may differ depending on how the carrier provides it:- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	FirstAttemptedAt *string `json:"first_attempted_at,omitempty"`
	// CourierRedirectLink Delivery instructions (delivery date or address) can be modified by visiting the link if supported by a carrier. The language parameter of this link relies on the destination country/region and the language associated with the shipment, if the data regarding the destination country/region and language of the shipment is not available, AfterShip will set the language parameter of the link to "US" by default.
	CourierRedirectLink *string `json:"courier_redirect_link,omitempty"`
	// TrackingAccountNumber Additional field required by some carriers to retrieve the tracking info. The shipper’s carrier account number. Refer to our article on  for more details.
	TrackingAccountNumber *string `json:"tracking_account_number,omitempty"`
	// TrackingKey Additional field required by some carriers to retrieve the tracking info. A type of tracking credential required by some carriers. Refer to our article on  for more details.
	TrackingKey *string `json:"tracking_key,omitempty"`
	// TrackingShipDate The date and time when the shipment is shipped by the merchant and ready for pickup by the carrier. The field supports the following formats:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZThe field serves two key purposes:- Calculate processing time metrics in the Order-to-delivery Analytics dashboard. To ensure accurate analytics, it's recommended to include timezone information when configuring this value- Required by certain carriers to retrieve tracking information as an additional tracking field.
	TrackingShipDate *string `json:"tracking_ship_date,omitempty"`
	// OnTimeStatus Whether the tracking is delivered on time or not.
	OnTimeStatus *string `json:"on_time_status,omitempty"`
	// OnTimeDifference The difference days of the on time.
	OnTimeDifference *float64 `json:"on_time_difference,omitempty"`
	// OrderTags The tags of the order.
	OrderTags []string `json:"order_tags,omitempty"`
	// AftershipEstimatedDeliveryDate The estimated delivery date of the shipment provided by AfterShip’s AI and shown to the recipients. It uses the format `YYYY-MM-DD` based on the shipment recipient’s timezone.
	AftershipEstimatedDeliveryDate *TrackingAftershipEstimatedDeliveryDate `json:"aftership_estimated_delivery_date,omitempty"`
	// CustomEstimatedDeliveryDate Estimated delivery time of the shipment based on your . It uses the format `YYYY-MM-DD` based on the shipment recipient’s timezone.
	CustomEstimatedDeliveryDate *TrackingCustomEstimatedDeliveryDate `json:"custom_estimated_delivery_date,omitempty"`
	// OrderNumber A unique, human-readable identifier for the order.
	OrderNumber *string `json:"order_number,omitempty"`
	// FirstEstimatedDelivery The shipment’s original estimated delivery date. It could be provided by the carrier, AfterShip AI, or based on your custom settings. The format of carrier EDDs may differ depending on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ AfterShip AI and custom EDDs always use the format `YYYY-MM-DD`. All EDDs use the shipment recipient’s timezone.
	FirstEstimatedDelivery *TrackingFirstEstimatedDelivery `json:"first_estimated_delivery,omitempty"`
	// LatestEstimatedDelivery The most recently calculated estimated delivery date. It could be provided by the carrier, AfterShip AI, or based on your custom settings. The format of carrier EDDs may differ depending on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ AfterShip AI and custom EDDs always use the format `YYYY-MM-DD`. All EDDs use the shipment recipient’s timezone.
	LatestEstimatedDelivery *TrackingLatestEstimatedDelivery `json:"latest_estimated_delivery,omitempty"`
	// ShipmentTags Used to add tags to your shipments to help categorize and filter them easily.
	ShipmentTags []string `json:"shipment_tags,omitempty"`
	// CourierConnectionId If you have multiple accounts connected for a single carrier on AfterShip, we have introduced the courier_connection_id field to allow you to specify the carrier account associated with each shipment. By providing this information, you enable us to accurately track and monitor your shipments based on the correct carrier account.(</br>In the event that you do not specify the courier_connection_id, we will handle your shipment using the connection that was created earliest among your connected accounts.
	CourierConnectionId *string `json:"courier_connection_id,omitempty"`
	// CarbonEmissions The model contains the total amount of carbon emissions generated by the shipment. - AfterShip will provide this data only when it is available, and its availability is contingent upon the location and weight information that AfterShip can obtain.- The values will be accessible solely for shipments that have been successfully delivered. However, in the event of a shipping update after the delivery status has been achieved, the value may change.- It’s a paid service and only for Tracking Enterprise users, please contact your customer success manager if you want to know more.
	CarbonEmissions *TrackingCarbonEmissions `json:"carbon_emissions,omitempty"`
	// LocationId The location_id refers to the place where you fulfilled the items.  - If you provide a location_id, the system will automatically use it as the tracking's origin address. However, passing both location_id and any origin address information simultaneously is not allowed.- Please make sure you add your locations .
	LocationId *string `json:"location_id,omitempty"`
	// ShippingMethod The shipping_method string refers to the chosen method for delivering the package. Merchants typically offer various shipping methods to consumers during the checkout process, such as, Local Delivery, Free Express Worldwide Shipping, etc.
	ShippingMethod *string `json:"shipping_method,omitempty"`
	// FailedDeliveryAttempts By dynamically tracking failed delivery attempts during shipment, this field allows you to pinpoint carriers accountable for the most failures. Analyzing the root cause of these failures enables you to improve carriers' delivery standard operating procedures (SOP), leading to an overall enhancement in delivery service quality.
	FailedDeliveryAttempts *int `json:"failed_delivery_attempts,omitempty"`
	// SignatureRequirement The signature_requirement field serves the purpose of validating the service option type, specifically proof of delivery. By collecting the recipient's signature upon delivery, it ensures the package reaches the intended recipient and prevents disputes related to non-delivery or lost packages.</br>
	SignatureRequirement *TrackingSignatureRequirement `json:"signature_requirement,omitempty"`
	// DeliveryLocationType The delivery location type represents the secure area where the carrier leaves the package, such as a safe place, locker, mailbox, front porch, etc. This information helps ensure the shipment reaches the intended recipient efficiently, minimizing the risk of theft or damage.
	DeliveryLocationType *string `json:"delivery_location_type,omitempty"`
	// AftershipTrackingUrl The tracking URL directs your customers to the shipment tracking page which can display either the default or a customized page based on segmentation rules.- The universal URL is used by default, but you can opt for a custom domain if you have one. Learn how to set up a custom domain .The field is not automatically enabled in API & Webhook. Please contact support if you’d like to enable it.
	AftershipTrackingUrl *string `json:"aftership_tracking_url,omitempty"`
	// AftershipTrackingOrderUrl The order URL directs your customers to the order tracking page, which includes all shipments. It can display either the default or a customized page based on segmentation rules.- The universal URL is used by default, but you can opt for a custom domain if you have one. Learn how to set up a custom domain .The field is not automatically enabled in API & Webhook. Please contact support if you’d like to enable it.
	AftershipTrackingOrderUrl *string `json:"aftership_tracking_order_url,omitempty"`
	// FirstMile The field contains information about the first leg of the shipping starting from the carrier picking up the shipment from the shipper to the point where they hand it over to the last-mile carrier. Once AfterShip detects the shipment is multi-leg, we will populate the first-mile information under this object.
	FirstMile *TrackingFirstMile `json:"first_mile,omitempty"`
	// LastMile This field contains information about the last leg of the shipment, starting from the carrier who hands it over to the last-mile carrier, all the way to delivery. Once AfterShip detects that the shipment involves multiple legs and identifies the last-mile carrier, we will populate the last-mile carrier information in this object. Alternatively, the user can provide this information in this field to specify the last-mile carrier, which is helpful if AfterShip is unable to detect it automatically.
	LastMile *TrackingLastMile `json:"last_mile,omitempty"`
	// Customers The field contains the customer information associated with the tracking. A maximum of three customer objects are allowed.
	Customers []TrackingCustomers `json:"customers,omitempty"`
	// ProofOfDelivery An array of proof of delivery (POD) records, such as a signature or photo captured upon successful delivery.This field returns a value only after the feature is enabled. Please contact your customer success manager if you'd like to know more.
	ProofOfDelivery []TrackingProofOfDelivery `json:"proof_of_delivery,omitempty"`
	// MultiPieceInfo Multi-piece shipment refers to a scenario where a single shipment order is fulfilled by multiple physical packages. Each piece has its own carrier-assigned tracking number, but all pieces belong to the same shipment. This commonly occurs when an order is too large to fit in one box, or when items are packed separately for handling reasons.This field contains multi-piece shipment metadata describing a group of packages that belong to the same shipment.This field returns a value only when your subscription plan includes a multi-piece feature. To enable, go to .
	MultiPieceInfo *TrackingMultiPieceInfo `json:"multi_piece_info,omitempty"`
	// ShipmentDirection Indicates the business direction of the shipment in the e-commerce fulfillment lifecycle.Possible values:- `forward`: A forward (outbound-to-customer) shipment created for order fulfillment.- `return`: A return (customer-to-merchant) shipment created for after-sales return or exchange.This field is populated in either of the following cases:1. You explicitly provided it when creating the tracking.2. AfterShip automatically detected a linked forward or return shipment.It also determines which related shipment object (`forward_shipment` or `return_shipment`) may appear in the response.
	ShipmentDirection *TrackingShipmentDirection `json:"shipment_direction,omitempty"`
	// ReturnShipment The associated return shipment linked to the current outbound shipment.This field is only present when `shipment_direction = "forward"` and AfterShip has detected a linked return shipment.
	ReturnShipment *TrackingReturnShipment `json:"return_shipment,omitempty"`
	// ForwardShipment The original outbound shipment linked to this return. Use this to trace a return back to its source delivery.This field is only present when `shipment_direction = "return"` and AfterShip has detected a linked forward shipment.
	ForwardShipment *TrackingForwardShipment `json:"forward_shipment,omitempty"`
}

func (tracking *Tracking) SetId(val string) {
	tracking.Id = &val
}

func (tracking *Tracking) SetLegacyId(val string) {
	tracking.LegacyId = &val
}

func (tracking *Tracking) SetCreatedAt(val string) {
	tracking.CreatedAt = &val
}

func (tracking *Tracking) SetUpdatedAt(val string) {
	tracking.UpdatedAt = &val
}

func (tracking *Tracking) SetTrackingNumber(val string) {
	tracking.TrackingNumber = &val
}

func (tracking *Tracking) SetSlug(val string) {
	tracking.Slug = &val
}

func (tracking *Tracking) SetActive(val bool) {
	tracking.Active = &val
}

func (tracking *Tracking) SetCustomFields(val map[string]string) {
	tracking.CustomFields = val
}

func (tracking *Tracking) SetTransitTime(val int) {
	tracking.TransitTime = &val
}

func (tracking *Tracking) SetOriginCountryRegion(val string) {
	tracking.OriginCountryRegion = &val
}

func (tracking *Tracking) SetOriginState(val string) {
	tracking.OriginState = &val
}

func (tracking *Tracking) SetOriginCity(val string) {
	tracking.OriginCity = &val
}

func (tracking *Tracking) SetOriginPostalCode(val string) {
	tracking.OriginPostalCode = &val
}

func (tracking *Tracking) SetOriginRawLocation(val string) {
	tracking.OriginRawLocation = &val
}

func (tracking *Tracking) SetDestinationCountryRegion(val string) {
	tracking.DestinationCountryRegion = &val
}

func (tracking *Tracking) SetDestinationState(val string) {
	tracking.DestinationState = &val
}

func (tracking *Tracking) SetDestinationCity(val string) {
	tracking.DestinationCity = &val
}

func (tracking *Tracking) SetDestinationPostalCode(val string) {
	tracking.DestinationPostalCode = &val
}

func (tracking *Tracking) SetDestinationRawLocation(val string) {
	tracking.DestinationRawLocation = &val
}

func (tracking *Tracking) SetCourierDestinationCountryRegion(val string) {
	tracking.CourierDestinationCountryRegion = &val
}

func (tracking *Tracking) SetCourierEstimatedDeliveryDate(val TrackingCourierEstimatedDeliveryDate) {
	tracking.CourierEstimatedDeliveryDate = &val
}

func (tracking *Tracking) SetNote(val string) {
	tracking.Note = &val
}

func (tracking *Tracking) SetOrderId(val string) {
	tracking.OrderId = &val
}

func (tracking *Tracking) SetOrderIdPath(val string) {
	tracking.OrderIdPath = &val
}

func (tracking *Tracking) SetOrderDate(val string) {
	tracking.OrderDate = &val
}

func (tracking *Tracking) SetShipmentPackageCount(val float64) {
	tracking.ShipmentPackageCount = &val
}

func (tracking *Tracking) SetShipmentPickupDate(val string) {
	tracking.ShipmentPickupDate = &val
}

func (tracking *Tracking) SetShipmentDeliveryDate(val string) {
	tracking.ShipmentDeliveryDate = &val
}

func (tracking *Tracking) SetShipmentType(val string) {
	tracking.ShipmentType = &val
}

func (tracking *Tracking) SetShipmentWeight(val TrackingShipmentWeight) {
	tracking.ShipmentWeight = &val
}

func (tracking *Tracking) SetShipmentDimensions(val TrackingShipmentDimensions) {
	tracking.ShipmentDimensions = &val
}

func (tracking *Tracking) SetSignedBy(val string) {
	tracking.SignedBy = &val
}

func (tracking *Tracking) SetSource(val string) {
	tracking.Source = &val
}

func (tracking *Tracking) SetTag(val Tag) {
	tracking.Tag = &val
}

func (tracking *Tracking) SetSubtag(val string) {
	tracking.Subtag = &val
}

func (tracking *Tracking) SetSubtagMessage(val string) {
	tracking.SubtagMessage = &val
}

func (tracking *Tracking) SetTitle(val string) {
	tracking.Title = &val
}

func (tracking *Tracking) SetTrackedCount(val float64) {
	tracking.TrackedCount = &val
}

func (tracking *Tracking) SetLanguage(val string) {
	tracking.Language = &val
}

func (tracking *Tracking) SetUniqueToken(val string) {
	tracking.UniqueToken = &val
}

func (tracking *Tracking) SetCheckpoints(val []Checkpoint) {
	tracking.Checkpoints = val
}

func (tracking *Tracking) SetSubscribedSmses(val []string) {
	tracking.SubscribedSmses = val
}

func (tracking *Tracking) SetSubscribedEmails(val []string) {
	tracking.SubscribedEmails = val
}

func (tracking *Tracking) SetReturnToSender(val bool) {
	tracking.ReturnToSender = &val
}

func (tracking *Tracking) SetOrderPromisedDeliveryDate(val TrackingOrderPromisedDeliveryDate) {
	tracking.OrderPromisedDeliveryDate = &val
}

func (tracking *Tracking) SetDeliveryType(val string) {
	tracking.DeliveryType = &val
}

func (tracking *Tracking) SetPickupLocation(val string) {
	tracking.PickupLocation = &val
}

func (tracking *Tracking) SetPickupNote(val string) {
	tracking.PickupNote = &val
}

func (tracking *Tracking) SetCourierTrackingLink(val string) {
	tracking.CourierTrackingLink = &val
}

func (tracking *Tracking) SetFirstAttemptedAt(val string) {
	tracking.FirstAttemptedAt = &val
}

func (tracking *Tracking) SetCourierRedirectLink(val string) {
	tracking.CourierRedirectLink = &val
}

func (tracking *Tracking) SetTrackingAccountNumber(val string) {
	tracking.TrackingAccountNumber = &val
}

func (tracking *Tracking) SetTrackingKey(val string) {
	tracking.TrackingKey = &val
}

func (tracking *Tracking) SetTrackingShipDate(val string) {
	tracking.TrackingShipDate = &val
}

func (tracking *Tracking) SetOnTimeStatus(val string) {
	tracking.OnTimeStatus = &val
}

func (tracking *Tracking) SetOnTimeDifference(val float64) {
	tracking.OnTimeDifference = &val
}

func (tracking *Tracking) SetOrderTags(val []string) {
	tracking.OrderTags = val
}

func (tracking *Tracking) SetAftershipEstimatedDeliveryDate(val TrackingAftershipEstimatedDeliveryDate) {
	tracking.AftershipEstimatedDeliveryDate = &val
}

func (tracking *Tracking) SetCustomEstimatedDeliveryDate(val TrackingCustomEstimatedDeliveryDate) {
	tracking.CustomEstimatedDeliveryDate = &val
}

func (tracking *Tracking) SetOrderNumber(val string) {
	tracking.OrderNumber = &val
}

func (tracking *Tracking) SetFirstEstimatedDelivery(val TrackingFirstEstimatedDelivery) {
	tracking.FirstEstimatedDelivery = &val
}

func (tracking *Tracking) SetLatestEstimatedDelivery(val TrackingLatestEstimatedDelivery) {
	tracking.LatestEstimatedDelivery = &val
}

func (tracking *Tracking) SetShipmentTags(val []string) {
	tracking.ShipmentTags = val
}

func (tracking *Tracking) SetCourierConnectionId(val string) {
	tracking.CourierConnectionId = &val
}

func (tracking *Tracking) SetCarbonEmissions(val TrackingCarbonEmissions) {
	tracking.CarbonEmissions = &val
}

func (tracking *Tracking) SetLocationId(val string) {
	tracking.LocationId = &val
}

func (tracking *Tracking) SetShippingMethod(val string) {
	tracking.ShippingMethod = &val
}

func (tracking *Tracking) SetFailedDeliveryAttempts(val int) {
	tracking.FailedDeliveryAttempts = &val
}

func (tracking *Tracking) SetSignatureRequirement(val TrackingSignatureRequirement) {
	tracking.SignatureRequirement = &val
}

func (tracking *Tracking) SetDeliveryLocationType(val string) {
	tracking.DeliveryLocationType = &val
}

func (tracking *Tracking) SetAftershipTrackingUrl(val string) {
	tracking.AftershipTrackingUrl = &val
}

func (tracking *Tracking) SetAftershipTrackingOrderUrl(val string) {
	tracking.AftershipTrackingOrderUrl = &val
}

func (tracking *Tracking) SetFirstMile(val TrackingFirstMile) {
	tracking.FirstMile = &val
}

func (tracking *Tracking) SetLastMile(val TrackingLastMile) {
	tracking.LastMile = &val
}

func (tracking *Tracking) SetCustomers(val []TrackingCustomers) {
	tracking.Customers = val
}

func (tracking *Tracking) SetProofOfDelivery(val []TrackingProofOfDelivery) {
	tracking.ProofOfDelivery = val
}

func (tracking *Tracking) SetMultiPieceInfo(val TrackingMultiPieceInfo) {
	tracking.MultiPieceInfo = &val
}

func (tracking *Tracking) SetShipmentDirection(val TrackingShipmentDirection) {
	tracking.ShipmentDirection = &val
}

func (tracking *Tracking) SetReturnShipment(val TrackingReturnShipment) {
	tracking.ReturnShipment = &val
}

func (tracking *Tracking) SetForwardShipment(val TrackingForwardShipment) {
	tracking.ForwardShipment = &val
}
