// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// TrackingFirstEstimatedDeliverySource The source of the EDD. Either the carrier, AfterShip AI, or based on your custom EDD settings.
type TrackingFirstEstimatedDeliverySource string

const (
	TrackingFirstEstimatedDeliverySourceCarrierEdd   TrackingFirstEstimatedDeliverySource = "Carrier EDD"
	TrackingFirstEstimatedDeliverySourceAfterShipEdd TrackingFirstEstimatedDeliverySource = "AfterShip EDD"
	TrackingFirstEstimatedDeliverySourceCustomEdd    TrackingFirstEstimatedDeliverySource = "Custom EDD"
	TrackingFirstEstimatedDeliverySourceOrderEdd     TrackingFirstEstimatedDeliverySource = "Order EDD"
)
