// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// UpdateTrackingByIdRequestCustomers
type UpdateTrackingByIdRequestCustomers struct {
	// Role The  role of the customer, indicating whether the customer is  an individual or a company.
	Role *string `json:"role,omitempty"`
	// Name Customer name associated with the tracking.
	Name *string `json:"name,omitempty"`
	// PhoneNumber The phone number(s) to receive SMS notifications. Phone numbers should begin with a `+` sign and include the area code.
	PhoneNumber *string `json:"phone_number,omitempty"`
	// Email Email address(es) to receive email notifications.
	Email *string `json:"email,omitempty"`
	// Language The preferred language of the customer. If you have set up AfterShip notifications in different languages, we use this to send the tracking updates to the customer in their preferred language.
	Language *string `json:"language,omitempty"`
	// Id The customer's identifier on the merchant or platform (for example, Shopify) side.
	Id *string `json:"id,omitempty"`
}

func (updateTrackingByIdRequestCustomers *UpdateTrackingByIdRequestCustomers) SetRole(val string) {
	updateTrackingByIdRequestCustomers.Role = &val
}

func (updateTrackingByIdRequestCustomers *UpdateTrackingByIdRequestCustomers) SetName(val string) {
	updateTrackingByIdRequestCustomers.Name = &val
}

func (updateTrackingByIdRequestCustomers *UpdateTrackingByIdRequestCustomers) SetPhoneNumber(val string) {
	updateTrackingByIdRequestCustomers.PhoneNumber = &val
}

func (updateTrackingByIdRequestCustomers *UpdateTrackingByIdRequestCustomers) SetEmail(val string) {
	updateTrackingByIdRequestCustomers.Email = &val
}

func (updateTrackingByIdRequestCustomers *UpdateTrackingByIdRequestCustomers) SetLanguage(val string) {
	updateTrackingByIdRequestCustomers.Language = &val
}

func (updateTrackingByIdRequestCustomers *UpdateTrackingByIdRequestCustomers) SetId(val string) {
	updateTrackingByIdRequestCustomers.Id = &val
}
