// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// UpdateTrackingByIdRequestOrderPromisedDeliveryDate The promised delivery date of the order in shipment recipient’s timezone.
type UpdateTrackingByIdRequestOrderPromisedDeliveryDate struct {
	// PromisedDeliveryDate The promised delivery date of the order. It uses the formats:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	PromisedDeliveryDate *string `json:"promised_delivery_date,omitempty"`
	// PromisedDeliveryDateMin Earliest promised delivery date of the order. It uses the formats:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	PromisedDeliveryDateMin *string `json:"promised_delivery_date_min,omitempty"`
	// PromisedDeliveryDateMax Latest promised delivery date of the order. It uses the formats:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
	PromisedDeliveryDateMax *string `json:"promised_delivery_date_max,omitempty"`
}

func (updateTrackingByIdRequestOrderPromisedDeliveryDate *UpdateTrackingByIdRequestOrderPromisedDeliveryDate) SetPromisedDeliveryDate(val string) {
	updateTrackingByIdRequestOrderPromisedDeliveryDate.PromisedDeliveryDate = &val
}

func (updateTrackingByIdRequestOrderPromisedDeliveryDate *UpdateTrackingByIdRequestOrderPromisedDeliveryDate) SetPromisedDeliveryDateMin(val string) {
	updateTrackingByIdRequestOrderPromisedDeliveryDate.PromisedDeliveryDateMin = &val
}

func (updateTrackingByIdRequestOrderPromisedDeliveryDate *UpdateTrackingByIdRequestOrderPromisedDeliveryDate) SetPromisedDeliveryDateMax(val string) {
	updateTrackingByIdRequestOrderPromisedDeliveryDate.PromisedDeliveryDateMax = &val
}
