// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// UpdateTrackingByIdRequestDeliveryType Shipment delivery type- `pickup_at_store`- `pickup_at_courier`- `door_to_door`
type UpdateTrackingByIdRequestDeliveryType string

const (
	UpdateTrackingByIdRequestDeliveryTypePickupAtStore   UpdateTrackingByIdRequestDeliveryType = "pickup_at_store"
	UpdateTrackingByIdRequestDeliveryTypePickupAtCourier UpdateTrackingByIdRequestDeliveryType = "pickup_at_courier"
	UpdateTrackingByIdRequestDeliveryTypeDoorToDoor      UpdateTrackingByIdRequestDeliveryType = "door_to_door"
)
