// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package model

// UpdateTrackingByIdRequestShipmentDirection Indicates the business direction of the shipment in the e-commerce fulfillment lifecycle.Possible values:- `forward`: A forward (outbound-to-customer) shipment created for order fulfillment.- `return`: A return (customer-to-merchant) shipment created for after-sales return or exchange.When provided, this field gives AfterShip additional context about the shipment's intent, enabling more accurate status identification.
type UpdateTrackingByIdRequestShipmentDirection string

const (
	UpdateTrackingByIdRequestShipmentDirectionForward UpdateTrackingByIdRequestShipmentDirection = "forward"
	UpdateTrackingByIdRequestShipmentDirectionReturn  UpdateTrackingByIdRequestShipmentDirection = "return"
)
