// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package request

import (
	"fmt"
	"net/http"
    "bytes"
    "encoding/json"
	"github.com/aftership/tracking-sdk-go/v7/component"
	"github.com/aftership/tracking-sdk-go/v7/errorx"
	"github.com/aftership/tracking-sdk-go/v7/model"
)

type CreateTrackingRequest struct {
	body  model.CreateTrackingRequest
	header http.Header
	sender *component.HttpSender
	requestBuilder
}

func NewCreateTrackingRequest(sender *component.HttpSender) *CreateTrackingRequest {
	return &CreateTrackingRequest{
        sender: sender,
	}
}


func (t *CreateTrackingRequest) BuildBody(body model.CreateTrackingRequest) *CreateTrackingRequest {
	t.body = body
	return t
}

func (t *CreateTrackingRequest) BuildHeader(h http.Header) *CreateTrackingRequest {
	t.header = h
	return t
}



func (t *CreateTrackingRequest) build() (*http.Request, error) {
    uri := fmt.Sprintf("/tracking/2025-01/trackings?") 
    body,err := json.Marshal(t.body)
    if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
    }
    req, err := http.NewRequest("POST", uri, bytes.NewReader(body))
	if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *CreateTrackingRequest) Execute() (  *model.CreateTrackingResponse, error) {
	req, err := t.build()
	if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	var data model.CreateTrackingResponse
	return &data, t.sender.Do(req, &data)
}