// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package request

import (
	"errors"
	"fmt"
	"github.com/aftership/tracking-sdk-go/v8/component"
	"github.com/aftership/tracking-sdk-go/v8/errorx"
	"github.com/aftership/tracking-sdk-go/v8/model"
	"net/http"
)

type DeleteCourierConnectionsByIdRequest struct {
	id     string
	header http.Header
	sender *component.HttpSender
	requestBuilder
}

func NewDeleteCourierConnectionsByIdRequest(sender *component.HttpSender) *DeleteCourierConnectionsByIdRequest {
	return &DeleteCourierConnectionsByIdRequest{
		sender: sender,
	}
}

func (t *DeleteCourierConnectionsByIdRequest) BuildHeader(h http.Header) *DeleteCourierConnectionsByIdRequest {
	t.header = h
	return t
}

func (t *DeleteCourierConnectionsByIdRequest) BuildPath(id string) *DeleteCourierConnectionsByIdRequest {
	t.id = id
	return t
}

func (t *DeleteCourierConnectionsByIdRequest) isPathParamValid() error {
	if t.id == "" {
		return errors.New("path param `id` can not be empty")
	}
	return nil
}

func (t *DeleteCourierConnectionsByIdRequest) build() (*http.Request, error) {
	if err := t.isPathParamValid(); err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	uri := fmt.Sprintf("/tracking/2025-04/courier-connections/%s?", t.id)
	req, err := http.NewRequest("DELETE", uri, nil)
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *DeleteCourierConnectionsByIdRequest) Execute() (*model.DeleteCourierConnectionsByIdResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	var data model.DeleteCourierConnectionsByIdResponse
	return &data, t.sender.Do(req, &data)
}
