// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package request

import (
    "errors"
	"fmt"
	"net/http"
    "bytes"
    "encoding/json"
	"github.com/google/go-querystring/query"
	"github.com/AfterShip/tracking-sdk-go/v4/component"
	"github.com/AfterShip/tracking-sdk-go/v4/errorx"
	"github.com/AfterShip/tracking-sdk-go/v4/model"
)

type DeleteNotificationBySlugTrackingNumberRequest struct {
	slug     string
	trackingNumber     string
	body  model.DeleteNotificationBySlugTrackingNumberRequest
    query  model.DeleteNotificationBySlugTrackingNumberQuery
	header http.Header
	sender *component.HttpSender
	requestBuilder
}

func NewDeleteNotificationBySlugTrackingNumberRequest(sender *component.HttpSender) *DeleteNotificationBySlugTrackingNumberRequest {
	return &DeleteNotificationBySlugTrackingNumberRequest{
        sender: sender,
	}
}

func (t *DeleteNotificationBySlugTrackingNumberRequest) BuildQuery(query model.DeleteNotificationBySlugTrackingNumberQuery) *DeleteNotificationBySlugTrackingNumberRequest {
	t.query = query
	return t
}

func (t *DeleteNotificationBySlugTrackingNumberRequest) BuildBody(body model.DeleteNotificationBySlugTrackingNumberRequest) *DeleteNotificationBySlugTrackingNumberRequest {
	t.body = body
	return t
}

func (t *DeleteNotificationBySlugTrackingNumberRequest) BuildHeader(h http.Header) *DeleteNotificationBySlugTrackingNumberRequest {
	t.header = h
	return t
}

func (t *DeleteNotificationBySlugTrackingNumberRequest) BuildPath( slug string, trackingNumber string,) *DeleteNotificationBySlugTrackingNumberRequest {
	t.slug = slug
	t.trackingNumber = trackingNumber
	return t
}

func (t *DeleteNotificationBySlugTrackingNumberRequest) isPathParamValid() error {
    if t.slug == "" {
        return errors.New("path param `slug` can not be empty")
    }
    return nil
    if t.trackingNumber == "" {
        return errors.New("path param `trackingNumber` can not be empty")
    }
    return nil
}

func (t *DeleteNotificationBySlugTrackingNumberRequest) build() (*http.Request, error) {
	q, err := query.Values(t.query)
	if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
    if err := t.isPathParamValid(); err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
    }
    uri := fmt.Sprintf("/tracking/2024-04/notifications/%s/%s/remove?",  t.slug, t.trackingNumber,)  + q.Encode()
    body,err := json.Marshal(t.body)
    if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
    }
    req, err := http.NewRequest("POST", uri, bytes.NewReader(body))
	if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *DeleteNotificationBySlugTrackingNumberRequest) Execute() ( *model.Notification , error) {
	req, err := t.build()
	if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	var data model.DeleteNotificationBySlugTrackingNumberResponse
	err = t.sender.Do(req, &data)
	return &data.Notification,err
}