// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package request

import (
    "errors"
	"fmt"
	"net/http"
	"github.com/google/go-querystring/query"
	"github.com/aftership/tracking-sdk-go/v4/component"
	"github.com/aftership/tracking-sdk-go/v4/errorx"
	"github.com/aftership/tracking-sdk-go/v4/model"
)

type DeleteTrackingBySlugTrackingNumberRequest struct {
	slug     string
	trackingNumber     string
    query  model.DeleteTrackingBySlugTrackingNumberQuery
	header http.Header
	sender *component.HttpSender
	requestBuilder
}

func NewDeleteTrackingBySlugTrackingNumberRequest(sender *component.HttpSender) *DeleteTrackingBySlugTrackingNumberRequest {
	return &DeleteTrackingBySlugTrackingNumberRequest{
        sender: sender,
	}
}

func (t *DeleteTrackingBySlugTrackingNumberRequest) BuildQuery(query model.DeleteTrackingBySlugTrackingNumberQuery) *DeleteTrackingBySlugTrackingNumberRequest {
	t.query = query
	return t
}


func (t *DeleteTrackingBySlugTrackingNumberRequest) BuildHeader(h http.Header) *DeleteTrackingBySlugTrackingNumberRequest {
	t.header = h
	return t
}

func (t *DeleteTrackingBySlugTrackingNumberRequest) BuildPath( slug string, trackingNumber string,) *DeleteTrackingBySlugTrackingNumberRequest {
	t.slug = slug
	t.trackingNumber = trackingNumber
	return t
}

func (t *DeleteTrackingBySlugTrackingNumberRequest) isPathParamValid() error {
    if t.slug == "" {
        return errors.New("path param `slug` can not be empty")
    }
    return nil
    if t.trackingNumber == "" {
        return errors.New("path param `trackingNumber` can not be empty")
    }
    return nil
}

func (t *DeleteTrackingBySlugTrackingNumberRequest) build() (*http.Request, error) {
	q, err := query.Values(t.query)
	if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
    if err := t.isPathParamValid(); err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
    }
    uri := fmt.Sprintf("/tracking/2024-04/trackings/%s/%s?",  t.slug, t.trackingNumber,)  + q.Encode()
    req, err := http.NewRequest("DELETE", uri, nil)
	if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *DeleteTrackingBySlugTrackingNumberRequest) Execute() ( *model.PartialDeleteTracking , error) {
	req, err := t.build()
	if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	var data model.DeleteTrackingBySlugTrackingNumberResponse
	err = t.sender.Do(req, &data)
	return &data.Tracking,err
}