// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package request

import (
	"bytes"
	"encoding/json"
	"fmt"
	"github.com/aftership/tracking-sdk-go/v9/component"
	"github.com/aftership/tracking-sdk-go/v9/errorx"
	"github.com/aftership/tracking-sdk-go/v9/model"
	"net/http"
)

type DetectCourierRequest struct {
	body   model.DetectCourierRequest
	header http.Header
	sender *component.HttpSender
	requestBuilder
}

func NewDetectCourierRequest(sender *component.HttpSender) *DetectCourierRequest {
	return &DetectCourierRequest{
		sender: sender,
	}
}

func (t *DetectCourierRequest) BuildBody(body model.DetectCourierRequest) *DetectCourierRequest {
	t.body = body
	return t
}

func (t *DetectCourierRequest) BuildHeader(h http.Header) *DetectCourierRequest {
	t.header = h
	return t
}

func (t *DetectCourierRequest) build() (*http.Request, error) {
	uri := fmt.Sprintf("/tracking/2025-07/couriers/detect?")
	body, err := json.Marshal(t.body)
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	req, err := http.NewRequest("POST", uri, bytes.NewReader(body))
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *DetectCourierRequest) Execute() (*model.DetectCourierResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	var data model.DetectCourierResponse
	return &data, t.sender.Do(req, &data)
}
