// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package request

import (
    "errors"
	"fmt"
	"net/http"
	"github.com/google/go-querystring/query"
	"github.com/AfterShip/tracking-sdk-go/v4/component"
	"github.com/AfterShip/tracking-sdk-go/v4/errorx"
	"github.com/AfterShip/tracking-sdk-go/v4/model"
)

type GetCheckpointBySlugTrackingNumberRequest struct {
	slug     string
	trackingNumber     string
    query  model.GetCheckpointBySlugTrackingNumberQuery
	header http.Header
	sender *component.HttpSender
	requestBuilder
}

func NewGetCheckpointBySlugTrackingNumberRequest(sender *component.HttpSender) *GetCheckpointBySlugTrackingNumberRequest {
	return &GetCheckpointBySlugTrackingNumberRequest{
        sender: sender,
	}
}

func (t *GetCheckpointBySlugTrackingNumberRequest) BuildQuery(query model.GetCheckpointBySlugTrackingNumberQuery) *GetCheckpointBySlugTrackingNumberRequest {
	t.query = query
	return t
}


func (t *GetCheckpointBySlugTrackingNumberRequest) BuildHeader(h http.Header) *GetCheckpointBySlugTrackingNumberRequest {
	t.header = h
	return t
}

func (t *GetCheckpointBySlugTrackingNumberRequest) BuildPath( slug string, trackingNumber string,) *GetCheckpointBySlugTrackingNumberRequest {
	t.slug = slug
	t.trackingNumber = trackingNumber
	return t
}

func (t *GetCheckpointBySlugTrackingNumberRequest) isPathParamValid() error {
    if t.slug == "" {
        return errors.New("path param `slug` can not be empty")
    }
    return nil
    if t.trackingNumber == "" {
        return errors.New("path param `trackingNumber` can not be empty")
    }
    return nil
}

func (t *GetCheckpointBySlugTrackingNumberRequest) build() (*http.Request, error) {
	q, err := query.Values(t.query)
	if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
    if err := t.isPathParamValid(); err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
    }
    uri := fmt.Sprintf("/tracking/2024-04/last_checkpoint/%s/%s?",  t.slug, t.trackingNumber,)  + q.Encode()
    req, err := http.NewRequest("GET", uri, nil)
	if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *GetCheckpointBySlugTrackingNumberRequest) Execute() (  *model.GetCheckpointBySlugTrackingNumberResponse, error) {
	req, err := t.build()
	if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	var data model.GetCheckpointBySlugTrackingNumberResponse
	return &data, t.sender.Do(req, &data)
}