// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package request

import (
    "errors"
	"fmt"
	"net/http"
	"github.com/google/go-querystring/query"
	"github.com/AfterShip/tracking-sdk-go/v4/component"
	"github.com/AfterShip/tracking-sdk-go/v4/errorx"
	"github.com/AfterShip/tracking-sdk-go/v4/model"
)

type GetCheckpointByTrackingIdRequest struct {
	trackingId     string
    query  model.GetCheckpointByTrackingIdQuery
	header http.Header
	sender *component.HttpSender
	requestBuilder
}

func NewGetCheckpointByTrackingIdRequest(sender *component.HttpSender) *GetCheckpointByTrackingIdRequest {
	return &GetCheckpointByTrackingIdRequest{
        sender: sender,
	}
}

func (t *GetCheckpointByTrackingIdRequest) BuildQuery(query model.GetCheckpointByTrackingIdQuery) *GetCheckpointByTrackingIdRequest {
	t.query = query
	return t
}


func (t *GetCheckpointByTrackingIdRequest) BuildHeader(h http.Header) *GetCheckpointByTrackingIdRequest {
	t.header = h
	return t
}

func (t *GetCheckpointByTrackingIdRequest) BuildPath( trackingId string,) *GetCheckpointByTrackingIdRequest {
	t.trackingId = trackingId
	return t
}

func (t *GetCheckpointByTrackingIdRequest) isPathParamValid() error {
    if t.trackingId == "" {
        return errors.New("path param `trackingId` can not be empty")
    }
    return nil
}

func (t *GetCheckpointByTrackingIdRequest) build() (*http.Request, error) {
	q, err := query.Values(t.query)
	if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
    if err := t.isPathParamValid(); err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
    }
    uri := fmt.Sprintf("/tracking/2024-04/last_checkpoint/%s?",  t.trackingId,)  + q.Encode()
    req, err := http.NewRequest("GET", uri, nil)
	if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *GetCheckpointByTrackingIdRequest) Execute() (  *model.GetCheckpointByTrackingIdResponse, error) {
	req, err := t.build()
	if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	var data model.GetCheckpointByTrackingIdResponse
	return &data, t.sender.Do(req, &data)
}