// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package request

import (
	"errors"
	"fmt"
	"github.com/aftership/tracking-sdk-go/v9/component"
	"github.com/aftership/tracking-sdk-go/v9/errorx"
	"github.com/aftership/tracking-sdk-go/v9/model"
	"net/http"
)

type GetCourierConnectionsByIdRequest struct {
	id     string
	header http.Header
	sender *component.HttpSender
	requestBuilder
}

func NewGetCourierConnectionsByIdRequest(sender *component.HttpSender) *GetCourierConnectionsByIdRequest {
	return &GetCourierConnectionsByIdRequest{
		sender: sender,
	}
}

func (t *GetCourierConnectionsByIdRequest) BuildHeader(h http.Header) *GetCourierConnectionsByIdRequest {
	t.header = h
	return t
}

func (t *GetCourierConnectionsByIdRequest) BuildPath(id string) *GetCourierConnectionsByIdRequest {
	t.id = id
	return t
}

func (t *GetCourierConnectionsByIdRequest) isPathParamValid() error {
	if t.id == "" {
		return errors.New("path param `id` can not be empty")
	}
	return nil
}

func (t *GetCourierConnectionsByIdRequest) build() (*http.Request, error) {
	if err := t.isPathParamValid(); err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	uri := fmt.Sprintf("/tracking/2025-07/courier-connections/%s?", t.id)
	req, err := http.NewRequest("GET", uri, nil)
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *GetCourierConnectionsByIdRequest) Execute() (*model.GetCourierConnectionsByIdResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	var data model.GetCourierConnectionsByIdResponse
	return &data, t.sender.Do(req, &data)
}
