// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package request

import (
	"fmt"
	"github.com/aftership/tracking-sdk-go/v9/component"
	"github.com/aftership/tracking-sdk-go/v9/errorx"
	"github.com/aftership/tracking-sdk-go/v9/model"
	"github.com/google/go-querystring/query"
	"net/http"
)

type GetCouriersRequest struct {
	query  model.GetCouriersQuery
	header http.Header
	sender *component.HttpSender
	requestBuilder
}

func NewGetCouriersRequest(sender *component.HttpSender) *GetCouriersRequest {
	return &GetCouriersRequest{
		sender: sender,
	}
}

func (t *GetCouriersRequest) BuildQuery(query model.GetCouriersQuery) *GetCouriersRequest {
	t.query = query
	return t
}

func (t *GetCouriersRequest) BuildHeader(h http.Header) *GetCouriersRequest {
	t.header = h
	return t
}

func (t *GetCouriersRequest) build() (*http.Request, error) {
	q, err := query.Values(t.query)
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	uri := fmt.Sprintf("/tracking/2025-07/couriers?") + q.Encode()
	req, err := http.NewRequest("GET", uri, nil)
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *GetCouriersRequest) Execute() (*model.GetCouriersResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	var data model.GetCouriersResponse
	return &data, t.sender.Do(req, &data)
}
