// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package request

import (
	"fmt"
	"github.com/aftership/tracking-sdk-go/v8/component"
	"github.com/aftership/tracking-sdk-go/v8/errorx"
	"github.com/aftership/tracking-sdk-go/v8/model"
	"github.com/google/go-querystring/query"
	"net/http"
)

type GetCourierConnectionsRequest struct {
	query  model.GetCourierConnectionsQuery
	header http.Header
	sender *component.HttpSender
	requestBuilder
}

func NewGetCourierConnectionsRequest(sender *component.HttpSender) *GetCourierConnectionsRequest {
	return &GetCourierConnectionsRequest{
		sender: sender,
	}
}

func (t *GetCourierConnectionsRequest) BuildQuery(query model.GetCourierConnectionsQuery) *GetCourierConnectionsRequest {
	t.query = query
	return t
}

func (t *GetCourierConnectionsRequest) BuildHeader(h http.Header) *GetCourierConnectionsRequest {
	t.header = h
	return t
}

func (t *GetCourierConnectionsRequest) build() (*http.Request, error) {
	q, err := query.Values(t.query)
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	uri := fmt.Sprintf("/tracking/2025-04/courier-connections?") + q.Encode()
	req, err := http.NewRequest("GET", uri, nil)
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *GetCourierConnectionsRequest) Execute() (*model.CourierConnectionPagination, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	var data model.GetCourierConnectionsResponse
	err = t.sender.Do(req, &data)
	var result model.CourierConnectionPagination
	result.NextCursor = data.Pagination.NextCursor
	result.HasNextPage = data.Pagination.HasNextPage
	result.Total = data.Pagination.Total
	result.CourierConnection = data.CourierConnections
	return &result, err
}
