// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package request

import (
	"errors"
	"fmt"
	"github.com/aftership/tracking-sdk-go/v6/component"
	"github.com/aftership/tracking-sdk-go/v6/errorx"
	"github.com/aftership/tracking-sdk-go/v6/model"
	"github.com/google/go-querystring/query"
	"net/http"
)

type GetTrackingByIdRequest struct {
	id     string
	query  model.GetTrackingByIdQuery
	header http.Header
	sender *component.HttpSender
	requestBuilder
}

func NewGetTrackingByIdRequest(sender *component.HttpSender) *GetTrackingByIdRequest {
	return &GetTrackingByIdRequest{
		sender: sender,
	}
}

func (t *GetTrackingByIdRequest) BuildQuery(query model.GetTrackingByIdQuery) *GetTrackingByIdRequest {
	t.query = query
	return t
}

func (t *GetTrackingByIdRequest) BuildHeader(h http.Header) *GetTrackingByIdRequest {
	t.header = h
	return t
}

func (t *GetTrackingByIdRequest) BuildPath(id string) *GetTrackingByIdRequest {
	t.id = id
	return t
}

func (t *GetTrackingByIdRequest) isPathParamValid() error {
	if t.id == "" {
		return errors.New("path param `id` can not be empty")
	}
	return nil
}

func (t *GetTrackingByIdRequest) build() (*http.Request, error) {
	q, err := query.Values(t.query)
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	if err := t.isPathParamValid(); err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	uri := fmt.Sprintf("/tracking/2024-10/trackings/%s?", t.id) + q.Encode()
	req, err := http.NewRequest("GET", uri, nil)
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *GetTrackingByIdRequest) Execute() (*model.GetTrackingByIdResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	var data model.GetTrackingByIdResponse
	return &data, t.sender.Do(req, &data)
}
