// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package request

import (
    "errors"
	"fmt"
	"net/http"
    "bytes"
    "encoding/json"
	"github.com/aftership/tracking-sdk-go/v4/component"
	"github.com/aftership/tracking-sdk-go/v4/errorx"
	"github.com/aftership/tracking-sdk-go/v4/model"
)

type MarkTrackingCompletedByIdRequest struct {
	id     string
	body  model.MarkTrackingCompletedByIdRequest
	header http.Header
	sender *component.HttpSender
	requestBuilder
}

func NewMarkTrackingCompletedByIdRequest(sender *component.HttpSender) *MarkTrackingCompletedByIdRequest {
	return &MarkTrackingCompletedByIdRequest{
        sender: sender,
	}
}


func (t *MarkTrackingCompletedByIdRequest) BuildBody(body model.MarkTrackingCompletedByIdRequest) *MarkTrackingCompletedByIdRequest {
	t.body = body
	return t
}

func (t *MarkTrackingCompletedByIdRequest) BuildHeader(h http.Header) *MarkTrackingCompletedByIdRequest {
	t.header = h
	return t
}

func (t *MarkTrackingCompletedByIdRequest) BuildPath( id string,) *MarkTrackingCompletedByIdRequest {
	t.id = id
	return t
}

func (t *MarkTrackingCompletedByIdRequest) isPathParamValid() error {
    if t.id == "" {
        return errors.New("path param `id` can not be empty")
    }
    return nil
}

func (t *MarkTrackingCompletedByIdRequest) build() (*http.Request, error) {
    if err := t.isPathParamValid(); err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
    }
    uri := fmt.Sprintf("/tracking/2024-04/trackings/%s/mark-as-completed?",  t.id,) 
    body,err := json.Marshal(t.body)
    if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
    }
    req, err := http.NewRequest("POST", uri, bytes.NewReader(body))
	if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *MarkTrackingCompletedByIdRequest) Execute() ( *model.Tracking , error) {
	req, err := t.build()
	if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	var data model.MarkTrackingCompletedByIdResponse
	err = t.sender.Do(req, &data)
	return &data.Tracking,err
}