// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package request

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/aftership/tracking-sdk-go/v5/component"
	"github.com/aftership/tracking-sdk-go/v5/errorx"
	"github.com/aftership/tracking-sdk-go/v5/model"
	"github.com/google/go-querystring/query"
	"net/http"
)

type MarkTrackingCompletedBySlugTrackingNumberRequest struct {
	slug           string
	trackingNumber string
	body           model.MarkTrackingCompletedBySlugTrackingNumberRequest
	query          model.MarkTrackingCompletedBySlugTrackingNumberQuery
	header         http.Header
	sender         *component.HttpSender
	requestBuilder
}

func NewMarkTrackingCompletedBySlugTrackingNumberRequest(sender *component.HttpSender) *MarkTrackingCompletedBySlugTrackingNumberRequest {
	return &MarkTrackingCompletedBySlugTrackingNumberRequest{
		sender: sender,
	}
}

func (t *MarkTrackingCompletedBySlugTrackingNumberRequest) BuildQuery(query model.MarkTrackingCompletedBySlugTrackingNumberQuery) *MarkTrackingCompletedBySlugTrackingNumberRequest {
	t.query = query
	return t
}

func (t *MarkTrackingCompletedBySlugTrackingNumberRequest) BuildBody(body model.MarkTrackingCompletedBySlugTrackingNumberRequest) *MarkTrackingCompletedBySlugTrackingNumberRequest {
	t.body = body
	return t
}

func (t *MarkTrackingCompletedBySlugTrackingNumberRequest) BuildHeader(h http.Header) *MarkTrackingCompletedBySlugTrackingNumberRequest {
	t.header = h
	return t
}

func (t *MarkTrackingCompletedBySlugTrackingNumberRequest) BuildPath(slug string, trackingNumber string) *MarkTrackingCompletedBySlugTrackingNumberRequest {
	t.slug = slug
	t.trackingNumber = trackingNumber
	return t
}

func (t *MarkTrackingCompletedBySlugTrackingNumberRequest) isPathParamValid() error {
	if t.slug == "" {
		return errors.New("path param `slug` can not be empty")
	}
	return nil
	if t.trackingNumber == "" {
		return errors.New("path param `trackingNumber` can not be empty")
	}
	return nil
}

func (t *MarkTrackingCompletedBySlugTrackingNumberRequest) build() (*http.Request, error) {
	q, err := query.Values(t.query)
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	if err := t.isPathParamValid(); err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	uri := fmt.Sprintf("/tracking/2024-07/trackings/%s/%s/mark-as-completed?", t.slug, t.trackingNumber) + q.Encode()
	body, err := json.Marshal(t.body)
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	req, err := http.NewRequest("POST", uri, bytes.NewReader(body))
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *MarkTrackingCompletedBySlugTrackingNumberRequest) Execute() (*model.MarkTrackingCompletedBySlugTrackingNumberResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	var data model.MarkTrackingCompletedBySlugTrackingNumberResponse
	return &data, t.sender.Do(req, &data)
}
