// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package request

import (
	"bytes"
	"encoding/json"
	"fmt"
	"github.com/aftership/tracking-sdk-go/v8/component"
	"github.com/aftership/tracking-sdk-go/v8/errorx"
	"github.com/aftership/tracking-sdk-go/v8/model"
	"net/http"
)

type PostCourierConnectionsRequest struct {
	body   model.PostCourierConnectionsRequest
	header http.Header
	sender *component.HttpSender
	requestBuilder
}

func NewPostCourierConnectionsRequest(sender *component.HttpSender) *PostCourierConnectionsRequest {
	return &PostCourierConnectionsRequest{
		sender: sender,
	}
}

func (t *PostCourierConnectionsRequest) BuildBody(body model.PostCourierConnectionsRequest) *PostCourierConnectionsRequest {
	t.body = body
	return t
}

func (t *PostCourierConnectionsRequest) BuildHeader(h http.Header) *PostCourierConnectionsRequest {
	t.header = h
	return t
}

func (t *PostCourierConnectionsRequest) build() (*http.Request, error) {
	uri := fmt.Sprintf("/tracking/2025-04/courier-connections?")
	body, err := json.Marshal(t.body)
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	req, err := http.NewRequest("POST", uri, bytes.NewReader(body))
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *PostCourierConnectionsRequest) Execute() (*model.PostCourierConnectionsResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	var data model.PostCourierConnectionsResponse
	return &data, t.sender.Do(req, &data)
}
