// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package request

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/aftership/tracking-sdk-go/v8/component"
	"github.com/aftership/tracking-sdk-go/v8/errorx"
	"github.com/aftership/tracking-sdk-go/v8/model"
	"net/http"
)

type PutCourierConnectionsByIdRequest struct {
	id     string
	body   model.PutCourierConnectionsByIdRequest
	header http.Header
	sender *component.HttpSender
	requestBuilder
}

func NewPutCourierConnectionsByIdRequest(sender *component.HttpSender) *PutCourierConnectionsByIdRequest {
	return &PutCourierConnectionsByIdRequest{
		sender: sender,
	}
}

func (t *PutCourierConnectionsByIdRequest) BuildBody(body model.PutCourierConnectionsByIdRequest) *PutCourierConnectionsByIdRequest {
	t.body = body
	return t
}

func (t *PutCourierConnectionsByIdRequest) BuildHeader(h http.Header) *PutCourierConnectionsByIdRequest {
	t.header = h
	return t
}

func (t *PutCourierConnectionsByIdRequest) BuildPath(id string) *PutCourierConnectionsByIdRequest {
	t.id = id
	return t
}

func (t *PutCourierConnectionsByIdRequest) isPathParamValid() error {
	if t.id == "" {
		return errors.New("path param `id` can not be empty")
	}
	return nil
}

func (t *PutCourierConnectionsByIdRequest) build() (*http.Request, error) {
	if err := t.isPathParamValid(); err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	uri := fmt.Sprintf("/tracking/2025-04/courier-connections/%s?", t.id)
	body, err := json.Marshal(t.body)
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	req, err := http.NewRequest("PATCH", uri, bytes.NewReader(body))
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *PutCourierConnectionsByIdRequest) Execute() (*model.PutCourierConnectionsByIdResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	var data model.PutCourierConnectionsByIdResponse
	return &data, t.sender.Do(req, &data)
}
