// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package request

import "net/http"

type requestBuilder struct{}

func (r *requestBuilder) appendHeader(header http.Header, req *http.Request) {
	if len(header) == 0 {
		return
	}
	for k, v := range header {
		if len(v) > 0 {
			req.Header.Set(k, v[0])
		}
	}
}
