// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package request

import (
	"errors"
	"fmt"
	"github.com/aftership/tracking-sdk-go/v6/component"
	"github.com/aftership/tracking-sdk-go/v6/errorx"
	"github.com/aftership/tracking-sdk-go/v6/model"
	"net/http"
)

type RetrackTrackingByIdRequest struct {
	id     string
	header http.Header
	sender *component.HttpSender
	requestBuilder
}

func NewRetrackTrackingByIdRequest(sender *component.HttpSender) *RetrackTrackingByIdRequest {
	return &RetrackTrackingByIdRequest{
		sender: sender,
	}
}

func (t *RetrackTrackingByIdRequest) BuildHeader(h http.Header) *RetrackTrackingByIdRequest {
	t.header = h
	return t
}

func (t *RetrackTrackingByIdRequest) BuildPath(id string) *RetrackTrackingByIdRequest {
	t.id = id
	return t
}

func (t *RetrackTrackingByIdRequest) isPathParamValid() error {
	if t.id == "" {
		return errors.New("path param `id` can not be empty")
	}
	return nil
}

func (t *RetrackTrackingByIdRequest) build() (*http.Request, error) {
	if err := t.isPathParamValid(); err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	uri := fmt.Sprintf("/tracking/2024-10/trackings/%s/retrack?", t.id)
	req, err := http.NewRequest("POST", uri, nil)
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *RetrackTrackingByIdRequest) Execute() (*model.RetrackTrackingByIdResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	var data model.RetrackTrackingByIdResponse
	return &data, t.sender.Do(req, &data)
}
