// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package request

import (
    "errors"
	"fmt"
	"net/http"
    "bytes"
    "encoding/json"
	"github.com/google/go-querystring/query"
	"github.com/AfterShip/tracking-sdk-go/v4/component"
	"github.com/AfterShip/tracking-sdk-go/v4/errorx"
	"github.com/AfterShip/tracking-sdk-go/v4/model"
)

type UpdateTrackingBySlugTrackingNumberRequest struct {
	slug     string
	trackingNumber     string
	body  model.UpdateTrackingBySlugTrackingNumberRequest
    query  model.UpdateTrackingBySlugTrackingNumberQuery
	header http.Header
	sender *component.HttpSender
	requestBuilder
}

func NewUpdateTrackingBySlugTrackingNumberRequest(sender *component.HttpSender) *UpdateTrackingBySlugTrackingNumberRequest {
	return &UpdateTrackingBySlugTrackingNumberRequest{
        sender: sender,
	}
}

func (t *UpdateTrackingBySlugTrackingNumberRequest) BuildQuery(query model.UpdateTrackingBySlugTrackingNumberQuery) *UpdateTrackingBySlugTrackingNumberRequest {
	t.query = query
	return t
}

func (t *UpdateTrackingBySlugTrackingNumberRequest) BuildBody(body model.UpdateTrackingBySlugTrackingNumberRequest) *UpdateTrackingBySlugTrackingNumberRequest {
	t.body = body
	return t
}

func (t *UpdateTrackingBySlugTrackingNumberRequest) BuildHeader(h http.Header) *UpdateTrackingBySlugTrackingNumberRequest {
	t.header = h
	return t
}

func (t *UpdateTrackingBySlugTrackingNumberRequest) BuildPath( slug string, trackingNumber string,) *UpdateTrackingBySlugTrackingNumberRequest {
	t.slug = slug
	t.trackingNumber = trackingNumber
	return t
}

func (t *UpdateTrackingBySlugTrackingNumberRequest) isPathParamValid() error {
    if t.slug == "" {
        return errors.New("path param `slug` can not be empty")
    }
    return nil
    if t.trackingNumber == "" {
        return errors.New("path param `trackingNumber` can not be empty")
    }
    return nil
}

func (t *UpdateTrackingBySlugTrackingNumberRequest) build() (*http.Request, error) {
	q, err := query.Values(t.query)
	if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
    if err := t.isPathParamValid(); err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
    }
    uri := fmt.Sprintf("/tracking/2024-04/trackings/%s/%s?",  t.slug, t.trackingNumber,)  + q.Encode()
    body,err := json.Marshal(t.body)
    if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
    }
    req, err := http.NewRequest("PUT", uri, bytes.NewReader(body))
	if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *UpdateTrackingBySlugTrackingNumberRequest) Execute() ( *model.Tracking , error) {
	req, err := t.build()
	if err != nil {
        return nil, errorx.NewSdkError(errorx.ErrBadRequest, errorx.GetErrorMessage(errorx.ErrBadRequest), err.Error())
	}
	var data model.UpdateTrackingBySlugTrackingNumberResponse
	err = t.sender.Do(req, &data)
	return &data.Tracking,err
}