// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package tracking

import (
	"fmt"
	"github.com/aftership/tracking-sdk-go/v5/component"
	"github.com/aftership/tracking-sdk-go/v5/errorx"
	"github.com/aftership/tracking-sdk-go/v5/service"
	"net/url"
)

type Client struct {
	options               clientOptions
	sender                *component.HttpSender
	Courier               *service.CourierService
	EstimatedDeliveryDate *service.EstimatedDeliveryDateService
	Tracking              *service.TrackingService
}

func New(opts ...ClientOption) (*Client, error) {
	client := &Client{}
	client.options = defaultClientOptions
	for _, opt := range opts {
		opt.apply(&client.options)
	}
	if client.options.timeoutMs < 0 {
		return nil, errorx.NewSdkError(errorx.ErrInvalidOption, fmt.Sprintf("Invalid option: %s", "TIMEOUT"), "")
	}
	if client.options.maxRetry < 0 || client.options.maxRetry > 10 {
		return nil, errorx.NewSdkError(errorx.ErrInvalidOption, fmt.Sprintf("Invalid option: %s", "MAX_RETRY"), "")
	}
	if len(client.options.apiKey) == 0 {
		return nil, errorx.NewSdkError(errorx.ErrInvalidApiKey, errorx.GetErrorMessage(errorx.ErrInvalidApiKey), "")
	}
	if len(client.options.proxy) > 0 {
		_, err := url.Parse(client.options.proxy)
		if err != nil {
			return nil, errorx.NewSdkError(errorx.ErrInvalidOption, fmt.Sprintf("Invalid option: %s", "PROXY"), "")
		}
	}
	client.sender = component.NewHttpSender(
		component.Config{
			Timeout:   client.options.timeoutMs,
			Proxy:     client.options.proxy,
			MaxRetry:  client.options.maxRetry,
			UserAgent: client.options.userAgent,
			Domain:    client.options.domain,
		},
		component.NewAuthenticator(client.options.apiKey, client.options.apiSecret, client.options.authenticationType),
	)
	client.Courier = service.NewCourierService(client.sender)
	client.EstimatedDeliveryDate = service.NewEstimatedDeliveryDateService(client.sender)
	client.Tracking = service.NewTrackingService(client.sender)
	return client, nil
}
