// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package service

import (
	"github.com/aftership/tracking-sdk-go/v8/component"
	"github.com/aftership/tracking-sdk-go/v8/request"
)

type CourierService struct {
	sender *component.HttpSender
}

func NewCourierService(sender *component.HttpSender) *CourierService {
	return &CourierService{sender: sender}
}

func (this *CourierService) GetCouriers() *request.GetCouriersRequest {
	return request.NewGetCouriersRequest(this.sender)
}

func (this *CourierService) DetectCourier() *request.DetectCourierRequest {
	return request.NewDetectCourierRequest(this.sender)
}
