// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package service

import (
	"github.com/aftership/tracking-sdk-go/v8/component"
	"github.com/aftership/tracking-sdk-go/v8/request"
)

type EstimatedDeliveryDateService struct {
	sender *component.HttpSender
}

func NewEstimatedDeliveryDateService(sender *component.HttpSender) *EstimatedDeliveryDateService {
	return &EstimatedDeliveryDateService{sender: sender}
}

func (this *EstimatedDeliveryDateService) Predict() *request.PredictRequest {
	return request.NewPredictRequest(this.sender)
}

func (this *EstimatedDeliveryDateService) PredictBatch() *request.PredictBatchRequest {
	return request.NewPredictBatchRequest(this.sender)
}
