// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package service

import (
    "github.com/AfterShip/tracking-sdk-go/v4/component"
    "github.com/AfterShip/tracking-sdk-go/v4/request"
)

type EstimatedDeliveryDateService struct {
    sender *component.HttpSender
}

func NewEstimatedDeliveryDateService(sender *component.HttpSender) *EstimatedDeliveryDateService {
    return &EstimatedDeliveryDateService{sender: sender}
}

func (this *EstimatedDeliveryDateService) PredictBatch() *request.PredictBatchRequest {
    return request.NewPredictBatchRequest(this.sender)
}

