// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package service

import (
	"github.com/aftership/tracking-sdk-go/v8/component"
	"github.com/aftership/tracking-sdk-go/v8/request"
)

type TrackingService struct {
	sender *component.HttpSender
}

func NewTrackingService(sender *component.HttpSender) *TrackingService {
	return &TrackingService{sender: sender}
}

func (this *TrackingService) UpdateTrackingById() *request.UpdateTrackingByIdRequest {
	return request.NewUpdateTrackingByIdRequest(this.sender)
}

func (this *TrackingService) DeleteTrackingById() *request.DeleteTrackingByIdRequest {
	return request.NewDeleteTrackingByIdRequest(this.sender)
}

func (this *TrackingService) MarkTrackingCompletedById() *request.MarkTrackingCompletedByIdRequest {
	return request.NewMarkTrackingCompletedByIdRequest(this.sender)
}

func (this *TrackingService) GetTrackings() *request.GetTrackingsRequest {
	return request.NewGetTrackingsRequest(this.sender)
}

func (this *TrackingService) CreateTracking() *request.CreateTrackingRequest {
	return request.NewCreateTrackingRequest(this.sender)
}

func (this *TrackingService) RetrackTrackingById() *request.RetrackTrackingByIdRequest {
	return request.NewRetrackTrackingByIdRequest(this.sender)
}

func (this *TrackingService) GetTrackingById() *request.GetTrackingByIdRequest {
	return request.NewGetTrackingByIdRequest(this.sender)
}
