// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package operation

import (
	"bytes"
	"context"
	"encoding/json"
	"github.com/aftership/tracking-sdk-go/v10/component"
	"github.com/aftership/tracking-sdk-go/v10/errorx"
	"github.com/aftership/tracking-sdk-go/v10/model"
	"net/http"
)

type CreateTrackingRequest struct {
	body   model.CreateTrackingRequest
	header http.Header
	sender *component.HttpSender
	ctx    context.Context
	requestBuilder
}

func NewCreateTrackingRequest(sender *component.HttpSender) *CreateTrackingRequest {
	return &CreateTrackingRequest{
		sender: sender,
	}
}

func (t *CreateTrackingRequest) WithContext(ctx context.Context) *CreateTrackingRequest {
	t.ctx = ctx
	return t
}

func (t *CreateTrackingRequest) BuildBody(body model.CreateTrackingRequest) *CreateTrackingRequest {
	t.body = body
	return t
}

func (t *CreateTrackingRequest) BuildHeader(h http.Header) *CreateTrackingRequest {
	t.header = h
	return t
}

func (t *CreateTrackingRequest) build() (*http.Request, error) {
	uri := "/tracking/2025-07/trackings?"
	body, err := json.Marshal(t.body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest("POST", uri, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *CreateTrackingRequest) Execute() (*model.CreateTrackingResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	resp, err := t.sender.Do(t.ctx, req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var data model.Tracking
	err = processResponse(resp, &data)
	if err != nil {
		return nil, err
	}
	var result model.CreateTrackingResponse
	result.Data = data
	result.ResponseHeader = resp.Header
	return &result, nil
}
