// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package operation

import (
	"context"
	"errors"
	"github.com/aftership/tracking-sdk-go/v10/component"
	"github.com/aftership/tracking-sdk-go/v10/errorx"
	"github.com/aftership/tracking-sdk-go/v10/model"
	"net/http"
	"strings"
)

type DeleteTrackingByIdRequest struct {
	id     string
	header http.Header
	sender *component.HttpSender
	ctx    context.Context
	requestBuilder
}

func NewDeleteTrackingByIdRequest(sender *component.HttpSender) *DeleteTrackingByIdRequest {
	return &DeleteTrackingByIdRequest{
		sender: sender,
	}
}

func (t *DeleteTrackingByIdRequest) WithContext(ctx context.Context) *DeleteTrackingByIdRequest {
	t.ctx = ctx
	return t
}

func (t *DeleteTrackingByIdRequest) BuildHeader(h http.Header) *DeleteTrackingByIdRequest {
	t.header = h
	return t
}

func (t *DeleteTrackingByIdRequest) BuildPath(id string) *DeleteTrackingByIdRequest {
	t.id = id
	return t
}

func (t *DeleteTrackingByIdRequest) isPathParamValid() error {
	if t.id == "" {
		return errors.New("path param `id` can not be empty")
	}
	return nil
}

func (t *DeleteTrackingByIdRequest) build() (*http.Request, error) {
	if err := t.isPathParamValid(); err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	uri := "/tracking/2025-07/trackings/{id}?"
	uri = strings.ReplaceAll(uri, "{"+"id"+"}", t.id)

	req, err := http.NewRequest("DELETE", uri, nil)
	if err != nil {
		return nil, err
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *DeleteTrackingByIdRequest) Execute() (*model.DeleteTrackingByIdResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	resp, err := t.sender.Do(t.ctx, req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var data model.Tracking
	err = processResponse(resp, &data)
	if err != nil {
		return nil, err
	}
	var result model.DeleteTrackingByIdResponse
	result.Data = data
	result.ResponseHeader = resp.Header
	return &result, nil
}
