// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package operation

import (
	"context"
	"errors"
	"github.com/aftership/tracking-sdk-go/v12/component"
	"github.com/aftership/tracking-sdk-go/v12/errorx"
	"github.com/aftership/tracking-sdk-go/v12/model"
	"net/http"
	"strings"
)

type DeleteCourierConnectionsByIdRequest struct {
	id     string
	header http.Header
	sender *component.HttpSender
	ctx    context.Context
	requestBuilder
}

func NewDeleteCourierConnectionsByIdRequest(sender *component.HttpSender) *DeleteCourierConnectionsByIdRequest {
	return &DeleteCourierConnectionsByIdRequest{
		sender: sender,
	}
}

func (t *DeleteCourierConnectionsByIdRequest) WithContext(ctx context.Context) *DeleteCourierConnectionsByIdRequest {
	t.ctx = ctx
	return t
}

func (t *DeleteCourierConnectionsByIdRequest) BuildHeader(h http.Header) *DeleteCourierConnectionsByIdRequest {
	t.header = h
	return t
}

func (t *DeleteCourierConnectionsByIdRequest) BuildPath(id string) *DeleteCourierConnectionsByIdRequest {
	t.id = id
	return t
}

func (t *DeleteCourierConnectionsByIdRequest) isPathParamValid() error {
	if t.id == "" {
		return errors.New("path param `id` can not be empty")
	}
	return nil
}

func (t *DeleteCourierConnectionsByIdRequest) build() (*http.Request, error) {
	if err := t.isPathParamValid(); err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	uri := "/tracking/2026-07/courier-connections/{id}?"
	uri = strings.ReplaceAll(uri, "{"+"id"+"}", t.id)

	req, err := http.NewRequest("DELETE", uri, nil)
	if err != nil {
		return nil, err
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *DeleteCourierConnectionsByIdRequest) Execute() (*model.DeleteCourierConnectionsByIdResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	resp, err := t.sender.Do(t.ctx, req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var data model.CourierConnection
	err = processResponse(resp, &data)
	if err != nil {
		return nil, err
	}
	var result model.DeleteCourierConnectionsByIdResponse
	result.Data = data
	result.ResponseHeader = resp.Header
	return &result, nil
}
