// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package operation

import (
	"bytes"
	"context"
	"encoding/json"
	"github.com/aftership/tracking-sdk-go/v11/component"
	"github.com/aftership/tracking-sdk-go/v11/errorx"
	"github.com/aftership/tracking-sdk-go/v11/model"
	"net/http"
)

type DetectCourierRequest struct {
	body   model.DetectCourierRequest
	header http.Header
	sender *component.HttpSender
	ctx    context.Context
	requestBuilder
}

func NewDetectCourierRequest(sender *component.HttpSender) *DetectCourierRequest {
	return &DetectCourierRequest{
		sender: sender,
	}
}

func (t *DetectCourierRequest) WithContext(ctx context.Context) *DetectCourierRequest {
	t.ctx = ctx
	return t
}

func (t *DetectCourierRequest) BuildBody(body model.DetectCourierRequest) *DetectCourierRequest {
	t.body = body
	return t
}

func (t *DetectCourierRequest) BuildHeader(h http.Header) *DetectCourierRequest {
	t.header = h
	return t
}

func (t *DetectCourierRequest) build() (*http.Request, error) {
	uri := "/tracking/2026-01/couriers/detect?"
	body, err := json.Marshal(t.body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest("POST", uri, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *DetectCourierRequest) Execute() (*model.DetectCourierResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	resp, err := t.sender.Do(t.ctx, req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var data model.DetectCourierResponseData
	err = processResponse(resp, &data)
	if err != nil {
		return nil, err
	}
	var result model.DetectCourierResponse
	result.Data = data
	result.ResponseHeader = resp.Header
	return &result, nil
}
