// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package operation

import (
	"context"
	"errors"
	"github.com/aftership/tracking-sdk-go/v10/component"
	"github.com/aftership/tracking-sdk-go/v10/errorx"
	"github.com/aftership/tracking-sdk-go/v10/model"
	"github.com/google/go-querystring/query"
	"net/http"
	"strings"
)

// GetTrackingByIdQuery
type GetTrackingByIdQuery struct {
	// Fields List of fields to include in the response. Use comma for multiple values. Fields to include: `destination_postal_code`, `tracking_ship_date`, `tracking_account_number`, `tracking_key`, `origin_country_region`, `destination_country_region`, `destination_state`, `title`, `order_id`, `tag`, `checkpoints`
	Fields *string `url:"fields,omitempty"`
	// Lang Translate checkpoint messages from the carrier’s provided language to the target language. Supported target languages include:</br>&nbsp;&nbsp;&nbsp;&nbsp;- English (en)</br>&nbsp;&nbsp;&nbsp;&nbsp;- French (fr)</br>&nbsp;&nbsp;&nbsp;&nbsp;- French Canadian (fr-CA)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Arabic (ar)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Bulgarian (bg)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Catalan (ca)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Croatian (hr)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Czech (cs)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Danish (da)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Dutch (nl)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Estonian (et)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Filipino (tl)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Finnish (fi)</br>&nbsp;&nbsp;&nbsp;&nbsp;- German (de)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Greek (el)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Hebrew (he)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Hindi (hi)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Hungarian (hu)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Indonesian (id)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Italian (it)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Japanese (ja)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Korean (ko)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Latvian (lv)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Lithuanian (lt)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Malay (ms)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Polish (pl)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Portuguese (pt)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Romanian (ro)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Russian (ru)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Serbian (sr)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Slovak (sk)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Slovenian (sl)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Spanish (es)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Swedish (sv)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Thai (th)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Turkish (tr)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Ukrainian (uk)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Vietnamese (vi)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Simplified Chinese (zh-Hans)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Traditional Chinese (zh-Hant)</br>&nbsp;&nbsp;&nbsp;&nbsp;- Norwegian (nb)</br>
	Lang *string `url:"lang,omitempty"`
}

func NewGetTrackingByIdQuery() GetTrackingByIdQuery {
	return GetTrackingByIdQuery{}
}

func (query *GetTrackingByIdQuery) SetFields(fields string) *GetTrackingByIdQuery {
	query.Fields = &fields
	return query
}

func (query *GetTrackingByIdQuery) SetLang(lang string) *GetTrackingByIdQuery {
	query.Lang = &lang
	return query
}

type GetTrackingByIdRequest struct {
	id     string
	query  GetTrackingByIdQuery
	header http.Header
	sender *component.HttpSender
	ctx    context.Context
	requestBuilder
}

func NewGetTrackingByIdRequest(sender *component.HttpSender) *GetTrackingByIdRequest {
	return &GetTrackingByIdRequest{
		sender: sender,
	}
}

func (t *GetTrackingByIdRequest) WithContext(ctx context.Context) *GetTrackingByIdRequest {
	t.ctx = ctx
	return t
}

func (t *GetTrackingByIdRequest) BuildQuery(query GetTrackingByIdQuery) *GetTrackingByIdRequest {
	t.query = query
	return t
}

func (t *GetTrackingByIdRequest) BuildHeader(h http.Header) *GetTrackingByIdRequest {
	t.header = h
	return t
}

func (t *GetTrackingByIdRequest) BuildPath(id string) *GetTrackingByIdRequest {
	t.id = id
	return t
}

func (t *GetTrackingByIdRequest) isPathParamValid() error {
	if t.id == "" {
		return errors.New("path param `id` can not be empty")
	}
	return nil
}

func (t *GetTrackingByIdRequest) build() (*http.Request, error) {
	q, err := query.Values(t.query)
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	if err := t.isPathParamValid(); err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	uri := "/tracking/2025-07/trackings/{id}?"
	uri = strings.ReplaceAll(uri, "{"+"id"+"}", t.id)
	uri = uri + q.Encode()
	req, err := http.NewRequest("GET", uri, nil)
	if err != nil {
		return nil, err
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *GetTrackingByIdRequest) Execute() (*model.GetTrackingByIdResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	resp, err := t.sender.Do(t.ctx, req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var data model.Tracking
	err = processResponse(resp, &data)
	if err != nil {
		return nil, err
	}
	var result model.GetTrackingByIdResponse
	result.Data = data
	result.ResponseHeader = resp.Header
	return &result, nil
}
