// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package operation

import (
	"context"
	"github.com/aftership/tracking-sdk-go/v12/component"
	"github.com/aftership/tracking-sdk-go/v12/errorx"
	"github.com/aftership/tracking-sdk-go/v12/model"
	"github.com/google/go-querystring/query"
	"net/http"
)

// GetCourierConnectionsQuery
type GetCourierConnectionsQuery struct {
	// CourierSlug Unique courier code.(Example: dhl-api)
	CourierSlug *string `url:"courier_slug,omitempty"`
	// Cursor A string representing the cursor value for the current page of results.
	Cursor *string `url:"cursor,omitempty"`
	// Limit Number of courier connections each page contain. (Default: 100, Max: 200)
	Limit *string `url:"limit,omitempty"`
}

func NewGetCourierConnectionsQuery() GetCourierConnectionsQuery {
	return GetCourierConnectionsQuery{}
}

func (query *GetCourierConnectionsQuery) SetCourierSlug(courierSlug string) *GetCourierConnectionsQuery {
	query.CourierSlug = &courierSlug
	return query
}

func (query *GetCourierConnectionsQuery) SetCursor(cursor string) *GetCourierConnectionsQuery {
	query.Cursor = &cursor
	return query
}

func (query *GetCourierConnectionsQuery) SetLimit(limit string) *GetCourierConnectionsQuery {
	query.Limit = &limit
	return query
}

type GetCourierConnectionsRequest struct {
	query  GetCourierConnectionsQuery
	header http.Header
	sender *component.HttpSender
	ctx    context.Context
	requestBuilder
}

func NewGetCourierConnectionsRequest(sender *component.HttpSender) *GetCourierConnectionsRequest {
	return &GetCourierConnectionsRequest{
		sender: sender,
	}
}

func (t *GetCourierConnectionsRequest) WithContext(ctx context.Context) *GetCourierConnectionsRequest {
	t.ctx = ctx
	return t
}

func (t *GetCourierConnectionsRequest) BuildQuery(query GetCourierConnectionsQuery) *GetCourierConnectionsRequest {
	t.query = query
	return t
}

func (t *GetCourierConnectionsRequest) BuildHeader(h http.Header) *GetCourierConnectionsRequest {
	t.header = h
	return t
}

func (t *GetCourierConnectionsRequest) build() (*http.Request, error) {
	q, err := query.Values(t.query)
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	uri := "/tracking/2026-07/courier-connections?" + q.Encode()
	req, err := http.NewRequest("GET", uri, nil)
	if err != nil {
		return nil, err
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *GetCourierConnectionsRequest) Execute() (*model.GetCourierConnectionsResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	resp, err := t.sender.Do(t.ctx, req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var data model.GetCourierConnectionsResponseData
	err = processResponse(resp, &data)
	if err != nil {
		return nil, err
	}
	var result model.GetCourierConnectionsResponse
	result.Data = data
	result.ResponseHeader = resp.Header
	return &result, nil
}
