// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package operation

import (
	"context"
	"github.com/aftership/tracking-sdk-go/v11/component"
	"github.com/aftership/tracking-sdk-go/v11/errorx"
	"github.com/aftership/tracking-sdk-go/v11/model"
	"github.com/google/go-querystring/query"
	"net/http"
)

// GetTrackingsQuery
type GetTrackingsQuery struct {
	// Cursor A string representing the cursor value for the current page of results.
	Cursor *string `url:"cursor,omitempty"`
	// Limit Number of trackings each page contain. (Default: 100, Max: 200)
	Limit *int `url:"limit,omitempty"`
	// Keyword Search the content of the tracking record fields: `tracking_number`, `title`, `order_id`, `customers[x].name`, `custom_fields`, `customers[x].email`, `customers[x].phone_number`
	Keyword *string `url:"keyword,omitempty"`
	// TrackingNumbers Tracking number of shipments. Use comma to separate multiple values (Example: RA123456789US,LE123456789US). Supports up to 50 tracking numbers.
	TrackingNumbers *string `url:"tracking_numbers,omitempty"`
	// Slug Unique courier code Use comma for multiple values. (Example: dhl,ups,usps)
	Slug *string `url:"slug,omitempty"`
	// TransitTime Total delivery time in days.- When the shipment is delivered: Transit time = Delivered date - Picked up date- When the shipment is not delivered: Transit time = Current date - Picked up dateValue as `null` for the shipment without pickup date.
	TransitTime *int `url:"transit_time,omitempty"`
	// Origin Origin country/region of trackings. Use ISO Alpha-3 (three letters). Use comma for multiple values. (Example: USA,HKG)
	Origin *string `url:"origin,omitempty"`
	// Destination Destination country/region of trackings. Use ISO Alpha-3 (three letters). Use comma for multiple values. (Example: USA,HKG)
	Destination *string `url:"destination,omitempty"`
	// Tag Current status of tracking. Values include `Pending`, `InfoReceived`, `InTransit`, `OutForDelivery`, `AttemptFail`, `Delivered`, `AvailableForPickup`, `Exception`, `Expired` (See tag definition)
	Tag *string `url:"tag,omitempty"`
	// CreatedAtMin Start date and time of trackings created. AfterShip only stores data of 120 days. Please make sure the value of the parameter is properly escaped in
	CreatedAtMin *string `url:"created_at_min,omitempty"`
	// CreatedAtMax End date and time of trackings created. Please make sure the value of the parameter is properly escaped in
	CreatedAtMax *string `url:"created_at_max,omitempty"`
	// UpdatedAtMin Start date and time of trackings updated. Please make sure the value of the parameter is properly escaped in
	UpdatedAtMin *string `url:"updated_at_min,omitempty"`
	// UpdatedAtMax End date and time of trackings updated. Please make sure the value of the parameter is properly escaped in
	UpdatedAtMax *string `url:"updated_at_max,omitempty"`
	// Fields List of fields to include in the response. Use comma for multiple values. Available options: `title`, `order_id`, `tag`, `checkpoints`. Example: `title,order_id`
	Fields *string `url:"fields,omitempty"`
	// ReturnToSender Select return to sender, the value should be `true` or `false`, with optional comma separated.
	ReturnToSender *string `url:"return_to_sender,omitempty"`
	// CourierDestinationCountryRegion Destination country/region of trackings returned by courier. Use ISO Alpha-3 (three letters). Use comma for multiple values. (Example: USA,HKG)
	CourierDestinationCountryRegion *string `url:"courier_destination_country_region,omitempty"`
	// ShipmentTags Tags you added to your shipments to help categorize and filter them easily. Use a comma to separate multiple values (Example: a,b)
	ShipmentTags *string `url:"shipment_tags,omitempty"`
	// OrderId A globally-unique identifier for the order. Use comma for multiple values.(Example: 6845a095a27a4caeb27487806f058add,4845a095a27a4caeb27487806f058abc)
	OrderId *string `url:"order_id,omitempty"`
}

func NewGetTrackingsQuery() GetTrackingsQuery {
	return GetTrackingsQuery{}
}

func (query *GetTrackingsQuery) SetCursor(cursor string) *GetTrackingsQuery {
	query.Cursor = &cursor
	return query
}

func (query *GetTrackingsQuery) SetLimit(limit int) *GetTrackingsQuery {
	query.Limit = &limit
	return query
}

func (query *GetTrackingsQuery) SetKeyword(keyword string) *GetTrackingsQuery {
	query.Keyword = &keyword
	return query
}

func (query *GetTrackingsQuery) SetTrackingNumbers(trackingNumbers string) *GetTrackingsQuery {
	query.TrackingNumbers = &trackingNumbers
	return query
}

func (query *GetTrackingsQuery) SetSlug(slug string) *GetTrackingsQuery {
	query.Slug = &slug
	return query
}

func (query *GetTrackingsQuery) SetTransitTime(transitTime int) *GetTrackingsQuery {
	query.TransitTime = &transitTime
	return query
}

func (query *GetTrackingsQuery) SetOrigin(origin string) *GetTrackingsQuery {
	query.Origin = &origin
	return query
}

func (query *GetTrackingsQuery) SetDestination(destination string) *GetTrackingsQuery {
	query.Destination = &destination
	return query
}

func (query *GetTrackingsQuery) SetTag(tag string) *GetTrackingsQuery {
	query.Tag = &tag
	return query
}

func (query *GetTrackingsQuery) SetCreatedAtMin(createdAtMin string) *GetTrackingsQuery {
	query.CreatedAtMin = &createdAtMin
	return query
}

func (query *GetTrackingsQuery) SetCreatedAtMax(createdAtMax string) *GetTrackingsQuery {
	query.CreatedAtMax = &createdAtMax
	return query
}

func (query *GetTrackingsQuery) SetUpdatedAtMin(updatedAtMin string) *GetTrackingsQuery {
	query.UpdatedAtMin = &updatedAtMin
	return query
}

func (query *GetTrackingsQuery) SetUpdatedAtMax(updatedAtMax string) *GetTrackingsQuery {
	query.UpdatedAtMax = &updatedAtMax
	return query
}

func (query *GetTrackingsQuery) SetFields(fields string) *GetTrackingsQuery {
	query.Fields = &fields
	return query
}

func (query *GetTrackingsQuery) SetReturnToSender(returnToSender string) *GetTrackingsQuery {
	query.ReturnToSender = &returnToSender
	return query
}

func (query *GetTrackingsQuery) SetCourierDestinationCountryRegion(courierDestinationCountryRegion string) *GetTrackingsQuery {
	query.CourierDestinationCountryRegion = &courierDestinationCountryRegion
	return query
}

func (query *GetTrackingsQuery) SetShipmentTags(shipmentTags string) *GetTrackingsQuery {
	query.ShipmentTags = &shipmentTags
	return query
}

func (query *GetTrackingsQuery) SetOrderId(orderId string) *GetTrackingsQuery {
	query.OrderId = &orderId
	return query
}

type GetTrackingsRequest struct {
	query  GetTrackingsQuery
	header http.Header
	sender *component.HttpSender
	ctx    context.Context
	requestBuilder
}

func NewGetTrackingsRequest(sender *component.HttpSender) *GetTrackingsRequest {
	return &GetTrackingsRequest{
		sender: sender,
	}
}

func (t *GetTrackingsRequest) WithContext(ctx context.Context) *GetTrackingsRequest {
	t.ctx = ctx
	return t
}

func (t *GetTrackingsRequest) BuildQuery(query GetTrackingsQuery) *GetTrackingsRequest {
	t.query = query
	return t
}

func (t *GetTrackingsRequest) BuildHeader(h http.Header) *GetTrackingsRequest {
	t.header = h
	return t
}

func (t *GetTrackingsRequest) build() (*http.Request, error) {
	q, err := query.Values(t.query)
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	uri := "/tracking/2026-01/trackings?" + q.Encode()
	req, err := http.NewRequest("GET", uri, nil)
	if err != nil {
		return nil, err
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *GetTrackingsRequest) Execute() (*model.GetTrackingsResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	resp, err := t.sender.Do(t.ctx, req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var data model.GetTrackingsResponseData
	err = processResponse(resp, &data)
	if err != nil {
		return nil, err
	}
	var result model.GetTrackingsResponse
	result.Data = data
	result.ResponseHeader = resp.Header
	return &result, nil
}
