// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package operation

import (
	"context"
	"github.com/aftership/tracking-sdk-go/v10/component"
	"github.com/aftership/tracking-sdk-go/v10/errorx"
	"github.com/aftership/tracking-sdk-go/v10/model"
	"github.com/google/go-querystring/query"
	"net/http"
)

// GetCouriersQuery
type GetCouriersQuery struct {
	// Active get user activated couriers
	Active *bool `url:"active,omitempty"`
	// Slug Unique courier code Use comma for multiple values. (Example: dhl,ups,usps)
	Slug *string `url:"slug,omitempty"`
}

func NewGetCouriersQuery() GetCouriersQuery {
	return GetCouriersQuery{}
}

func (query *GetCouriersQuery) SetActive(active bool) *GetCouriersQuery {
	query.Active = &active
	return query
}

func (query *GetCouriersQuery) SetSlug(slug string) *GetCouriersQuery {
	query.Slug = &slug
	return query
}

type GetCouriersRequest struct {
	query  GetCouriersQuery
	header http.Header
	sender *component.HttpSender
	ctx    context.Context
	requestBuilder
}

func NewGetCouriersRequest(sender *component.HttpSender) *GetCouriersRequest {
	return &GetCouriersRequest{
		sender: sender,
	}
}

func (t *GetCouriersRequest) WithContext(ctx context.Context) *GetCouriersRequest {
	t.ctx = ctx
	return t
}

func (t *GetCouriersRequest) BuildQuery(query GetCouriersQuery) *GetCouriersRequest {
	t.query = query
	return t
}

func (t *GetCouriersRequest) BuildHeader(h http.Header) *GetCouriersRequest {
	t.header = h
	return t
}

func (t *GetCouriersRequest) build() (*http.Request, error) {
	q, err := query.Values(t.query)
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	uri := "/tracking/2025-07/couriers?" + q.Encode()
	req, err := http.NewRequest("GET", uri, nil)
	if err != nil {
		return nil, err
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *GetCouriersRequest) Execute() (*model.GetCouriersResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	resp, err := t.sender.Do(t.ctx, req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var data model.GetCouriersResponseData
	err = processResponse(resp, &data)
	if err != nil {
		return nil, err
	}
	var result model.GetCouriersResponse
	result.Data = data
	result.ResponseHeader = resp.Header
	return &result, nil
}
