// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package operation

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"github.com/aftership/tracking-sdk-go/v10/component"
	"github.com/aftership/tracking-sdk-go/v10/errorx"
	"github.com/aftership/tracking-sdk-go/v10/model"
	"net/http"
	"strings"
)

type MarkTrackingCompletedByIdRequest struct {
	id     string
	body   model.MarkTrackingCompletedByIdRequest
	header http.Header
	sender *component.HttpSender
	ctx    context.Context
	requestBuilder
}

func NewMarkTrackingCompletedByIdRequest(sender *component.HttpSender) *MarkTrackingCompletedByIdRequest {
	return &MarkTrackingCompletedByIdRequest{
		sender: sender,
	}
}

func (t *MarkTrackingCompletedByIdRequest) WithContext(ctx context.Context) *MarkTrackingCompletedByIdRequest {
	t.ctx = ctx
	return t
}

func (t *MarkTrackingCompletedByIdRequest) BuildBody(body model.MarkTrackingCompletedByIdRequest) *MarkTrackingCompletedByIdRequest {
	t.body = body
	return t
}

func (t *MarkTrackingCompletedByIdRequest) BuildHeader(h http.Header) *MarkTrackingCompletedByIdRequest {
	t.header = h
	return t
}

func (t *MarkTrackingCompletedByIdRequest) BuildPath(id string) *MarkTrackingCompletedByIdRequest {
	t.id = id
	return t
}

func (t *MarkTrackingCompletedByIdRequest) isPathParamValid() error {
	if t.id == "" {
		return errors.New("path param `id` can not be empty")
	}
	return nil
}

func (t *MarkTrackingCompletedByIdRequest) build() (*http.Request, error) {
	if err := t.isPathParamValid(); err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	uri := "/tracking/2025-07/trackings/{id}/mark-as-completed?"
	uri = strings.ReplaceAll(uri, "{"+"id"+"}", t.id)

	body, err := json.Marshal(t.body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest("POST", uri, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *MarkTrackingCompletedByIdRequest) Execute() (*model.MarkTrackingCompletedByIdResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	resp, err := t.sender.Do(t.ctx, req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var data model.Tracking
	err = processResponse(resp, &data)
	if err != nil {
		return nil, err
	}
	var result model.MarkTrackingCompletedByIdResponse
	result.Data = data
	result.ResponseHeader = resp.Header
	return &result, nil
}
