// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package operation

import (
	"bytes"
	"context"
	"encoding/json"
	"github.com/aftership/tracking-sdk-go/v11/component"
	"github.com/aftership/tracking-sdk-go/v11/errorx"
	"github.com/aftership/tracking-sdk-go/v11/model"
	"net/http"
)

type PostCourierConnectionsRequest struct {
	body   model.PostCourierConnectionsRequest
	header http.Header
	sender *component.HttpSender
	ctx    context.Context
	requestBuilder
}

func NewPostCourierConnectionsRequest(sender *component.HttpSender) *PostCourierConnectionsRequest {
	return &PostCourierConnectionsRequest{
		sender: sender,
	}
}

func (t *PostCourierConnectionsRequest) WithContext(ctx context.Context) *PostCourierConnectionsRequest {
	t.ctx = ctx
	return t
}

func (t *PostCourierConnectionsRequest) BuildBody(body model.PostCourierConnectionsRequest) *PostCourierConnectionsRequest {
	t.body = body
	return t
}

func (t *PostCourierConnectionsRequest) BuildHeader(h http.Header) *PostCourierConnectionsRequest {
	t.header = h
	return t
}

func (t *PostCourierConnectionsRequest) build() (*http.Request, error) {
	uri := "/tracking/2026-01/courier-connections?"
	body, err := json.Marshal(t.body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest("POST", uri, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *PostCourierConnectionsRequest) Execute() (*model.PostCourierConnectionsResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	resp, err := t.sender.Do(t.ctx, req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var data model.CourierConnection
	err = processResponse(resp, &data)
	if err != nil {
		return nil, err
	}
	var result model.PostCourierConnectionsResponse
	result.Data = data
	result.ResponseHeader = resp.Header
	return &result, nil
}
