// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package operation

import (
	"bytes"
	"context"
	"encoding/json"
	"github.com/aftership/tracking-sdk-go/v12/component"
	"github.com/aftership/tracking-sdk-go/v12/errorx"
	"github.com/aftership/tracking-sdk-go/v12/model"
	"net/http"
)

type PredictBatchRequest struct {
	body   model.PredictBatchRequest
	header http.Header
	sender *component.HttpSender
	ctx    context.Context
	requestBuilder
}

func NewPredictBatchRequest(sender *component.HttpSender) *PredictBatchRequest {
	return &PredictBatchRequest{
		sender: sender,
	}
}

func (t *PredictBatchRequest) WithContext(ctx context.Context) *PredictBatchRequest {
	t.ctx = ctx
	return t
}

func (t *PredictBatchRequest) BuildBody(body model.PredictBatchRequest) *PredictBatchRequest {
	t.body = body
	return t
}

func (t *PredictBatchRequest) BuildHeader(h http.Header) *PredictBatchRequest {
	t.header = h
	return t
}

func (t *PredictBatchRequest) build() (*http.Request, error) {
	uri := "/tracking/2026-07/estimated-delivery-date/predict-batch?"
	body, err := json.Marshal(t.body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest("POST", uri, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *PredictBatchRequest) Execute() (*model.PredictBatchResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	resp, err := t.sender.Do(t.ctx, req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var data model.PredictBatchResponseData
	err = processResponse(resp, &data)
	if err != nil {
		return nil, err
	}
	var result model.PredictBatchResponse
	result.Data = data
	result.ResponseHeader = resp.Header
	return &result, nil
}
