// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package operation

import (
	"bytes"
	"context"
	"encoding/json"
	"github.com/aftership/tracking-sdk-go/v11/component"
	"github.com/aftership/tracking-sdk-go/v11/errorx"
	"github.com/aftership/tracking-sdk-go/v11/model"
	"net/http"
)

type PredictRequest struct {
	body   model.EstimatedDeliveryDateRequest
	header http.Header
	sender *component.HttpSender
	ctx    context.Context
	requestBuilder
}

func NewPredictRequest(sender *component.HttpSender) *PredictRequest {
	return &PredictRequest{
		sender: sender,
	}
}

func (t *PredictRequest) WithContext(ctx context.Context) *PredictRequest {
	t.ctx = ctx
	return t
}

func (t *PredictRequest) BuildBody(body model.EstimatedDeliveryDateRequest) *PredictRequest {
	t.body = body
	return t
}

func (t *PredictRequest) BuildHeader(h http.Header) *PredictRequest {
	t.header = h
	return t
}

func (t *PredictRequest) build() (*http.Request, error) {
	uri := "/tracking/2026-01/estimated-delivery-date/predict?"
	body, err := json.Marshal(t.body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest("POST", uri, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *PredictRequest) Execute() (*model.PredictResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	resp, err := t.sender.Do(t.ctx, req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var data model.EstimatedDeliveryDateResponse
	err = processResponse(resp, &data)
	if err != nil {
		return nil, err
	}
	var result model.PredictResponse
	result.Data = data
	result.ResponseHeader = resp.Header
	return &result, nil
}
