// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package operation

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"github.com/aftership/tracking-sdk-go/v11/component"
	"github.com/aftership/tracking-sdk-go/v11/errorx"
	"github.com/aftership/tracking-sdk-go/v11/model"
	"net/http"
	"strings"
)

type PutCourierConnectionsByIdRequest struct {
	id     string
	body   model.PutCourierConnectionsByIdRequest
	header http.Header
	sender *component.HttpSender
	ctx    context.Context
	requestBuilder
}

func NewPutCourierConnectionsByIdRequest(sender *component.HttpSender) *PutCourierConnectionsByIdRequest {
	return &PutCourierConnectionsByIdRequest{
		sender: sender,
	}
}

func (t *PutCourierConnectionsByIdRequest) WithContext(ctx context.Context) *PutCourierConnectionsByIdRequest {
	t.ctx = ctx
	return t
}

func (t *PutCourierConnectionsByIdRequest) BuildBody(body model.PutCourierConnectionsByIdRequest) *PutCourierConnectionsByIdRequest {
	t.body = body
	return t
}

func (t *PutCourierConnectionsByIdRequest) BuildHeader(h http.Header) *PutCourierConnectionsByIdRequest {
	t.header = h
	return t
}

func (t *PutCourierConnectionsByIdRequest) BuildPath(id string) *PutCourierConnectionsByIdRequest {
	t.id = id
	return t
}

func (t *PutCourierConnectionsByIdRequest) isPathParamValid() error {
	if t.id == "" {
		return errors.New("path param `id` can not be empty")
	}
	return nil
}

func (t *PutCourierConnectionsByIdRequest) build() (*http.Request, error) {
	if err := t.isPathParamValid(); err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	uri := "/tracking/2026-01/courier-connections/{id}?"
	uri = strings.ReplaceAll(uri, "{"+"id"+"}", t.id)

	body, err := json.Marshal(t.body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest("PATCH", uri, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *PutCourierConnectionsByIdRequest) Execute() (*model.PutCourierConnectionsByIdResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	resp, err := t.sender.Do(t.ctx, req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var data model.CourierConnection
	err = processResponse(resp, &data)
	if err != nil {
		return nil, err
	}
	var result model.PutCourierConnectionsByIdResponse
	result.Data = data
	result.ResponseHeader = resp.Header
	return &result, nil
}
