// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package operation

import (
	"encoding/json"
	"io"
	"net/http"

	"github.com/aftership/tracking-sdk-go/v10/errorx"
)

type response struct {
	Data interface{} `json:"data,omitempty"`
	Meta meta        `json:"meta,omitempty"`
}

type meta struct {
	Code    int    `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
	Type    string `json:"type,omitempty"`
}

func processResponse(resp *http.Response, data interface{}) error {
	bytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return errorx.NewSdkError(errorx.ErrUnknownError, err.Error())
	}

	var respBody response
	respBody.Data = data
	err = json.Unmarshal(bytes, &respBody)
	if err != nil {
		return errorx.NewSdkError(errorx.ErrUnknownError, err.Error())
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return errorx.NewApiError(
			respBody.Meta.Code,
			resp.StatusCode,
			respBody.Meta.Message,
			string(bytes),
			resp.Header)
	}

	return nil
}
