// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package operation

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"github.com/aftership/tracking-sdk-go/v12/component"
	"github.com/aftership/tracking-sdk-go/v12/errorx"
	"github.com/aftership/tracking-sdk-go/v12/model"
	"net/http"
	"strings"
)

type UpdateTrackingByIdRequest struct {
	id     string
	body   model.UpdateTrackingByIdRequest
	header http.Header
	sender *component.HttpSender
	ctx    context.Context
	requestBuilder
}

func NewUpdateTrackingByIdRequest(sender *component.HttpSender) *UpdateTrackingByIdRequest {
	return &UpdateTrackingByIdRequest{
		sender: sender,
	}
}

func (t *UpdateTrackingByIdRequest) WithContext(ctx context.Context) *UpdateTrackingByIdRequest {
	t.ctx = ctx
	return t
}

func (t *UpdateTrackingByIdRequest) BuildBody(body model.UpdateTrackingByIdRequest) *UpdateTrackingByIdRequest {
	t.body = body
	return t
}

func (t *UpdateTrackingByIdRequest) BuildHeader(h http.Header) *UpdateTrackingByIdRequest {
	t.header = h
	return t
}

func (t *UpdateTrackingByIdRequest) BuildPath(id string) *UpdateTrackingByIdRequest {
	t.id = id
	return t
}

func (t *UpdateTrackingByIdRequest) isPathParamValid() error {
	if t.id == "" {
		return errors.New("path param `id` can not be empty")
	}
	return nil
}

func (t *UpdateTrackingByIdRequest) build() (*http.Request, error) {
	if err := t.isPathParamValid(); err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	uri := "/tracking/2026-07/trackings/{id}?"
	uri = strings.ReplaceAll(uri, "{"+"id"+"}", t.id)

	body, err := json.Marshal(t.body)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequest("PUT", uri, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	t.requestBuilder.appendHeader(t.header, req)
	return req, nil
}

func (t *UpdateTrackingByIdRequest) Execute() (*model.UpdateTrackingByIdResponse, error) {
	req, err := t.build()
	if err != nil {
		return nil, errorx.NewSdkError(errorx.ErrBadRequest, err.Error())
	}
	resp, err := t.sender.Do(t.ctx, req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var data model.Tracking
	err = processResponse(resp, &data)
	if err != nil {
		return nil, err
	}
	var result model.UpdateTrackingByIdResponse
	result.Data = data
	result.ResponseHeader = resp.Header
	return &result, nil
}
