// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package errorx

import (
	"encoding/json"
)

type APIError struct {
	Code       int    `json:"code"`
	MetaCode   int   `json:"meta_code"`
	StatusCode int    `json:"status_code"`
	Message    string `json:"message"`
	Response   string `json:"response"`
}

func NewApiError(code, status int, msg, resp string) *APIError {
	return &APIError{
        Code:       GetErrorCode(code),
        MetaCode:   code,
		StatusCode: status,
		Message:    msg,
		Response:   resp,
	}
}

func NewSdkError(code int, msg string, detail string) *APIError {
	return &APIError{
		Code:       code,
		MetaCode:   0,
		StatusCode: 0,
		Message:    msg,
		Response:   detail,
	}
}

func (e *APIError) Error() string {
	ret, _ := json.Marshal(e)
	return string(ret)
}
