// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package errorx

import (
	"encoding/json"
	"net/http"
)

type APIError struct {
	Code       string      `json:"code"`
	MetaCode   int         `json:"meta_code"`
	StatusCode int         `json:"status_code"`
	Message    string      `json:"message"`
	Response   string      `json:"response"`
	Header     http.Header `json:"response_header"`
}

func NewApiError(metaCode, statusCode int, msg, resp string, header http.Header) *APIError {
	return &APIError{
		Code:       GetErrorCode(metaCode, statusCode),
		MetaCode:   metaCode,
		StatusCode: statusCode,
		Message:    msg,
		Response:   resp,
		Header:     header,
	}
}

func NewSdkError(code string, msg string) *APIError {
	return &APIError{
		Code:    code,
		Message: msg,
	}
}

func (e *APIError) Error() string {
	ret, _ := json.Marshal(e)
	return string(ret)
}
