// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package errorx

import (
	"encoding/json"
	"net/http"
)

type APIError struct {
	Code       int         `json:"code"`
	MetaCode   int         `json:"meta_code"`
	StatusCode int         `json:"status_code"`
	Message    string      `json:"message"`
	Response   string      `json:"response"`
	Header     http.Header `json:"response_header"`
}

func NewApiError(code, status int, msg, resp string, header http.Header) *APIError {
	return &APIError{
		Code:       GetErrorCode(code),
		MetaCode:   code,
		StatusCode: status,
		Message:    msg,
		Response:   resp,
		Header:     header,
	}
}

func NewSdkError(code int, msg string, detail string) *APIError {
	return &APIError{
		Code:       code,
		MetaCode:   0,
		StatusCode: 0,
		Message:    msg,
		Response:   detail,
	}
}

func (e *APIError) Error() string {
	ret, _ := json.Marshal(e)
	return string(ret)
}
