// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package errorx

const (
	ErrInvalidApiKey                 = "INVALID_API_KEY"
	ErrInvalidOption                 = "INVALID_OPTION"
	ErrBadRequest                    = "BAD_REQUEST"
	ErrRateLimitExceed               = "RATE_LIMIT_EXCEED"
	ErrTimedOut                      = "TIMED_OUT"
	ErrUnknownError                  = "UNKNOWN_ERROR"
	ErrInvalidRequest                = "INVALID_REQUEST"
	ErrInvalidJson                   = "INVALID_JSON"
	ErrTrackingAlreadyExist          = "TRACKING_ALREADY_EXIST"
	ErrTrackingDoesNotExist          = "TRACKING_DOES_NOT_EXIST"
	ErrTrackingNumberInvalid         = "TRACKING_NUMBER_INVALID"
	ErrTrackingRequired              = "TRACKING_REQUIRED"
	ErrTrackingNumberRequired        = "TRACKING_NUMBER_REQUIRED"
	ErrValueInvalid                  = "VALUE_INVALID"
	ErrValueRequired                 = "VALUE_REQUIRED"
	ErrSlugInvalid                   = "SLUG_INVALID"
	ErrMissingOrInvalidRequiredField = "MISSING_OR_INVALID_REQUIRED_FIELD"
	ErrBadCourier                    = "BAD_COURIER"
	ErrInactiveRetrackNotAllowed     = "INACTIVE_RETRACK_NOT_ALLOWED"
	ErrNotificationRequired          = "NOTIFICATION_REQUIRED"
	ErrIdInvalid                     = "ID_INVALID"
	ErrRetrackOnceAllowed            = "RETRACK_ONCE_ALLOWED"
	ErrTrackingNumberFormatInvalid   = "TRACKING_NUMBER_FORMAT_INVALID"
	ErrApiKeyInvalid                 = "API_KEY_INVALID"
	ErrRequestNotAllowed             = "REQUEST_NOT_ALLOWED"
	ErrNotFound                      = "NOT_FOUND"
	ErrTooManyRequest                = "TOO_MANY_REQUEST"
	ErrInternalError                 = "INTERNAL_ERROR"
)

var codeMap = map[int]string{
	400:  ErrInvalidRequest,
	4001: ErrInvalidJson,
	4003: ErrTrackingAlreadyExist,
	4004: ErrTrackingDoesNotExist,
	4005: ErrTrackingNumberInvalid,
	4006: ErrTrackingRequired,
	4007: ErrTrackingNumberRequired,
	4008: ErrValueInvalid,
	4009: ErrValueRequired,
	4010: ErrSlugInvalid,
	4011: ErrMissingOrInvalidRequiredField,
	4012: ErrBadCourier,
	4013: ErrInactiveRetrackNotAllowed,
	4014: ErrNotificationRequired,
	4015: ErrIdInvalid,
	4016: ErrRetrackOnceAllowed,
	4017: ErrTrackingNumberFormatInvalid,
	401:  ErrApiKeyInvalid,
	403:  ErrRequestNotAllowed,
	404:  ErrNotFound,
	429:  ErrTooManyRequest,
	500:  ErrInternalError,
	502:  ErrInternalError,
	503:  ErrInternalError,
	504:  ErrInternalError,
}

func GetErrorCode(metaCode int, statusCode int) string {
	if code, ok := codeMap[metaCode]; ok {
		return code
	}
	if statusCode >= 400 && statusCode < 500 {
		return ErrBadRequest
	}
	return ErrUnknownError
}
