// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package api

import (
	"github.com/aftership/tracking-sdk-go/v11/component"
	"github.com/aftership/tracking-sdk-go/v11/operation"
)

type CourierConnectionApi struct {
	sender *component.HttpSender
}

func NewCourierConnectionApi(sender *component.HttpSender) *CourierConnectionApi {
	return &CourierConnectionApi{sender: sender}
}

func (this *CourierConnectionApi) GetCourierConnections() *operation.GetCourierConnectionsRequest {
	return operation.NewGetCourierConnectionsRequest(this.sender)
}

func (this *CourierConnectionApi) PostCourierConnections() *operation.PostCourierConnectionsRequest {
	return operation.NewPostCourierConnectionsRequest(this.sender)
}

func (this *CourierConnectionApi) GetCourierConnectionsById() *operation.GetCourierConnectionsByIdRequest {
	return operation.NewGetCourierConnectionsByIdRequest(this.sender)
}

func (this *CourierConnectionApi) PutCourierConnectionsById() *operation.PutCourierConnectionsByIdRequest {
	return operation.NewPutCourierConnectionsByIdRequest(this.sender)
}

func (this *CourierConnectionApi) DeleteCourierConnectionsById() *operation.DeleteCourierConnectionsByIdRequest {
	return operation.NewDeleteCourierConnectionsByIdRequest(this.sender)
}
