// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package api

import (
	"github.com/aftership/tracking-sdk-go/v10/component"
	"github.com/aftership/tracking-sdk-go/v10/operation"
)

type CourierApi struct {
	sender *component.HttpSender
}

func NewCourierApi(sender *component.HttpSender) *CourierApi {
	return &CourierApi{sender: sender}
}

func (this *CourierApi) GetCouriers() *operation.GetCouriersRequest {
	return operation.NewGetCouriersRequest(this.sender)
}

func (this *CourierApi) DetectCourier() *operation.DetectCourierRequest {
	return operation.NewDetectCourierRequest(this.sender)
}
