// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package api

import (
	"github.com/aftership/tracking-sdk-go/v11/component"
	"github.com/aftership/tracking-sdk-go/v11/operation"
)

type EstimatedDeliveryDateApi struct {
	sender *component.HttpSender
}

func NewEstimatedDeliveryDateApi(sender *component.HttpSender) *EstimatedDeliveryDateApi {
	return &EstimatedDeliveryDateApi{sender: sender}
}

func (this *EstimatedDeliveryDateApi) Predict() *operation.PredictRequest {
	return operation.NewPredictRequest(this.sender)
}

func (this *EstimatedDeliveryDateApi) PredictBatch() *operation.PredictBatchRequest {
	return operation.NewPredictBatchRequest(this.sender)
}
