// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package api

import (
	"github.com/aftership/tracking-sdk-go/v11/component"
	"github.com/aftership/tracking-sdk-go/v11/operation"
)

type TrackingApi struct {
	sender *component.HttpSender
}

func NewTrackingApi(sender *component.HttpSender) *TrackingApi {
	return &TrackingApi{sender: sender}
}

func (this *TrackingApi) GetTrackings() *operation.GetTrackingsRequest {
	return operation.NewGetTrackingsRequest(this.sender)
}

func (this *TrackingApi) CreateTracking() *operation.CreateTrackingRequest {
	return operation.NewCreateTrackingRequest(this.sender)
}

func (this *TrackingApi) GetTrackingById() *operation.GetTrackingByIdRequest {
	return operation.NewGetTrackingByIdRequest(this.sender)
}

func (this *TrackingApi) UpdateTrackingById() *operation.UpdateTrackingByIdRequest {
	return operation.NewUpdateTrackingByIdRequest(this.sender)
}

func (this *TrackingApi) DeleteTrackingById() *operation.DeleteTrackingByIdRequest {
	return operation.NewDeleteTrackingByIdRequest(this.sender)
}

func (this *TrackingApi) RetrackTrackingById() *operation.RetrackTrackingByIdRequest {
	return operation.NewRetrackTrackingByIdRequest(this.sender)
}

func (this *TrackingApi) MarkTrackingCompletedById() *operation.MarkTrackingCompletedByIdRequest {
	return operation.NewMarkTrackingCompletedByIdRequest(this.sender)
}
