// Code generated by AfterShip SDK Generator. DO NOT EDIT.

package component

import (
	"context"
	"errors"
	"github.com/aftership/tracking-sdk-go/v10/errorx"
	"math"
	"math/rand"
	"net"
	"net/http"
	"net/url"
	"os"
	"time"
)

type Config struct {
	UserAgent string
	Domain    string
	Timeout   int64
	MaxRetry  int
	Proxy     string
}

type HttpSender struct {
	httpclient *http.Client
	auth       *Authenticator
	Config
}

func NewHttpSender(config Config, auth *Authenticator) *HttpSender {
	client := http.Client{
		Timeout: time.Duration(config.Timeout) * time.Millisecond,
	}
	if len(config.Proxy) > 0 {
		proxyUrl, _ := url.Parse(config.Proxy)
		client.Transport = &http.Transport{
			Proxy: http.ProxyURL(proxyUrl),
		}
	}
	return &HttpSender{
		httpclient: &client,
		auth:       auth,
		Config:     config,
	}
}

func (c *HttpSender) Do(ctx context.Context, request *http.Request) (*http.Response, error) {
	var err error
	request = c.setParam(request)
	request.Header, err = newHeaderBuilder(c.auth).
		buildDefaultHeader(c.UserAgent).
		buildAuthHeader(request).
		build()
	if err != nil {
		return nil, err
	}
	if ctx == nil {
		ctx = context.Background()
	}
	request = request.WithContext(ctx)

	var resp *http.Response
	resp, err = c.httpclient.Do(request)
	if err == nil {
		return resp, nil
	}

	if c.shouldRetry(resp, err) {
		retryResp, errRetry := c.retry(request)
		if errRetry != nil {
			return nil, errRetry
		}
		return retryResp, nil
	}

	return resp, err
}

func (c *HttpSender) retry(req *http.Request) (*http.Response, error) {
	var (
		err       error
		respRetry *http.Response
	)
	for i := 0; i < c.Config.MaxRetry; i++ {
		select {
		case <-req.Context().Done():
			return nil, req.Context().Err()
		case <-time.After(time.Duration(c.delay(i)) * time.Second):
		}

		respRetry, err = c.httpclient.Do(req)
		if err == nil && c.isResponseOk(respRetry.StatusCode) {
			return respRetry, nil
		}
	}
	if req.Context() != nil && req.Context().Err() != nil {
		return nil, req.Context().Err()
	}
	if err != nil {
		var netErr net.Error
		if errors.As(err, &netErr) && netErr.Timeout() {
			return nil, errorx.NewSdkError(errorx.ErrTimedOut, "Request timed out.")
		}
		return nil, errorx.NewSdkError(errorx.ErrUnknownError, "Something went wrong on AfterShip's end.")
	}
	return respRetry, nil
}

func (c *HttpSender) shouldRetry(rawResp *http.Response, rawErr error) bool {
	if os.IsTimeout(rawErr) || (rawResp != nil && rawResp.StatusCode >= 500) {
		return true
	}
	return false
}

func (c *HttpSender) delay(retryAttempt int) int {
	delayBase := 3
	delay := delayBase * (2 ^ (retryAttempt - 1))
	jitter := float64(delay) * (rand.Float64() - 0.5)
	return int(math.Max(1, float64(delay)+jitter))
}

func (c *HttpSender) isResponseOk(code int) bool {
	if code >= http.StatusOK && code < http.StatusMultipleChoices {
		return true
	}
	return false
}

func (c *HttpSender) setParam(request *http.Request) *http.Request {
	u, _ := url.Parse(c.Domain + request.URL.RequestURI())
	request.URL = u
	return request
}
